name: 'ccao_data_athena'
version: '0.1.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'athena'

# These configurations specify where dbt should look for different types of
# files. The `model-paths` config, for example, states that models in this
# project can be found in the "models/" directory. You probably won't need to
# change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Variables that can change with invocation of dbt commands. Note that we parse
# the data_test_iasworld_* variables by name in scripts, so if you change their
# names, make sure you check all of our scripts and adjust them accordingly
vars:
  # Start year for iasWorld data tests. Typically this should be the current
  # year, since errors in past data cannot usually be amended once records are
  # closed. Set as an integer for compatibility with comparison operators and
  # SQL's BETWEEN
  data_test_iasworld_year_start: 2025

  # End year for iasWorld data tests. Typically set to a date in the future,
  # but can also be use to select specific time frames for testing
  data_test_iasworld_year_end: 2030

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  ccao_data_athena:
    +materialized: view
    +write_compression: zstd
    +format: parquet
    +ha: true
    census:
      +schema: census
    default:
      +schema: default
    location:
      +schema: location
    model:
      +schema: model
    proximity:
      +schema: proximity
    reporting:
      +schema: reporting
    sale:
      +schema: sale
    spatial:
      +schema: spatial
    qc:
      +schema: qc
data_tests:
  +schema: test_failure

seeds:
  ccao_data_athena:
    ccao:
      +schema: ccao
    location:
      +schema: location
    model:
      +schema: model
    spatial:
      +schema: spatial
