name: 'athena'
version: '0.1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'athena'

# These configurations specify where dbt should look for different types of
# files. The `model-paths` config, for example, states that models in this
# project can be found in the "models/" directory. You probably won't need to
# change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]


# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  athena:
    +materialized: view
    ccao:
      # Set default materialization on a per-schema basis. Schemas that contain
      # _any_ persistent models should be set to `view` or `table`, or left
      # to inherit the `view` default which is set on the `athena` project, but
      # schemas that are entirely ephemeral should be marked `ephemeral`. The
      # point of this pattern of defaults is that schemas with non-ephemeral
      # defaults will be marked for deletion by the cleanup_dbt_resources.sh
      # script, since `dbt list --select config.materialization:view` only
      # reads this config file and does not consider model-level overrides.
      # Hence, only schemas that contain exclusively ephemeral models should
      # be marked with an `ephemeral` default, since we won't build those
      # schemas into Athena and we don't want cleanup_dbt_resources.sh to
      # try to clean them up.
      +materialized: ephemeral
      +schema: ccao
    census:
      +schema: census
    default:
      +schema: default
    iasworld:
      +materialized: ephemeral
      +schema: iasworld
    location:
      +schema: location
    model:
      +schema: model
    other:
      +materialized: ephemeral
      +schema: other
    proximity:
      +schema: proximity
    reporting:
      +schema: reporting
    rpie:
      +schema: rpie
    spatial:
      +materialized: ephemeral
      +schema: spatial
    tax:
      +materialized: ephemeral
      +schema: tax
