name: 'ccao_data_athena'
version: '0.1.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'athena'

# These configurations specify where dbt should look for different types of
# files. The `model-paths` config, for example, states that models in this
# project can be found in the "models/" directory. You probably won't need to
# change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]


# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Variables that can change with invocation of dbt commands. Note that we parse
# the test_* variables by name in scripts, so if you change their names, make
# sure you check all of our scripts and adjust them accordingly
vars:
  # Start year for testing data using test_qc_* tagged dbt tests. Typically
  # this should be the current year, since errors in past data cannot usually
  # be amended once records are closed. Set as an integer for compatibility
  # with comparison operators and SQL's BETWEEN
  test_qc_year_start: 2024

  # End year for testing data using test_qc_* tagged dbt tests. Typically set
  # to a date in the future, but can also be use to select specific time
  # frames for testing
  test_qc_year_end: 2030

  # Locations in S3 where Python model dependencies are stored. Since these
  # locations vary by target, it would be nice if we could define them as target
  # attributes in profiles.yml, but we can't add new profiles.yml attributes
  # without extending dbt-athena so we define the locations here instead
  s3_dependency_dir_dev: s3://ccao-dbt-athena-dev-us-east-1/dependencies
  s3_dependency_dir_ci: s3://ccao-dbt-athena-ci-us-east-1/dependencies
  s3_dependency_dir_prod: s3://ccao-athena-dependencies-us-east-1

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  ccao_data_athena:
    +materialized: view
    +write_compression: zstd
    +format: parquet
    ccao:
      +schema: ccao
    census:
      +schema: census
    default:
      +schema: default
    location:
      +schema: location
    model:
      +schema: model
    proximity:
      +schema: proximity
    reporting:
      +schema: reporting
    sale:
      +schema: sale
    qc:
      +schema: qc
tests:
  +schema: test_failure

seeds:
  ccao_data_athena:
    ccao:
      +schema: ccao
    location:
      +schema: location
    model:
      +schema: model
