name: 'athena'
version: '0.1.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'athena'

# These configurations specify where dbt should look for different types of
# files. The `model-paths` config, for example, states that models in this
# project can be found in the "models/" directory. You probably won't need to
# change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]


# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # Start year for testing data using test_qc_* tagged dbt tests. Typically
  # this should be the current year, since errors in past data cannot usually
  # be amended once records are closed. Set as an integer for compatibility
  # with comparison operators and SQL's BETWEEN
  test_qc_year_start: 2023

  # End year for testing data using test_qc_* tagged dbt tests. Typically set
  # to a date in the future, but can also be use to select specific time
  # frames for testing
  test_qc_year_end: 2030

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  athena:
    +materialized: view
    +write_compression: zstd
    +format: parquet
    census:
      +schema: census
    default:
      +schema: default
    location:
      +schema: location
    model:
      +schema: model
    proximity:
      +schema: proximity
    reporting:
      +schema: reporting
    rpie:
      +schema: rpie
    sale:
      +schema: sale
    qc:
      +schema: qc
tests:
  +schema: test_failure
