athena:
  target: dev
  outputs:
    dev:
      type: athena
      s3_staging_dir: s3://ccao-dbt-athena-dev-us-east-1/results/
      s3_data_dir: s3://ccao-dbt-athena-dev-us-east-1/data/
      s3_data_naming: schema_table
      region_name: us-east-1
      # "schema" here corresponds to a Glue database
      schema: dbt-test
      # "database" here corresponds to a Glue data catalog
      database: awsdatacatalog
      threads: 5
    ci:
      type: athena
      s3_staging_dir: s3://ccao-dbt-athena-ci-us-east-1/results/
      s3_data_dir: s3://ccao-dbt-athena-ci-us-east-1/data/
      s3_data_naming: schema_table
      region_name: us-east-1
      schema: dbt-test
      database: awsdatacatalog
      threads: 5
    prod:
      type: athena
      s3_staging_dir: s3://ccao-athena-results-us-east-1/
      s3_data_dir: s3://ccao-athena-ctas-us-east-1/
      s3_data_naming: schema_table
      region_name: us-east-1
      schema: default
      database: awsdatacatalog
      threads: 5
