models:
  - name: pinval.vw_pinval_comp
    description: '{{ doc("vw_pinval_comp") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_comp_unique_run_id_pin_card_comp_num
          combination_of_columns:
            - run_id
            - pin
            - card
            - comp_num
          config:
            error_if: ">0"

  - name: pinval.vw_pinval_assessment_card
    description: '{{ doc("vw_pinval_assessment_card") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_assessment_card_unique_run_id_pin_card
          combination_of_columns:
            - run_id
            - meta_pin
            - meta_card_num
          allowed_duplicates: 0
          config:
            error_if: ">0"