models:
  - name: pinval.vw_comp
    description: '{{ doc("view_pinval_vw_comp") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_comp_unique_run_id_pin_card_comp_num
          combination_of_columns:
            - run_id
            - pin
            - card
            - comp_num

  - name: pinval.vw_assessment_card
    description: '{{ doc("view_pinval_vw_assessment_card") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_assessment_card_unique_run_id_pin_card
          combination_of_columns:
            - run_id
            - meta_pin
            - meta_card_num
