--IF EXISTS(
--	SELECT 1 
--	FROM dbo.sysobjects 
--	WHERE id = OBJECT_ID('dbo.VW_RPIE_NOTICE_PINS')
--	) DROP VIEW dbo.VW_RPIE_NOTICE_PINS
--	GO

--CREATE VIEW VW_RPIE_NOTICE_PINS
--AS
declare @AlLChars varchar(100) = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
SELECT DISTINCT top 100 cast('PIN-' + PL_PIN as varchar(max)) as PIN, RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' +
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1)
AS Unique_Value, 
PL_HOUSE_NO, PL_DIR, PL_STR_NAME, PL_STR_SUFFIX, PL_APT_NO, PL_CITY_NAME, 'IL' as PL_State, PL_ZIPCODE, D.HD_NAME as Mailing_Name, D.HD_ADDR as Mailing_Address, D.HD_CITY as Mailing_City,
D.HD_ZIP as Mailing_Zip, '11/25/2019' as Notice_Deadline, B.MV as Apt_MV, C.MV as Comm_MV,
CASE WHEN B.MV>=5000000 THEN '1' ELSE '0' END AS FiveMM_AptMV,
CASE WHEN C.MV>=5000000 THEN '1' ELSE '0' END AS FiveMM_CommMV
FROM PROPLOCS A
LEFT JOIN (SELECT DISTINCT HD_PIN, (HD_PRI_LND + HD_PRI_BLD)*10 as MV FROM HEAD WHERE Left(HD_CLASS,1) IN (3) and TAX_YEAR=2018) AS B ON A.PL_PIN=B.HD_PIN
LEFT JOIN (SELECT DISTINCT HD_PIN, (HD_PRI_LND + HD_PRI_BLD)*4 as MV FROM HEAD WHERE Left(HD_CLASS,1) IN (5) and TAX_YEAR=2018) AS C ON A.PL_PIN=C.HD_PIN
LEFT JOIN HEAD D ON D.HD_PIN = A.PL_PIN WHERE Left(HD_CLASS,1) IN (3,5) AND TAX_YEAR=2018 AND HD_CLASS NOT IN (593)
  --Group By PL_PIN, PL_HOUSE_NO, PL_DIR, PL_STR_NAME, PL_STR_SUFFIX, PL_APT_NO, PL_CITY_NAME, PL_ZIPCODE, D.HD_NAME, D.HD_ADDR, D.HD_CITY, D.HD_ZIP, B.MV, C.MV
  --GO
	 
