SELECT * FROM VW_RES_UNIVERSE AS UNIVERSE
LEFT JOIN
	VW_PINGEO GEO
	ON UNIVERSE.PIN = GEO.PIN
LEFT JOIN
	VW_MOST_RECENT_IDORSALES SALES
	ON UNIVERSE.PIN = SALES.PIN

WHERE UNIVERSE.TAX_YEAR = (SELECT MAX(TAX_YEAR) FROM AS_HEADT)