



SELECT 'PIN'+PIN AS PIN
, CL_CLS AS PROPERTY_CLASS
, CL_ASSD_VAL AS ASSESSED_VALUE_2018
, FACTOR*CL_ASSD_VAL AS EQUALIZED_ASSESSED_VALUE_2018
, CL_TXCD AS TAX_CODE
, 'CBD (Ashland, Division, Roosevelt)' AS CBD
  , CASE WHEN PL_HOUSE_NO IS NULL THEN 'ADDRESS MISSING FROM PROPLOCS' ELSE
  LTRIM(RTRIM(CAST(PL_HOUSE_NO as varchar(10)))) + ' ' + LTRIM(RTRIM(PL_DIR))+ ' ' + LTRIM(RTRIM(PL_STR_NAME))+
' ' + LTRIM(RTRIM(PL_STR_SUFFIX)) + ' ' + LTRIM(RTRIM(PL_CITY_NAME)) +', Illinois ' + LTRIM(RTRIM(PL_ZIPCODE)) END as PROPERTY_ADDRESS
FROM PINGEO AS GEO
INNER JOIN CLERKVALUES AS CLRK 
ON LEFT(GEO.Name, 10)=LEFT(CLRK.PIN, 10) 
INNER JOIN FTBL_EQUALIZATION_FACTOR AS F
ON F.TAX_YEAR=CLRK.TAX_YEAR
WHERE centroid_x>=-87.668643 AND centroid_y<=41.866924 AND centroid_y<=41.903327
AND CLRK.TAX_YEAR=2018
AND LEFT(CL_CLS , 1) IN (3, 5, 6, 7, 8, 9)
