
/* Sums the total tax base by year. Our checksum values are 76,609,267,827 in 2017 and 86,326,178,932 in 2018 */
SELECT TAX_YEAR, SUM(TOTAL_BOR_EAV) AS TOTAL_BOR_EAV, SUM(TOTAL_CLERK_EXEMPTIONS) AS TOTAL_CLERK_EXEMPTIONS
, SUM(TOTAL_BOR_EAV)-SUM(TOTAL_CLERK_EXEMPTIONS) AS TOTAL_EAV
, CASE WHEN TAX_YEAR=2017 THEN 8969561584
	WHEN TAX_YEAR=2018 THEN 12208310713
	ELSE NULL END AS TIF_INCREMENET 
, CASE WHEN TAX_YEAR=2017 THEN 76609267827 
	WHEN TAX_YEAR=2018 THEN 86326178932 
		ELSE NULL END AS CHECK_SUM
, CASE WHEN TAX_YEAR=2017 THEN (SUM(TOTAL_BOR_EAV)-SUM(TOTAL_CLERK_EXEMPTIONS)-8969561584-76609267827)/76609267827
		WHEN TAX_YEAR=2018 THEN (SUM(TOTAL_BOR_EAV)-SUM(TOTAL_CLERK_EXEMPTIONS)-12208310713-86326178932)/86326178932 
		ELSE NULL END AS PCT_VARIANCE_TOTAL
/* , CASE WHEN TAX_YEAR=2017 THEN (SUM(TOTAL_BOR_EAV)-SUM(TOTAL_CLERK_EXEMPTIONS)-SUM(ALT_DIS_VET_80_EX)-12208310713-76609267827)/76609267827
		WHEN TAX_YEAR=2018 THEN (SUM(TOTAL_BOR_EAV)-SUM(TOTAL_CLERK_EXEMPTIONS)-SUM(ALT_DIS_VET_80_EX)-8969561584-86326178932)/86326178932 
		ELSE NULL END AS PCT_VARIANCE_ALT_TOTAL */
FROM (
	/* This inner query returns the data aggregated at the tax code level */
	/* This part to R */
	SELECT X.TAX_YEAR, X.TAX_CODE, X.TOWNSHIP, X.MAJOR_CLASS
	, PIN_COUNT
	, X.TOTAL_BOR_EAV, TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX AS TOTAL_CLERK_EXEMPTIONS FROM (  
	  SELECT
	  H.TAX_YEAR
	  , CL_TXCD AS TAX_CODE
	  , HD_TOWN AS TOWNSHIP 
	  , LEFT(HD_CLASS, 1) AS MAJOR_CLASS
	  /* PART 1: Total EAV, excluding disabled vets with >70% disability,
		aggregated from the Board of Review Head file */
	  , SUM(HD_ASS_LND*FACTOR+HD_ASS_BLD*FACTOR) AS TOTAL_BOR_EAV
	  , COUNT(H.PIN) AS PIN_COUNT
	  /* PART 2. Total Exempt EAV, excluding disabled vets with >70% disability
			, aggregated from the Clerk's exemtpion data. */
	  , SUM(CLRK.CL_DIS_IND+CLRK.CL_DIS_VET+CL_FREEZE_EXE_AMT+CL_HOMOWN_EXE_AMT+
	 CL_HOMSTD_EXE_AMT+CL_RET_VET+CL_DIS_VET_GE75K+
	 CL_DIS_VET_LT75K+CL_EXOWNEXVAL) AS TOTAL_CLERK_EXEMPTIONS
	  FROM AS_HEADBR AS H   
	  LEFT JOIN EXEMPTIONS AS E
		ON E.PIN=H.PIN AND E.TAX_YEAR=H.TAX_YEAR
	  LEFT JOIN FTBL_EQUALIZATION_FACTOR AS F
		ON H.TAX_YEAR=F.TAX_YEAR
	  LEFT JOIN	CLERKVALUES AS CLRK   
		ON CLRK.CL_PIN=H.PIN AND CLRK.TAX_YEAR=H.TAX_YEAR
	  WHERE (1=1) 
	  AND H.TAX_YEAR>=2017 
	  AND HD_TOWN IN (70, 71, 72, 73, 74, 75, 76, 77)
	  AND HD_ASS_LND*FACTOR+HD_ASS_BLD*FACTOR>=150 
	  GROUP BY H.TAX_YEAR, CL_TXCD, HD_TOWN, LEFT(HD_CLASS, 1)
	 ) AS X
	LEFT JOIN
	( /* PART 3. Total EAV for disabled veterans >70% are actually exemptions, up to 250,000.
		 Though these are EAVs, they are actually subtracted from the base as exemptions. */
	SELECT TAX_YEAR, TOWNSHIP, MAJOR_CLASS, TAX_CODE, SUM(DIS_VET_80_EX) AS DIS_VET_80_EX
	FROM 
	( SELECT H.TAX_YEAR
	  , CLRK.CL_TXCD AS TAX_CODE
	  , HD_TOWN AS TOWNSHIP 
	  , LEFT(HD_CLASS, 1) AS MAJOR_CLASS
	  /* Take EAV for these PINs up to 250k as an exemption, deducted from the base */
	  , CASE WHEN HD_ASS_LND*FACTOR+HD_ASS_BLD*FACTOR <250000 THEN HD_ASS_LND*FACTOR+HD_ASS_BLD*FACTOR ELSE 250000 END AS DIS_VET_80_EX
	FROM AS_HEADBR AS H
	LEFT JOIN CLERKVALUES AS CLRK
		ON CLRK.PIN=H.PIN AND CLRK.TAX_YEAR=H.TAX_YEAR
	LEFT JOIN FTBL_EQUALIZATION_FACTOR AS F
		ON H.TAX_YEAR=F.TAX_YEAR
		WHERE (1=1)
		AND H.TAX_YEAR>=2017 
		AND HD_TOWN IN (70, 71, 72, 73, 74, 75, 76, 77)
		AND HD_ASS_LND*FACTOR+HD_ASS_BLD*FACTOR>=150 
		AND CL_DIS_IND=8 
		 ) AS XXX
		 GROUP BY TAX_YEAR,TAX_CODE,TOWNSHIP, MAJOR_CLASS
		 ) AS XX
	ON X.TAX_YEAR=XX.TAX_YEAR 
	AND X.TAX_CODE=XX.TAX_CODE
	AND X.TOWNSHIP=XX.TOWNSHIP
	AND X.MAJOR_CLASS=XX.MAJOR_CLASS
/* END part for R */
) AS TOT
GROUP BY TAX_YEAR

