SELECT X.TAX_YEAR, X.TAX_CODE, X.TOWNSHIP, X.TOTAL_BOR_EAV, XY.TOTAL_CLERK_EXEMPTIONS, XX.DIS_VET_80_EX FROM (  
/* PART 1: Total EAV, excluding disabled vets with >70% disability,
	aggregated from the Board of Review Head file */
  SELECT
  H.TAX_YEAR
  , TAXCDE AS TAX_CODE
  , TOWN AS TOWNSHIP 
  , SUM(LANDVAL*FACTOR+BLDGVAL*FACTOR) AS TOTAL_BOR_EAV
  FROM BAMASTER AS H   
  LEFT JOIN EXEMPTIONS AS E
    ON E.PIN=H.PIN AND E.TAX_YEAR=H.TAX_YEAR
  LEFT JOIN FTBL_EQUALIZATION_FACTOR AS F
    ON H.TAX_YEAR=F.TAX_YEAR
  WHERE (1=1) 
  AND H.TAX_YEAR>=2017 
  AND TOWN IN (70, 71, 72, 73, 74, 75, 76, 77)
  AND LANDVAL*FACTOR+BLDGVAL*FACTOR>=150 
  GROUP BY H.TAX_YEAR, TAXCDE, TOWN 
	) AS X
LEFT JOIN
( /* PART 2. Total Exempt EAV, excluding disabled vets with >70% disability
		, aggregated from the Clerk's exemtpion data. */
SELECT CLRK.TAX_YEAR
  , CL_TXCD AS TAX_CODE
  , BA.TOWN AS TOWNSHIP 
 , SUM(CLRK.CL_DIS_IND+CLRK.CL_DIS_VET+CL_FREEZE_EXE_AMT+CL_HOMOWN_EXE_AMT+
 CL_HOMSTD_EXE_AMT+CL_RET_VET+CL_DIS_VET_GE75K+
 CL_DIS_VET_LT75K+CL_EXOWNEXVAL) AS TOTAL_CLERK_EXEMPTIONS
	FROM CLERKVALUES AS CLRK   
	LEFT JOIN BAMASTER AS BA
    ON CLRK.CL_PIN=BA.PIN AND CLRK.TAX_YEAR=BA.TAX_YEAR
	LEFT JOIN FTBL_EQUALIZATION_FACTOR AS F
    ON CLRK.TAX_YEAR=F.TAX_YEAR
    WHERE (1=1) 
	AND CLRK.TAX_YEAR>=2017 
	AND TOWN IN (70, 71, 72, 73, 74, 75, 76, 77)
	AND LANDVAL*FACTOR+BLDGVAL*FACTOR>=150 
	AND CL_DIS_IND!=8
	  GROUP BY CLRK.TAX_YEAR, CL_TXCD, BA.TOWN ) AS XY
ON X.TAX_YEAR= XY.TAX_YEAR 
AND X.TAX_CODE= XY.TAX_CODE
AND X.TOWNSHIP= XY.TOWNSHIP
LEFT JOIN
( /* PART 3. Total EAV for disabled veterans >70% are actually exemptions, up to 250,000.
     Though these are EAVs, they are actually subtracted from the base as exemptions. */
SELECT TAX_YEAR, TOWNSHIP, TAX_CODE, SUM(DIS_VET_80_EX) AS DIS_VET_80_EX, SUM(DIS_VET_80_EAV) AS DIS_VET_80_EAV FROM 
( SELECT H.TAX_YEAR
  , TAXCDE AS TAX_CODE
  , TOWN AS TOWNSHIP 
  /* Take EAV for these PINs up to 250k as an exemption, deducted from the base */
  , CASE WHEN LANDVAL*FACTOR+BLDGVAL*FACTOR <2500000 THEN LANDVAL*FACTOR+BLDGVAL*FACTOR ELSE 250000 END AS DIS_VET_80_EX
  /* Anything over 250k is added to the base as taxable EAV*/
  , CASE WHEN LANDVAL*FACTOR+BLDGVAL*FACTOR >2500000 THEN LANDVAL*FACTOR+BLDGVAL*FACTOR-2500000 ELSE 0 END AS DIS_VET_80_EAV
FROM BAMASTER AS H
LEFT JOIN CLERKVALUES AS CLRK
	ON CLRK.PIN=H.PIN AND CLRK.TAX_YEAR=H.TAX_YEAR
LEFT JOIN FTBL_EQUALIZATION_FACTOR AS F
    ON H.TAX_YEAR=F.TAX_YEAR
	WHERE (1=1)
	AND H.TAX_YEAR>=2017 
	AND TOWN IN (70, 71, 72, 73, 74, 75, 76, 77)
	AND LANDVAL*FACTOR+BLDGVAL*FACTOR>=150 
	AND CL_DIS_IND=8 
	 ) AS XXX
	 GROUP BY TAX_YEAR,TAX_CODE,TOWNSHIP
	 ) AS XX
ON X.TAX_YEAR=XX.TAX_YEAR 
AND X.TAX_CODE=XX.TAX_CODE
AND X.TOWNSHIP=XX.TOWNSHIP
WHERE X.TAX_YEAR=2018
