ALTER VIEW VW_CLEAN_IDORSALES AS

SELECT

B.PIN, B.RECORDED_DATE as sale_date, B.SALE_PRICE as sale_price, B.DOC_NO, B.DEED_TYPE, YEAR(B.RECORDED_DATE) AS TAX_YEAR

FROM IDORSALES AS B

/* Arbitrarily select a deed */
INNER JOIN
	(SELECT DISTINCT A.PIN, A.RECORDED_DATE, A.SALE_PRICE, MAX(A.DOC_NO) AS DOC_NO FROM IDORSALES AS A
	/* Largest sale price by PIN and date */
	INNER JOIN
		(SELECT X.PIN, X.RECORDED_DATE, MAX(X.SALE_PRICE) AS SALE_PRICE FROM IDORSALES AS X
		GROUP BY X.PIN, X.RECORDED_DATE) AS SSS
		ON A.PIN = SSS.PIN AND A.RECORDED_DATE = SSS.RECORDED_DATE AND A.SALE_PRICE = SSS.SALE_PRICE
		GROUP BY A.PIN, A.RECORDED_DATE, A.SALE_PRICE) AS WW
	ON WW.PIN = B.PIN AND WW.RECORDED_DATE = B.RECORDED_DATE AND WW.DOC_NO = B.DOC_NO
WHERE B.DEED_TYPE NOT IN ('Q', 'E', 'B')
	AND MULT_IND = ''
	AND YEAR(B.RECORDED_DATE)> = 1997