ALTER VIEW VW_MOST_RECENT_IDORSALES AS

SELECT DISTINCT

B.PIN, B.RECORDED_DATE as most_recent_sale_date, CONVERT(FLOAT, B.SALE_PRICE) as most_recent_sale_price, B.DOC_NO, B.DEED_TYPE

FROM IDORSALES AS B

INNER JOIN
	(SELECT DISTINCT A.PIN, A.RECORDED_DATE, A.SALE_PRICE, MAX(A.DOC_NO) AS DOC_NO FROM IDORSALES AS A
	INNER JOIN
		(SELECT X.PIN, SS.RECORDED_DATE, MAX(X.SALE_PRICE) AS SALE_PRICE FROM IDORSALES AS X
		INNER JOIN
			(SELECT PIN, MAX(RECORDED_DATE)  as RECORDED_DATE FROM IDORSALES
			WHERE DEED_TYPE NOT IN ('Q', 'E', 'B')
				AND MULT_IND = ''
            GROUP BY PIN) AS SS
			ON X.PIN=SS.PIN AND X.RECORDED_DATE=SS.RECORDED_DATE
		GROUP BY X.PIN, SS.RECORDED_DATE) AS SSS
		ON A.PIN=SSS.PIN AND A.RECORDED_DATE=SSS.RECORDED_DATE AND A.SALE_PRICE=SSS.SALE_PRICE
	GROUP BY A.PIN, A.RECORDED_DATE, A.SALE_PRICE) AS WW
	ON WW.PIN=B.PIN AND WW.RECORDED_DATE=B.RECORDED_DATE AND WW.DOC_NO=B.DOC_NO

WHERE B.DEED_TYPE NOT IN ('Q', 'E', 'B')
	AND (B.DEED_TYPE != '' OR YEAR(B.RECORDED_DATE) <= 2000)