ALTER VIEW VW_OPENDATA_ASSESSMENTS AS

/* first pass values */
SELECT DISTINCT HEADT.PIN, HEADT.HD_CLASS AS CLASS, HEADT.HD_NBHD AS NBHD, LEFT(HEADT.HD_TOWN, 2) AS TOWN, HEADT.TAX_YEAR AS [YEAR],
[MODEL RESULT], [PIPELINE RESULT],
(HEADT.HD_ASS_BLD + HEADT.HD_ASS_LND) * 10 AS [FIRST PASS], CERTIFIED,
CASE WHEN [APPEALED] = 1 THEN 'YES' ELSE 'NO' END AS [APPEALED],
[NUM REVIEWED],
CASE WHEN [CHANGED] = 1 THEN 'YES' WHEN [CHANGED] = 0 THEN 'NO' ELSE NULL END AS [CHANGED] 
, (BOR.HD_ASS_LND + BOR.HD_ASS_BLD)*10 AS [BOR RESULT]

FROM AS_HEADT HEADT
LEFT JOIN
	/* second pass values */
	(SELECT PIN, (HD_ASS_BLD + HD_ASS_LND) * 10 AS CERTIFIED, TAX_YEAR FROM AS_HEADTB) AS HEADTB

ON HEADT.PIN = HEADTB.PIN AND HEADT.TAX_YEAR = HEADTB.TAX_YEAR

LEFT JOIN

	(SELECT
		/* appeals data */
		PIN, CASE WHEN PC_PIN_RESULT_1 = 'C' OR PC_PIN_RESULT_2 = 'C' OR PC_PIN_RESULT_3 = 'C' THEN 1 ELSE 0 END AS [CHANGED],
		CASE WHEN PC_PIN_RESULT_3 != '' AND PC_PIN_RESULT_2 = '' THEN 1
		WHEN PC_PIN_RESULT_2 != '' AND PC_PIN_RESULT_1 = '' THEN 2
		WHEN PC_PIN_RESULT_1 != '' THEN 3
		ELSE 0 END AS [NUM REVIEWED],
		1 AS [APPEALED], TAX_YEAR

	FROM APPEALSDATA) AS APPEALS

ON HEADT.PIN = APPEALS.PIN AND HEADT.TAX_YEAR = APPEALS.TAX_YEAR

LEFT JOIN 
/* BOR Results */
AS_HEADBR AS BOR
ON HEADT.PIN=BOR.PIN AND HEADT.TAX_YEAR=BOR.TAX_YEAR

LEFT JOIN 
/* model and pipeline values, need to make sure only values from the latest version are ingested */
(SELECT UNIVERSE.PIN, UNIVERSE.TAX_YEAR AS YEAR, fitted_value_1 AS [MODEL RESULT], fitted_value_6 AS [PIPELINE RESULT], CASE WHEN UNIVERSE.version IS NULL THEN 0 ELSE UNIVERSE.version END as VERSION
  FROM DTBL_MODELVALS AS UNIVERSE

INNER JOIN

(SELECT PIN, TAX_YEAR, MAX(CASE WHEN version IS NULL THEN 0 ELSE VERSION END) AS VERSION
	FROM DTBL_MODELVALS
	GROUP BY PIN, TAX_YEAR) MAX_VERSION

ON UNIVERSE.PIN = MAX_VERSION.PIN AND UNIVERSE.TAX_YEAR = MAX_VERSION.TAX_YEAR AND CASE WHEN UNIVERSE.version IS NULL THEN 0 ELSE UNIVERSE.version END = MAX_VERSION.VERSION) FITTED_VALUES

ON HEADT.PIN = FITTED_VALUES.PIN AND HEADT.TAX_YEAR = FITTED_VALUES.YEAR

WHERE HEADT.HD_CLASS IN (200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 234, 241, 278, 295, 299)
