/* This view is used for RPIE notifications. Each PIN number is paired with a unique, random string of letters and numbers. 
Mailing and property addresses are also brought in */


declare @AlLChars varchar(100) = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

SELECT A.HD_PIN AS RPIE_PIN, RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' +
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1)
AS RPIE_CODE, triad_name, FTBL_TOWNCODES.township_name, HD_NAME AS MAILING_NAME, PROPERTY_ADDRESS, PROPERTY_APT_NO, PROPERTY_CITY, PROPERTY_ZIP, MAILING_ADDRESS, MAILING_CITY, MAILING_ZIP
FROM (SELECT HD_PIN,HD_TOWN, HD_NAME, HD_PRI_LND + HD_PRI_BLD as Assessed_Value FROM AS_HEADT WHERE TAX_YEAR=2019 AND LEFT(HD_CLASS, 1) NOT IN ('0', '1','2', '4')) AS A
LEFT JOIN VW_PINGEO AS B ON A.HD_PIN=B.PIN
LEFT JOIN FTBL_TOWNCODES ON LEFT(A.HD_TOWN,2)=township_code
