ALTER VIEW VW_RES_RATIOS AS

SELECT SALES.PIN, sale_price, sale_date, DATE_A_ROLL_CERTIFIED, BOARD_CLOSE_DATE, FMV, FMV / sale_price AS RATIO, HEAD.TAX_YEAR, HEAD.TOWN_CODE, [modeling_group]

FROM VW_CLEAN_IDORSALES AS SALES

LEFT JOIN

(SELECT PIN, LEFT(HD_TOWN, 2) AS TOWN_CODE, TAX_YEAR, (HD_ASS_LND + HD_ASS_BLD) * 10 AS FMV,
	CASE WHEN HD_CLASS IN (202, 203, 204, 205, 206, 207, 208, 209, 210, 234, 278, 295) THEN 'SF'
	WHEN HD_CLASS IN (211, 212) THEN 'MF'
	WHEN HD_CLASS IN (200, 201, 241) OR (HD_CLASS = 299 AND ((HD_PRI_BLD + HD_PRI_LND) > 10 OR (HD_PRI_BLD + HD_PRI_LND) IS NULL)) THEN 'NCHARS'
	ELSE NULL END AS [modeling_group]
	
	FROM AS_HEADTB) AS HEAD

ON SALES.PIN = HEAD.PIN

LEFT JOIN

(SELECT CODE, DATE_A_ROLL_CERTIFIED, BOARD_CLOSE_DATE, TAX_YEAR
	
	FROM FTBL_CERT_DATES) AS CERTIFIED

ON CERTIFIED.CODE = HEAD.TOWN_CODE AND CERTIFIED.TAX_YEAR = HEAD.TAX_YEAR

WHERE sale_price > 10000
	AND HEAD.TOWN_CODE IS NOT NULL
	AND [modeling_group] IS NOT NULL
	AND (DATEDIFF(DAY, DATE_A_ROLL_CERTIFIED, sale_date) BETWEEN 0 AND 365 OR (YEAR(sale_date) = (SELECT MAX(TAX_YEAR) FROM AS_HEADTB) AND HEAD.TAX_YEAR = (SELECT MAX(TAX_YEAR) FROM AS_HEADT)))