-- Most-recent-year-only copy of defualt.vw_pin_universe. Feeds the "Parcel
-- Universe (Current Year)" open data asset.
-- Some columns from the feeder view may not be present in this view.

SELECT
    feeder.pin,
    feeder.pin10,
    feeder.class,
    feeder.triad_name,
    feeder.triad_code,
    feeder.township_name,
    feeder.township_code,
    feeder.nbhd_code,
    feeder.tax_code,
    feeder.zip_code,
    feeder.lon,
    feeder.lat,
    feeder.x_3435,
    feeder.y_3435,
    feeder.census_block_group_geoid,
    feeder.census_block_geoid,
    feeder.census_congressional_district_geoid,
    feeder.census_congressional_district_num,
    feeder.census_county_subdivision_geoid,
    feeder.census_place_geoid,
    feeder.census_puma_geoid,
    feeder.census_school_district_elementary_geoid,
    feeder.census_school_district_secondary_geoid,
    feeder.census_school_district_unified_geoid,
    feeder.census_state_representative_geoid,
    feeder.census_state_representative_num,
    feeder.census_state_senate_geoid,
    feeder.census_state_senate_num,
    feeder.census_tract_geoid,
    feeder.census_zcta_geoid,
    feeder.census_data_year,
    feeder.census_acs5_congressional_district_geoid,
    feeder.census_acs5_congressional_district_num,
    feeder.census_acs5_county_subdivision_geoid,
    feeder.census_acs5_place_geoid,
    feeder.census_acs5_puma_geoid,
    feeder.census_acs5_school_district_elementary_geoid,
    feeder.census_acs5_school_district_secondary_geoid,
    feeder.census_acs5_school_district_unified_geoid,
    feeder.census_acs5_state_representative_geoid,
    feeder.census_acs5_state_representative_num,
    feeder.census_acs5_state_senate_geoid,
    feeder.census_acs5_state_senate_num,
    feeder.census_acs5_tract_geoid,
    feeder.census_acs5_data_year,
    feeder.cook_board_of_review_district_num,
    feeder.cook_board_of_review_district_data_year,
    feeder.cook_commissioner_district_num,
    feeder.cook_commissioner_district_data_year,
    feeder.cook_judicial_district_num,
    feeder.cook_judicial_district_data_year,
    feeder.ward_num,
    feeder.ward_chicago_data_year,
    feeder.ward_evanston_data_year,
    feeder.chicago_community_area_num,
    feeder.chicago_community_area_name,
    feeder.chicago_community_area_data_year,
    feeder.chicago_industrial_corridor_num,
    feeder.chicago_industrial_corridor_name,
    feeder.chicago_industrial_corridor_data_year,
    feeder.chicago_police_district_num,
    feeder.chicago_police_district_data_year,
    feeder.econ_coordinated_care_area_num,
    feeder.econ_coordinated_care_area_data_year,
    feeder.econ_enterprise_zone_num,
    feeder.econ_enterprise_zone_data_year,
    feeder.econ_industrial_growth_zone_num,
    feeder.econ_industrial_growth_zone_data_year,
    feeder.econ_qualified_opportunity_zone_num,
    feeder.econ_qualified_opportunity_zone_data_year,
    feeder.econ_central_business_district_num,
    feeder.econ_central_business_district_data_year,
    feeder.env_flood_fema_sfha,
    feeder.env_flood_fema_data_year,
    feeder.env_flood_fs_factor,
    feeder.env_flood_fs_risk_direction,
    feeder.env_flood_fs_data_year,
    feeder.env_ohare_noise_contour_no_buffer_bool,
    feeder.env_ohare_noise_contour_half_mile_buffer_bool,
    feeder.env_ohare_noise_contour_data_year,
    feeder.env_airport_noise_dnl,
    feeder.env_airport_noise_data_year,
    feeder.school_elementary_district_geoid,
    feeder.school_elementary_district_name,
    feeder.school_secondary_district_geoid,
    feeder.school_secondary_district_name,
    feeder.school_unified_district_geoid,
    feeder.school_unified_district_name,
    feeder.school_school_year,
    feeder.school_data_year,
    {{ array_join("tax_municipality_num") }},
    {{ array_join("tax_municipality_name") }},
    {{ array_join("tax_school_elementary_district_num") }},
    {{ array_join("tax_school_elementary_district_name") }},
    {{ array_join("tax_school_secondary_district_num") }},
    {{ array_join("tax_school_secondary_district_name") }},
    {{ array_join("tax_school_unified_district_num") }},
    {{ array_join("tax_school_unified_district_name") }},
    {{ array_join("tax_community_college_district_num") }},
    {{ array_join("tax_community_college_district_name") }},
    {{ array_join("tax_fire_protection_district_num") }},
    {{ array_join("tax_fire_protection_district_name") }},
    {{ array_join("tax_library_district_num") }},
    {{ array_join("tax_library_district_name") }},
    {{ array_join("tax_park_district_num") }},
    {{ array_join("tax_park_district_name") }},
    {{ array_join("tax_sanitation_district_num") }},
    {{ array_join("tax_sanitation_district_name") }},
    {{ array_join("tax_special_service_area_num") }},
    {{ array_join("tax_special_service_area_name") }},
    {{ array_join("tax_tif_district_num") }},
    {{ array_join("tax_tif_district_name") }},
    feeder.tax_data_year,
    feeder.access_cmap_walk_id,
    feeder.access_cmap_walk_nta_score,
    feeder.access_cmap_walk_total_score,
    feeder.access_cmap_walk_data_year,
    feeder.misc_subdivision_id,
    feeder.misc_subdivision_data_year,
    {{ open_data_columns() }}
FROM {{ ref('default.vw_pin_universe') }} AS feeder
{{ open_data_rows_to_delete() }}
WHERE COALESCE(feeder.year, deleted_rows.year)
    = (SELECT MAX(year) FROM {{ ref('default.vw_pin_universe') }})
