-- Most-recent-year-only copy of defualt.vw_pin_universe. Feeds the "Parcel
-- Universe (Current Year)" open data asset.
-- Some columns from the feeder view may not be present in this view.

WITH deleted AS (
    SELECT
        CONCAT(parid, taxyr) AS row_id,
        TRUE AS ":deleted" -- noqa
    FROM {{ source('iasworld', 'pardat') }}
    WHERE
        deactivat IS NOT NULL
        OR class = '999'
),

feeder AS (
    SELECT
        pin,
        pin10,
        CAST(year AS INT) AS year,
        class,
        triad_name,
        triad_code,
        township_name,
        township_code,
        nbhd_code,
        tax_code,
        zip_code,
        lon,
        lat,
        x_3435,
        y_3435,
        census_block_group_geoid,
        census_block_geoid,
        census_congressional_district_geoid,
        census_congressional_district_num,
        census_county_subdivision_geoid,
        census_place_geoid,
        census_puma_geoid,
        census_school_district_elementary_geoid,
        census_school_district_secondary_geoid,
        census_school_district_unified_geoid,
        census_state_representative_geoid,
        census_state_representative_num,
        census_state_senate_geoid,
        census_state_senate_num,
        census_tract_geoid,
        census_zcta_geoid,
        census_data_year,
        census_acs5_congressional_district_geoid,
        census_acs5_congressional_district_num,
        census_acs5_county_subdivision_geoid,
        census_acs5_place_geoid,
        census_acs5_puma_geoid,
        census_acs5_school_district_elementary_geoid,
        census_acs5_school_district_secondary_geoid,
        census_acs5_school_district_unified_geoid,
        census_acs5_state_representative_geoid,
        census_acs5_state_representative_num,
        census_acs5_state_senate_geoid,
        census_acs5_state_senate_num,
        census_acs5_tract_geoid,
        census_acs5_data_year,
        cook_board_of_review_district_num,
        cook_board_of_review_district_data_year,
        cook_commissioner_district_num,
        cook_commissioner_district_data_year,
        cook_judicial_district_num,
        cook_judicial_district_data_year,
        ward_num,
        ward_chicago_data_year,
        ward_evanston_data_year,
        chicago_community_area_num,
        chicago_community_area_name,
        chicago_community_area_data_year,
        chicago_industrial_corridor_num,
        chicago_industrial_corridor_name,
        chicago_industrial_corridor_data_year,
        chicago_police_district_num,
        chicago_police_district_data_year,
        econ_coordinated_care_area_num,
        econ_coordinated_care_area_data_year,
        econ_enterprise_zone_num,
        econ_enterprise_zone_data_year,
        econ_industrial_growth_zone_num,
        econ_industrial_growth_zone_data_year,
        econ_qualified_opportunity_zone_num,
        econ_qualified_opportunity_zone_data_year,
        econ_central_business_district_num,
        econ_central_business_district_data_year,
        env_flood_fema_sfha,
        env_flood_fema_data_year,
        env_flood_fs_factor,
        env_flood_fs_risk_direction,
        env_flood_fs_data_year,
        env_ohare_noise_contour_no_buffer_bool,
        env_ohare_noise_contour_half_mile_buffer_bool,
        env_ohare_noise_contour_data_year,
        env_airport_noise_dnl,
        env_airport_noise_data_year,
        school_elementary_district_geoid,
        school_elementary_district_name,
        school_secondary_district_geoid,
        school_secondary_district_name,
        school_unified_district_geoid,
        school_unified_district_name,
        school_school_year,
        school_data_year,
        {{ array_join("tax_municipality_num") }},
        {{ array_join("tax_municipality_name") }},
        {{ array_join("tax_school_elementary_district_num") }},
        {{ array_join("tax_school_elementary_district_name") }},
        {{ array_join("tax_school_secondary_district_num") }},
        {{ array_join("tax_school_secondary_district_name") }},
        {{ array_join("tax_school_unified_district_num") }},
        {{ array_join("tax_school_unified_district_name") }},
        {{ array_join("tax_community_college_district_num") }},
        {{ array_join("tax_community_college_district_name") }},
        {{ array_join("tax_fire_protection_district_num") }},
        {{ array_join("tax_fire_protection_district_name") }},
        {{ array_join("tax_library_district_num") }},
        {{ array_join("tax_library_district_name") }},
        {{ array_join("tax_park_district_num") }},
        {{ array_join("tax_park_district_name") }},
        {{ array_join("tax_sanitation_district_num") }},
        {{ array_join("tax_sanitation_district_name") }},
        {{ array_join("tax_special_service_area_num") }},
        {{ array_join("tax_special_service_area_name") }},
        {{ array_join("tax_tif_district_num") }},
        {{ array_join("tax_tif_district_name") }},
        tax_data_year,
        access_cmap_walk_id,
        access_cmap_walk_nta_score,
        access_cmap_walk_total_score,
        access_cmap_walk_data_year,
        misc_subdivision_id,
        misc_subdivision_data_year
    FROM {{ ref('default.vw_pin_universe') }}
    WHERE year = (SELECT MAX(year) FROM {{ ref('default.vw_pin_universe') }})
)

SELECT
    COALESCE(CONCAT(feeder.pin, CAST(feeder.year AS VARCHAR)), deleted.row_id)
        AS row_id,
    feeder.*,
    deleted.":deleted" -- noqa
FROM feeder
FULL OUTER JOIN deleted
    ON
    CONCAT(feeder.pin, CAST(feeder.year AS VARCHAR)) = deleted.row_id
