sources:
  - name: model
    tables:
      - name: assessment_card
        tags:
          - load_auto

      - name: assessment_pin
        tags:
          - load_auto

      - name: feature_importance
        tags:
          - load_auto

      - name: final_model
        tags:
          - load_manual

      - name: metadata
        tags:
          - load_auto

      - name: parameter_final
        tags:
          - load_auto

      - name: parameter_range
        tags:
          - load_auto

      - name: parameter_search
        tags:
          - load_auto

      - name: performance
        tags:
          - load_auto

      - name: performance_quantile
        tags:
          - load_auto

      - name: shap
        tags:
          - load_auto

      - name: test_card
        tags:
          - load_auto

      - name: timing
        tags:
          - load_auto


models:
  - name: model.vw_card_res_input
    config:
      tags:
        - type_res

    columns:
      - name: char_bldg_sf_95_percentile
        description: |
          95th percentile of building square footage,
          by year and township
      - name: char_land_sf_95_percentile
        description: |
          95th percentile of land square footage,
          by year and township
      - name: ind_bldg_gte_95_percentile
        description: |
          Indicator for a PIN with building square footage larger
          than 95% of other properties for this year and township
      - name: ind_land_bldg_ratio_gte_10
        description: |
          Indicator for a PIN with a ratio of (land sqft / bldg sqft)
          of greater than or equal to 10.

          This is intended to identify small houses on very large lots
      - name: ind_land_gte_95_percentile
        description: |
          Indicator for a PIN with land square footage larger
          than 95% of other properties for this year and township
      - name: other_ihs_avg_year_index
        description: '{{ doc("shared_column_ihs_avg_year_index") }}'
      - name: other_school_district_elementary_avg_rating
        description: '{{ doc("shared_column_school_district_elementary_avg_rating") }}'
      - name: other_school_district_secondary_avg_rating
        description: '{{ doc("shared_column_school_district_secondary_avg_rating") }}'
      - name: other_tax_bill_rate
        description: '{{ doc("shared_column_tax_bill_rate") }}'

  - name: model.vw_pin_condo_input
    config:
      tags:
        - type_condo

  - name: model.vw_pin_shared_input
