version: 2


models:
  - name: model.assessment_card
  - name: model.assessment_pin
  - name: model.feature_importance
  - name: model.final_model
  - name: model.metadata
  - name: model.parameter_final
  - name: model.parameter_range
  - name: model.parameter_search
  - name: model.performance
  - name: model.performance_quantile
  - name: model.shap
  - name: model.test_card
  - name: model.timing
  - name: model.vw_card_res_input
  - name: model.vw_pin_condo_input
  - name: model.vw_pin_shared_input

