version: 2


sources:
  - name: iasworld
    loaded_at_field: date_parse(wen, '%Y-%m-%d %H:%i:%s.0')
    tables:
      - name: aasysjur
      - name: addn
      - name: addrindx
      - name: aprval
      - name: asmt_all
        freshness:
          filter: &latest_taxyr taxyr >= date_format(current_date - interval '1' year, '%Y')
          warn_after: &24_hours {count: 24, period: hour}
          error_after: &48_hours {count: 48, period: hour}
        tests:
          - unique_combination_of_columns:
              name: asmt_all_unique_by_parid_procname_and_taxyr
              combination_of_columns:
                - parid
                - procname
                - taxyr
              where: >-
                cur = 'Y' and
                deactivat is null and
                procname in ('CCAOVALUE', 'CCAOFINAL', 'BORVALUE')
              config:
                error_if: ">5991764"
      - name: asmt_hist
      - name: cname
      - name: comdat
      - name: comnt
      - name: cvleg
      - name: cvown
      - name: cvtran
      - name: dedit
      - name: dweldat
      - name: enter
      - name: exadmn
      - name: exapp
      - name: excode
      - name: exdet
      - name: htagnt
      - name: htdates
      - name: htpar
        freshness:
          filter: *latest_taxyr
          warn_after: *24_hours
          error_after: *48_hours
        tests:
          - unique_combination_of_columns:
              name: htpar_unique_by_parid_caseno_taxyr_subkey
              combination_of_columns:
                - parid
                - caseno
                - taxyr
                - subkey
              where: cur = 'Y' and deactivat is null
              config:
                error_if: ">2"
      - name: land
      - name: legdat
      - name: lpmod
      - name: lpnbhd
      - name: oby
      - name: owndat
      - name: pardat
      - name: permit
        freshness:
          filter: date_format(date_parse(permdt, '%Y-%m-%d %H:%i:%s.0'), '%Y') >= date_format(current_date - interval '1' year, '%Y')
          warn_after: *48_hours
          error_after: &72_hours {count: 72, period: hour}
      - name: rcoby
      - name: sales
        tests:
          - unique_combination_of_columns:
              name: sales_unique_by_parid_instruno
              combination_of_columns:
                - parid
                - instruno
              where: substr(saledt, 1, 4) >= '2023'
      - name: splcom
      - name: valclass
