version: 2


models:
  - name: iasworld.aasysjur
  - name: iasworld.addn
  - name: iasworld.addrindx
  - name: iasworld.aprval
  - name: iasworld.asmt_all
  - name: iasworld.asmt_hist
  - name: iasworld.cname
  - name: iasworld.comdat
  - name: iasworld.comnt
  - name: iasworld.cvleg
  - name: iasworld.cvown
  - name: iasworld.cvtran
  - name: iasworld.dedit
  - name: iasworld.dweldat
  - name: iasworld.enter
  - name: iasworld.exadmn
  - name: iasworld.exapp
  - name: iasworld.excode
  - name: iasworld.exdet
  - name: iasworld.htagnt
  - name: iasworld.htdates
  - name: iasworld.htpar
  - name: iasworld.land
  - name: iasworld.legdat
  - name: iasworld.lpmod
  - name: iasworld.lpnbhd
  - name: iasworld.oby
  - name: iasworld.owndat
  - name: iasworld.pardat
  - name: iasworld.permit
  - name: iasworld.rcoby
  - name: iasworld.sales
  - name: iasworld.splcom
  - name: iasworld.valclass
