
CREATE TABLE RPIE_PIN_CODES (RPIE_PIN varchar(14), TAX_YEAR int, RPIE_CODE varchar(13))


declare @AlLChars varchar(100) = 'ABCDEFGHJKLMNOPQRSTUVWXYZ23456789'
INSERT INTO RPIE_PIN_CODES 
 SELECT PIN,TAX_YEAR, 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' +
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1)
              AS RPIE_CODE
  FROM AS_HEADT

--check for duplicate codes
  SELECT RPIE_CODE, COUNT(RPIE_CODE) FROM RPIE_PIN_CODES 
  GROUP BY RPIE_CODE
  HAVING COUNT(RPIE_CODE) > 1
/* 1st run found
  TXV-972-ERG-X      2
94H-Y9R-CC9-3 2
98B-7G9-9QX-L 2
MLZ-7LD-7EC-S 2
  */


SELECT * FROM RPIE_PIN_CODES where RPIE_CODE IN ('TXV-972-ERG-X','94H-Y9R-CC9-3','98B-7G9-9QX-L','MLZ-7LD-7EC-S')

  declare @AlLChars varchar(100) = 'ABCDEFGHJKLMNOPQRSTUVWXYZ23456789'

  UPDATE RPIE_PIN_CODES SET RPIE_CODE =
  RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' +
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + 
       RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1) + '-' + RIGHT( LEFT(@AlLChars,ABS(BINARY_CHECKSUM(NEWID())%35) + 1 ),1)
              WHERE RPIE_CODE IN ('TXV-972-ERG-X','94H-Y9R-CC9-3','98B-7G9-9QX-L','MLZ-7LD-7EC-S')
              
              -- check again
              SELECT RPIE_CODE, COUNT(RPIE_CODE) FROM RPIE_PIN_CODES 
  GROUP BY RPIE_CODE
  HAVING COUNT(RPIE_CODE) > 1

  --ok
/* This view is used for RPIE notifications. Each PIN number is paired with a unique, random string of letters and numbers. 
Mailing and property addresses are also brought in */

