[tool.ruff]
line-length = 79

[tool.sqlfluff.core]
dialect = "athena"
exclude_rules = "ambiguous.column_count, structure.column_order, RF04, ST05"
large_file_skip_byte_limit = 0
processes = -1

[tool.sqlfluff.indentation]
indent_unit = "space"
tab_space_size = 4
indented_joins = false
indented_using_on = true
indented_on_contents = false
indented_ctes = false
indented_then = true
indented_then_contents = false
allow_implicit_indents = true

[tool.sqlfluff.rules.aliasing.table]
aliasing = "explicit"
[tool.sqlfluff.rules.aliasing.column]
aliasing = "explicit"
[tool.sqlfluff.rules.aliasing.length]
min_alias_length = 2

[tool.sqlfluff.rules.capitalisation.keywords]
capitalisation_policy = "upper"
[tool.sqlfluff.rules.capitalisation.identifiers]
capitalisation_policy = "upper"
[tool.sqlfluff.rules.capitalisation.functions]
extended_capitalisation_policy = "upper"
[tool.sqlfluff.rules.capitalisation.literals]
capitalisation_policy = "upper"
[tool.sqlfluff.rules.capitalisation.types]
extended_capitalisation_policy = "upper"

[tool.sqlfluff.rules.convention.casting_style]
preferred_type_casting_style = "cast"

[tool.sqlfluff.templater.jinja]
load_macros_from_path = "dbt/macros"

[tool.sqlfluff.templater.jinja.macros]
# It appears that some common dbt variables like `target` and `exceptions` do
# not have sqlfluff mocks builtin, so we have to mock out any macros
# that reference those variables if they are used in code that sqlfluff
# lints
get_s3_dependency_dir = "{% macro get_s3_dependency_dir() %}s3://bucket{% endmacro %}"
