sources:
  - name: ccao
    tags:
      - load_manual
    tables:
      - name: class_dict
      - name: commercial_valuation
      - name: hie
        tags:
          - type_res
      - name: land_nbhd_rate
      - name: land_site_rate
      - name: pin_condo_char
        tags:
          - type_condo
      - name: pin_nonlivable
        tags:
          - type_condo
      - name: pin_weird
