version: 2


models:
  - name: ccao.class_dict
  - name: ccao.commercial_valuation
  - name: ccao.hie
  - name: ccao.land_nbhd_rate
  - name: ccao.land_site_rate
  - name: ccao.pin_399_garage_units
  - name: ccao.pin_condo_char
  - name: ccao.pin_questionable_garage_units
  - name: ccao.pin_weird
