models:
  - name: ccao.vw_time_util
    description: '{{ doc("view_vw_time_util") }}'

sources:
  - name: ccao
    tags:
      - load_manual
    tables:
      - name: commercial_valuation
        description: '{{ doc("table_commercial_valuation") }}'
        tags:
          - type_ic

      - name: cc_dli_senfrr
        description: '{{ doc("table_cc_dli_senfrr") }}'

      - name: cc_pifdb_piexemptre_dise
        description: '{{ doc("table_cc_pifdb_piexemptre_dise") }}'

      - name: cc_pifdb_piexemptre_ownr
        description: '{{ doc("table_cc_pifdb_piexemptre_ownr") }}'

      - name: cc_pifdb_piexemptre_sted
        description: '{{ doc("table_cc_pifdb_piexemptre_sted") }}'

      - name: hie
        description: '{{ doc("table_hie") }}'
        tags:
          - type_res

      - name: land_nbhd_rate
        description: '{{ doc("table_land_nbhd_rate") }}'
        tags:
          - type_land
        data_tests:
        - unique_combination_of_columns:
            name: ccao_land_nbhd_rate_unique_by_town_nbhd_class_and_year
            combination_of_columns:
              - town_nbhd
              - class
              - year
            meta:
              description: ccao land nbhd rate should be unique by town_nbhd, class, and year

      - name: land_site_rate
        description: '{{ doc("table_land_site_rate") }}'
        tags:
          - type_land

      - name: pin_condo_char
        description: '{{ doc("table_pin_condo_char") }}'
        tags:
          - type_condo
        data_tests:
        - unique_combination_of_columns:
            name: ccao_pin_condo_char_unique_by_pin_and_year
            combination_of_columns:
              - pin
              - year
            config:
              error_if: ">1"
            meta:
              description: ccao pin condo char should be unique by pin and year
        columns:
          - name: bedrooms
            description: '{{ doc("shared_column_char_beds") }}'
          - name: building_sf
            description: '{{ doc("shared_column_char_building_sf") }}'
          - name: full_baths
            description: '{{ doc("shared_column_char_fbath") }}'
          - name: half_baths
            description: '{{ doc("shared_column_char_hbath") }}'
          - name: parking_pin
            description: |
              Deeded parking/garage space or storage unit.

              Detected either by valuations, CDU, or unit
              number/proration rate heuristics.
          - name: pin
            description: '{{ doc("shared_column_pin") }}'
          - name: unit_sf
            description: '{{ doc("shared_column_char_unit_sf") }}'
          - name: year
            description: '{{ doc("shared_column_year") }}'

      - name: pin_nonlivable
        description: '{{ doc("table_pin_nonlivable") }}'
        tags:
          - type_condo
        data_tests:
          - unique_combination_of_columns:
              name: ccao_pin_nonlivable_unique_by_pin_and_year
              combination_of_columns:
                - pin
                - year
              meta: 
                description: pin nonlivable should be unique by pin and year
        columns:
          - name: flag
            data_tests:
              - accepted_values:
                  name: ccao_pin_nonlivable_flag_accepted_values
                  values: ["questionable", "negative pred", "399 GR"]
            meta:
              description: pin nonlivable flag should have values of questionable, negative pre or 399 GR

exposures:
  - name: commercial_valuation_data
    label: Commercial Valuation Data
    type: dashboard
    url: https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Commercial-Valuation-Data/csik-bsws
    depends_on:
      - source('ccao', 'commercial_valuation')
    owner:
      name: Data Department
    description: |
      Commercial valuation data collected and maintained by the Cook County Assessor's Office, from 2021 to present.

      Notes: Refreshed annually, as data is made available by the commercial team.

      Use cases: Can be used to look up the number of units in a multi-unit apartment building.
