name: Setup dbt
description: Install dependencies for dbt and configure it for use in CI.
inputs:
  role-to-assume:
    description: AWS IAM role to assume when running dbt operations.
    required: true
  role-duration-seconds:
    description: Expiration time for AWS OIDC token. Default is one hour.
    required: false
    default: 3600
runs:
  using: composite
  steps:
    - name: Install dbt requirements
      uses: ./.github/actions/install_dbt_requirements

    - name: Load environment variables
      uses: ./.github/actions/load_environment_variables

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: us-east-1
        role-duration-seconds: ${{ inputs.role-duration-seconds }}

    - name: Configure dbt environment
      uses: ./.github/actions/configure_dbt_environment
