name: Setup dbt
description: Install dependencies for dbt and configure it for use in CI.
inputs:
  role-to-assume:
    description: AWS IAM role to assume when running dbt operations.
    required: true
runs:
  using: composite
  steps:
    - name: Install dbt requirements
      uses: ./.github/actions/install_dbt_requirements

    - name: Load environment variables
      uses: ./.github/actions/load_environment_variables

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: us-east-1

    - name: Configure dbt environment
      uses: ./.github/actions/configure_dbt_environment
