sources:
  - name: census
    tags:
      - load_manual
    tables:
      - name: acs1
      - name: acs5
      - name: decennial
      - name: table_dict
      - name: variable_dict

models:
  - name: census.vw_acs5_stat
    columns:
      - name: count_age_children
        description: '{{ doc("column_count_age_children") }}'
      - name: count_age_senior
        description: '{{ doc("column_count_age_senior") }}'
      - name: count_education_associate
        description: '{{ doc("column_count_education_associate") }}'
      - name: count_education_bachelor
        description: '{{ doc("column_count_education_bachelor") }}'
      - name: count_education_graduate
        description: '{{ doc("column_count_education_graduate") }}'
      - name: count_education_high_school
        description: '{{ doc("column_count_education_high_school") }}'
      - name: count_education_total
        description: '{{ doc("column_count_education_total") }}'
      - name: count_employment_in_civilian_labor_force
        description: '{{ doc("column_count_employment_in_civilian_labor_force") }}'
      - name: count_employment_not_in_labor_force
        description: '{{ doc("column_count_employment_not_in_labor_force") }}'
      - name: count_employment_unemployed
        description: '{{ doc("column_count_employment_unemployed") }}'
      - name: count_household_family_married
        description: '{{ doc("column_count_household_family_married") }}'
      - name: count_household_family_other
        description: '{{ doc("column_count_household_family_other") }}'
      - name: count_household_family_total
        description: '{{ doc("column_count_household_family_total") }}'
      - name: count_household_nonfamily_alone
        description: '{{ doc("column_count_household_nonfamily_alone") }}'
      - name: count_household_nonfamily_not_alone
        description: '{{ doc("column_count_household_nonfamily_not_alone") }}'
      - name: count_household_owner_occupied
        description: '{{ doc("column_count_household_owner_occupied") }}'
      - name: count_household_owner_occupied_1_sel_cond
        description: '{{ doc("column_count_household_owner_occupied_w_sel_cond") }}'
      - name: count_household_owner_occupied_2_sel_cond
        description: '{{ doc("column_count_household_owner_occupied_w_sel_cond") }}'
      - name: count_household_owner_occupied_3_sel_cond
        description: '{{ doc("column_count_household_owner_occupied_w_sel_cond") }}'
      - name: count_household_owner_occupied_4_sel_cond
        description: '{{ doc("column_count_household_owner_occupied_w_sel_cond") }}'
      - name: count_household_renter_occupied
        description: '{{ doc("column_count_household_renter_occupied") }}'
      - name: count_household_renter_occupied_1_sel_cond
        description: '{{ doc("column_count_household_renter_occupied_w_sel_cond") }}'
      - name: count_household_renter_occupied_2_sel_cond
        description: '{{ doc("column_count_household_renter_occupied_w_sel_cond") }}'
      - name: count_household_renter_occupied_3_sel_cond
        description: '{{ doc("column_count_household_renter_occupied_w_sel_cond") }}'
      - name: count_household_renter_occupied_4_sel_cond
        description: '{{ doc("column_count_household_renter_occupied_w_sel_cond") }}'
      - name: count_household_total
        description: '{{ doc("column_count_household_total") }}'
      - name: count_household_total_occupied
        description: '{{ doc("column_count_household_total_occupied") }}'
      - name: count_income_above_poverty_level
        description: '{{ doc("column_count_income_above_poverty_level") }}'
      - name: count_income_below_poverty_level
        description: '{{ doc("column_count_income_below_poverty_level") }}'
      - name: count_income_household_received_snap_past_year
        description: '{{ doc("column_count_income_household_received_snap_past_year") }}'
      - name: count_income_total_poverty_level
        description: '{{ doc("column_count_income_total_poverty_level") }}'
      - name: count_mobility_moved_from_abroad
        description: '{{ doc("column_count_mobility_moved_from_abroad") }}'
      - name: count_mobility_moved_from_other_state
        description: '{{ doc("column_count_mobility_moved_from_other_state") }}'
      - name: count_mobility_moved_in_county
        description: '{{ doc("column_count_mobility_moved_in_county") }}'
      - name: count_mobility_moved_in_state
        description: '{{ doc("column_count_mobility_moved_in_state") }}'
      - name: count_mobility_no_move
        description: '{{ doc("column_count_mobility_no_move") }}'
      - name: count_mobility_total
        description: '{{ doc("column_count_mobility_total") }}'
      - name: count_race_aian
        description: '{{ doc("column_count_race_aian") }}'
      - name: count_race_asian
        description: '{{ doc("column_count_race_asian") }}'
      - name: count_race_black
        description: '{{ doc("column_count_race_black") }}'
      - name: count_race_hisp
        description: '{{ doc("column_count_race_hisp") }}'
      - name: count_race_nhpi
        description: '{{ doc("column_count_race_nhpi") }}'
      - name: count_race_other
        description: '{{ doc("column_count_race_other") }}'
      - name: count_race_total
        description: '{{ doc("column_count_race_total") }}'
      - name: count_race_white
        description: '{{ doc("column_count_race_white") }}'
      - name: count_sex_female
        description: '{{ doc("column_count_sex_female") }}'
      - name: count_sex_male
        description: '{{ doc("column_count_sex_male") }}'
      - name: count_sex_total
        description: '{{ doc("column_count_sex_total") }}'
      - name: geography
        description: '{{ doc("column_geography") }}'
      - name: geoid
        description: '{{ doc("column_geoid") }}'
      - name: geography
        description: '{{ doc("shared_column_geography") }}'
      - name: median_age_female
        description: '{{ doc("column_median_age_female") }}'
      - name: median_age_male
        description: '{{ doc("column_median_age_male") }}'
      - name: median_age_total
        description: '{{ doc("column_median_age_total") }}'
      - name: median_household_owner_occupied_value
        description: '{{ doc("column_median_household_owner_occupied_value") }}'
      - name: median_household_owner_occupied_year_built
        description: '{{ doc("column_median_household_owner_occupied_year_built") }}'
      - name: median_household_renter_occupied_gross_rent
        description: '{{ doc("column_median_household_renter_occupied_gross_rent") }}'
      - name: median_household_renter_occupied_year_built
        description: '{{ doc("column_median_household_renter_occupied_year_built") }}'
      - name: median_household_total_occupied_year_built
        description: '{{ doc("column_median_household_total_occupied_year_built") }}'
      - name: median_income_household_past_year
        description: '{{ doc("column_median_income_household_past_year") }}'
      - name: median_income_per_capita_past_year
        description: '{{ doc("column_median_income_per_capita_past_year") }}'
      - name: percent_age_children
        description: '{{ doc("column_percent_age_children") }}'
      - name: percent_age_senior
        description: '{{ doc("column_percent_age_senior") }}'
      - name: percent_education_associate
        description: '{{ doc("column_percent_education_associate") }}'
      - name: percent_education_bachelor
        description: '{{ doc("column_percent_education_bachelor") }}'
      - name: percent_education_graduate
        description: '{{ doc("column_percent_education_graduate") }}'
      - name: percent_education_high_school
        description: '{{ doc("column_percent_education_high_school") }}'
      - name: percent_employment_unemployed
        description: '{{ doc("column_percent_employment_unemployed") }}'
      - name: percent_household_family_married
        description: '{{ doc("column_percent_household_family_married") }}'
      - name: percent_household_nonfamily_alone
        description: '{{ doc("column_percent_household_nonfamily_alone") }}'
      - name: percent_household_nonfamily_not_alone
        description: '{{ doc("column_percent_household_nonfamily_not_alone") }}'
      - name: percent_household_owner_occupied
        description: '{{ doc("column_percent_household_owner_occupied") }}'
      - name: percent_household_owner_occupied_w_sel_cond
        description: '{{ doc("column_percent_household_owner_occupied_w_sel_cond") }}'
      - name: percent_household_renter_occupied
        description: '{{ doc("column_percent_household_renter_occupied") }}'
      - name: percent_household_renter_occupied_w_sel_cond
        description: '{{ doc("column_percent_household_renter_occupied_w_sel_cond") }}'
      - name: percent_household_total_occupied_w_sel_cond
        description: '{{ doc("column_percent_household_total_occupied_w_sel_cond") }}'
      - name: percent_income_above_poverty_level
        description: '{{ doc("column_percent_income_above_poverty_level") }}'
      - name: percent_income_below_poverty_level
        description: '{{ doc("column_percent_income_below_poverty_level") }}'
      - name: percent_income_household_received_snap_past_year
        description: '{{ doc("column_percent_income_household_received_snap_past_year") }}'
      - name: percent_mobility_moved_from_abroad
        description: '{{ doc("column_percent_mobility_moved_from_abroad") }}'
      - name: percent_mobility_moved_from_other_state
        description: '{{ doc("column_percent_mobility_moved_from_other_state") }}'
      - name: percent_mobility_moved_in_county
        description: '{{ doc("column_percent_mobility_moved_in_county") }}'
      - name: percent_mobility_moved_in_state
        description: '{{ doc("column_percent_mobility_moved_in_state") }}'
      - name: percent_mobility_no_move
        description: '{{ doc("column_percent_mobility_no_move") }}'
      - name: percent_race_aian
        description: '{{ doc("column_percent_race_aian") }}'
      - name: percent_race_asian
        description: '{{ doc("column_percent_race_asian") }}'
      - name: percent_race_black
        description: '{{ doc("column_percent_race_black") }}'
      - name: percent_race_hisp
        description: '{{ doc("column_percent_race_hisp") }}'
      - name: percent_race_nhpi
        description: '{{ doc("column_percent_race_nhpi") }}'
      - name: percent_race_other
        description: '{{ doc("column_percent_race_other") }}'
      - name: percent_race_white
        description: '{{ doc("column_percent_race_white") }}'
      - name: percent_sex_female
        description: '{{ doc("column_percent_sex_female") }}'
      - name: percent_sex_male
        description: '{{ doc("column_percent_sex_male") }}'
      - name: year
        description: '{{ doc("shared_column_year") }}'
