name: Publish SNS topic
description: |
  Publish a notification to an AWS SNS topic. Requires that AWS authentication
  already be configured.
inputs:
  sns_topic_arn:
    description: ARN of the SNS topic to publish to.
    required: true
  subject:
    description: Subject for the SNS notification.
    required: true
  body:
    description: Text body for the SNS notification.
    required: true
runs:
  using: composite
  steps:
    - name: Publish SNS topic
      run: ./${{ github.action_path }}/publish.sh \
          "${{ inputs.sns_topic_arn }}" \
          "${{ inputs.subject }}" \
          "${{ inputs.body }}"
      shell: bash
