-- Return all model predictors for all years to use in populating a SELECT
-- query, with an optional tablename indicating the table that the predictor
-- columns should be selected from.
--
-- This macro is currently only used by PINVAL views, so it only includes
-- predictors for PINVAL-eligible years.
--
-- We do have to add predictors to this list manually whenever we add them to
-- the model, but we have a data integrity test on PINVAL views that should
-- alert us if we ever fall out of sync with the model.
--
-- Never remove predictors from this list, only add them. Outdated
-- predictors are most likely necessary to support reports for prior
-- assessment years.
{% macro all_predictors(tablename=None) %}
    {%- set prefix = tablename + "." if tablename else "" -%}
    {{ prefix }}meta_nbhd_code,
    {{ prefix }}meta_sale_count_past_n_years,
    {{ prefix }}char_yrblt,
    {{ prefix }}char_air,
    {{ prefix }}char_apts,
    {{ prefix }}char_attic_fnsh,
    {{ prefix }}char_attic_type,
    {{ prefix }}char_beds,
    {{ prefix }}char_bldg_sf,
    {{ prefix }}char_bsmt,
    {{ prefix }}char_bsmt_fin,
    {{ prefix }}char_ext_wall,
    {{ prefix }}char_fbath,
    {{ prefix }}char_frpl,
    {{ prefix }}char_gar1_att,
    {{ prefix }}char_gar1_cnst,
    {{ prefix }}char_gar1_size,
    {{ prefix }}char_hbath,
    {{ prefix }}char_land_sf,
    {{ prefix }}char_heat,
    {{ prefix }}char_ncu,
    {{ prefix }}char_porch,
    {{ prefix }}char_roof_cnst,
    {{ prefix }}char_rooms,
    {{ prefix }}char_tp_dsgn,
    {{ prefix }}char_type_resd,
    {{ prefix }}char_recent_renovation,
    {{ prefix }}loc_longitude,
    {{ prefix }}loc_latitude,
    {{ prefix }}loc_census_tract_geoid,
    {{ prefix }}loc_env_flood_fs_factor,
    {{ prefix }}loc_env_airport_noise_dnl,
    {{ prefix }}loc_school_elementary_district_geoid,
    {{ prefix }}loc_school_secondary_district_geoid,
    {{ prefix }}loc_access_cmap_walk_nta_score,
    {{ prefix }}loc_access_cmap_walk_total_score,
    {{ prefix }}loc_tax_municipality_name,
    {{ prefix }}prox_num_pin_in_half_mile,
    {{ prefix }}prox_num_bus_stop_in_half_mile,
    {{ prefix }}prox_num_foreclosure_per_1000_pin_past_5_years,
    {{ prefix }}prox_num_school_in_half_mile,
    {{ prefix }}prox_num_school_with_rating_in_half_mile,
    {{ prefix }}prox_avg_school_rating_in_half_mile,
    {{ prefix }}prox_airport_dnl_total,
    {{ prefix }}prox_nearest_bike_trail_dist_ft,
    {{ prefix }}prox_nearest_cemetery_dist_ft,
    {{ prefix }}prox_nearest_cta_route_dist_ft,
    {{ prefix }}prox_nearest_cta_stop_dist_ft,
    {{ prefix }}prox_nearest_hospital_dist_ft,
    {{ prefix }}prox_lake_michigan_dist_ft,
    {{ prefix }}prox_nearest_major_road_dist_ft,
    {{ prefix }}prox_nearest_metra_route_dist_ft,
    {{ prefix }}prox_nearest_metra_stop_dist_ft,
    {{ prefix }}prox_nearest_park_dist_ft,
    {{ prefix }}prox_nearest_railroad_dist_ft,
    {{ prefix }}prox_nearest_secondary_road_dist_ft,
    {{ prefix }}prox_nearest_university_dist_ft,
    {{ prefix }}prox_nearest_vacant_land_dist_ft,
    {{ prefix }}prox_nearest_water_dist_ft,
    {{ prefix }}prox_nearest_golf_course_dist_ft,
    {{ prefix }}prox_nearest_road_highway_dist_ft,
    {{ prefix }}prox_nearest_road_arterial_dist_ft,
    {{ prefix }}prox_nearest_road_collector_dist_ft,
    {{ prefix }}prox_nearest_road_arterial_daily_traffic,
    {{ prefix }}prox_nearest_road_collector_daily_traffic,
    {{ prefix }}prox_nearest_new_construction_dist_ft,
    {{ prefix }}prox_nearest_stadium_dist_ft,
    {{ prefix }}acs5_percent_age_children,
    {{ prefix }}acs5_percent_age_senior,
    {{ prefix }}acs5_median_age_total,
    {{ prefix }}acs5_percent_mobility_no_move,
    {{ prefix }}acs5_percent_mobility_moved_from_other_state,
    {{ prefix }}acs5_percent_household_family_married,
    {{ prefix }}acs5_percent_household_nonfamily_alone,
    {{ prefix }}acs5_percent_education_high_school,
    {{ prefix }}acs5_percent_education_bachelor,
    {{ prefix }}acs5_percent_education_graduate,
    {{ prefix }}acs5_percent_income_below_poverty_level,
    {{ prefix }}acs5_median_income_household_past_year,
    {{ prefix }}acs5_median_income_per_capita_past_year,
    {{ prefix }}acs5_percent_income_household_received_snap_past_year,
    {{ prefix }}acs5_percent_employment_unemployed,
    {{ prefix }}acs5_median_household_total_occupied_year_built,
    {{ prefix }}acs5_median_household_renter_occupied_gross_rent,
    {{ prefix }}acs5_percent_household_owner_occupied,
    {{ prefix }}acs5_percent_household_total_occupied_w_sel_cond,
    {{ prefix }}acs5_percent_mobility_moved_in_county,
    {{ prefix }}other_tax_bill_rate,
    {{ prefix }}other_school_district_elementary_avg_rating,
    {{ prefix }}other_school_district_secondary_avg_rating,
    {{ prefix }}ccao_is_active_exe_homeowner,
    {{ prefix }}ccao_is_corner_lot,
    {{ prefix }}ccao_n_years_exe_homeowner,
    {{ prefix }}time_sale_year,
    {{ prefix }}time_sale_day,
    {{ prefix }}time_sale_quarter_of_year,
    {{ prefix }}time_sale_month_of_year,
    {{ prefix }}time_sale_day_of_year,
    {{ prefix }}time_sale_day_of_month,
    {{ prefix }}time_sale_day_of_week,
    {{ prefix }}time_sale_post_covid,
    {{ prefix }}shp_parcel_centroid_dist_ft_sd,
    {{ prefix }}shp_parcel_edge_len_ft_sd,
    {{ prefix }}shp_parcel_interior_angle_sd,
    {{ prefix }}shp_parcel_mrr_area_ratio,
    {{ prefix }}shp_parcel_mrr_side_ratio,
    {{ prefix }}shp_parcel_num_vertices
{% endmacro %}
