name: Install dbt dependencies
description: Installs Python and dbt requirements for a workflow
inputs:
  dbt_project_dir:
    description: Path to the directory containing the dbt project.
    required: false
    default: ./dbt
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true
        cache-dependency-glob: |
          ${{ inputs.dbt_project_dir }}/pyproject.toml
          ${{ inputs.dbt_project_dir }}/uv.lock

    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version-file: ${{ inputs.dbt_project_dir }}/.python-version

    - name: Install Python dependencies
      working-directory: ${{ inputs.dbt_project_dir }}
      shell: bash
      run: uv sync --frozen

    - name: Cache dbt requirements
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ${{ inputs.dbt_project_dir }}/dbt_packages
        key: dbt-${{ hashFiles(format('{0}/packages.yml', inputs.dbt_project_dir)) }}

    - name: Install dbt requirements
      working-directory: ${{ inputs.dbt_project_dir }}
      shell: bash
      run: uv run --frozen dbt deps
