name: Install dbt dependencies
description: Installs Python and dbt requirements for a workflow
inputs:
  dbt_project_dir:
    description: Path to the directory containing the dbt project.
    required: false
    default: ./dbt
runs:
  using: composite
  steps:
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip

      - name: Install python requirements
        working-directory: dbt
        shell: bash
        run: python -m pip install .

      - name: Cache dbt requirements
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dbt_project_dir }}/dbt_packages
          key: dbt-${{ hashFiles(format('{0}/packages.yml', inputs.dbt_project_dir)) }}

      - name: Install dbt requirements
        run: dbt deps
        working-directory: ${{ inputs.dbt_project_dir }}
        shell: bash
