name: Install dbt dependencies
description: Installs Python and dbt requirements for a workflow
inputs:
  dbt_project_dir:
    description: Path to the directory containing the dbt project.
    required: false
    default: ./dbt
runs:
  using: composite
  steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: |
            ${{ inputs.dbt_project_dir }}/pyproject.toml
            ${{ inputs.dbt_project_dir }}/uv.lock

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ inputs.dbt_project_dir }}/.python-version

      - name: Install Python dependencies
        working-directory: ${{ inputs.dbt_project_dir }}
        shell: bash
        run: uv pip install .
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Cache dbt requirements
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dbt_project_dir }}/dbt_packages
          key: dbt-${{ hashFiles(format('{0}/packages.yml', inputs.dbt_project_dir)) }}

      - name: Install dbt requirements
        working-directory: ${{ inputs.dbt_project_dir }}
        shell: bash
        run: dbt deps
