seeds:
  - name: pinval.vars_dict
    description: '{{ doc("seed_vars_dict") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_vars_dict_unique_by_code
          combination_of_columns:
            - code
  - name: pinval.model_run
    description: '{{ doc("seed_model_run") }}'
