seeds:
  - name: pinval.vars_dict
    description: '{{ doc("seed_vars_dict") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_vars_dict_unique_by_code
          combination_of_columns:
            - code
  - name: pinval.model_run
    description: '{{ doc("seed_model_run") }}'
    columns:
      - name: assessment_year
        description: '{{ doc("shared_column_year") }}'
      - name: run_id
        description: '{{ doc("shared_column_run_id") }}'
        data_tests:
          # Test to make sure that all model runs in this seed are present in the
          # downstream models that depend on this seed
          - relationships:
              name: pinval_model_run_card_run_id_in_pinval_assessment_card
              to: ref('pinval.assessment_card')
              field: run_id
              config:
                where: type = 'card'
          - relationships:
              name: pinval_model_run_comp_run_id_in_pinval_comp
              to: ref('pinval.comp')
              field: run_id
              config:
                where: type = 'comp'
          - relationships:
              name: pinval_model_run_shap_run_id_in_pinval_assessment_card
              to: ref('pinval.assessment_card')
              field: shap_run_id
              config:
                where: type = 'shap'
      - name: type
        description: Model run type, must be one of 'card', 'comp' or 'shap'
        data_tests:
          # These two tests ensure that for each assessment year,
          # there is at least one of each type: card, shap, and comp,
          # and we limit the type column to accept only those three values
          - count_is_consistent:
              name: pinval_model_run_has_all_required_types_per_year
              group_column: assessment_year
              min_value: 3
              max_value: 3
          - accepted_values:
              name: pinval_model_run_type_accepted_values
              values:
                - card
                - shap
                - comp
    data_tests:
      - unique_combination_of_columns:
          name: pinval_model_run_unique_by_assessment_year_type_and_run_id
          combination_of_columns:
            - assessment_year
            - type
            - run_id
    config:
      column_types:
        assessment_year: varchar
