seeds:
  - name: pinval.vars_dict
    description: '{{ doc("seed_vars_dict") }}'
    data_tests:
      - unique_combination_of_columns:
          name: pinval_vars_dict_unique_by_code
          combination_of_columns:
            - code
  - name: pinval.model_run
    description: '{{ doc("seed_model_run") }}'
    data_tests:
      - accepted_values:
          name: model_run_type_accepted_values
          column_name: type
          values:
            - card
            - shap
            - comps
    config:
      column_types:
        assessment_year: varchar
