models:
  - name: proximity.cnt_pin_num_bus_stop
  - name: proximity.cnt_pin_num_foreclosure
  - name: proximity.cnt_pin_num_school
  - name: proximity.crosswalk_year_fill
  - name: proximity.dist_pin_to_bike_trail
  - name: proximity.dist_pin_to_cemetery
  - name: proximity.dist_pin_to_cta_route
  - name: proximity.dist_pin_to_cta_stop
  - name: proximity.dist_pin_to_golf_course
  - name: proximity.dist_pin_to_hospital
  - name: proximity.dist_pin_to_lake_michigan
  - name: proximity.dist_pin_to_major_road
  - name: proximity.dist_pin_to_metra_route
  - name: proximity.dist_pin_to_metra_stop
  - name: proximity.dist_pin_to_park
  - name: proximity.dist_pin_to_pin
    description: '{{ doc("dist_pin_to_pin") }}'
  - name: proximity.dist_pin_to_pin_1km
    description: '{{ doc("dist_pin_to_pin_intermediate") }}'
  - name: proximity.dist_pin_to_pin_10km
    description: '{{ doc("dist_pin_to_pin_intermediate") }}'
  - name: proximity.dist_pin_to_railroad
  - name: proximity.dist_pin_to_water
  - name: proximity.vw_pin10_proximity
  - name: proximity.vw_pin10_proximity_fill

exposures:
  - name: parcel_proximity
    label: Parcel Proximity
    type: dashboard
    url: https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Parcel-Proximity/ydue-e5u3
    depends_on:
      - ref('proximity.vw_pin10_proximity')
    owner:
      name: Data Department
    meta:
      test_row_count: true
    description: |
      Cook County 10-digit parcels with attached distances to various spatial features.

      Notes: Refreshed monthly, data is updated yearly as spatial files are made available.

      Use cases: Can be used to isolate parcels by distance to specific spatial features.
