version: 2


models:
  - name: cnt_pin_num_bus_stop
  - name: cnt_pin_num_foreclosure
  - name: cnt_pin_num_school
  - name: crosswalk_year_fill
  - name: dist_pin_to_bike_trail
  - name: dist_pin_to_cemetery
  - name: dist_pin_to_cta_route
  - name: dist_pin_to_cta_stop
  - name: dist_pin_to_golf_course
  - name: dist_pin_to_hospital
  - name: dist_pin_to_lake_michigan
  - name: dist_pin_to_major_road
  - name: dist_pin_to_metra_route
  - name: dist_pin_to_metra_stop
  - name: dist_pin_to_park
  - name: dist_pin_to_pin
  - name: dist_pin_to_railroad
  - name: dist_pin_to_water
  - name: vw_pin10_proximity
  - name: vw_pin10_proximity_fill
