models:
  - name: proximity.cnt_pin_num_bus_stop
    description: '{{ doc("table_cnt_pin_num_bus_stop") }}'

  - name: proximity.cnt_pin_num_foreclosure
    description: '{{ doc("table_cnt_pin_num_foreclosure") }}'

  - name: proximity.cnt_pin_num_school
    description: '{{ doc("table_cnt_pin_num_school") }}'

  - name: proximity.crosswalk_year_fill
    description: '{{ doc("table_crosswalk_year_fill") }}'

  - name: proximity.dist_pin_to_airport
    description: '{{ doc("table_dist_pin_to_airport") }}'

  - name: proximity.dist_pin_to_bike_trail
    description: '{{ doc("table_dist_pin_to_bike_trail") }}'

  - name: proximity.dist_pin_to_cemetery
    description: '{{ doc("table_dist_pin_to_cemetery") }}'

  - name: proximity.dist_pin_to_cta_route
    description: '{{ doc("table_dist_pin_to_cta_route") }}'

  - name: proximity.dist_pin_to_cta_stop
    description: '{{ doc("table_dist_pin_to_cta_stop") }}'

  - name: proximity.dist_pin_to_golf_course
    description: '{{ doc("table_dist_pin_to_golf_course") }}'

  - name: proximity.dist_pin_to_hospital
    description: '{{ doc("table_dist_pin_to_hospital") }}'

  - name: proximity.dist_pin_to_lake_michigan
    description: '{{ doc("table_dist_pin_to_lake_michigan") }}'

  - name: proximity.dist_pin_to_major_road
    description: '{{ doc("table_dist_pin_to_major_road") }}'

  - name: proximity.dist_pin_to_metra_route
    description: '{{ doc("table_dist_pin_to_metra_route") }}'

  - name: proximity.dist_pin_to_metra_stop
    description: '{{ doc("table_dist_pin_to_metra_stop") }}'

  - name: proximity.dist_pin_to_park
    description: '{{ doc("table_dist_pin_to_park") }}'

  - name: proximity.dist_pin_to_pin
    description: '{{ doc("view_dist_pin_to_pin") }}'
    data_tests:
      - unique_combination_of_columns:
          name: proximity_dist_pin_to_pin_unique_by_10_digit_pin_and_year
          combination_of_columns:
            - pin10
            - year

  - name: proximity.dist_pin_to_pin_01
    description: '{{ doc("table_dist_pin_to_pin_intermediate") }}'

  - name: proximity.dist_pin_to_pin_02
    description: '{{ doc("table_dist_pin_to_pin_intermediate") }}'

  - name: proximity.dist_pin_to_pin_03
    description: '{{ doc("table_dist_pin_to_pin_intermediate") }}'

  - name: proximity.dist_pin_to_railroad
    description: '{{ doc("table_dist_pin_to_railroad") }}'

  - name: proximity.dist_pin_to_secondary_road
    description: '{{ doc("table_dist_pin_to_secondary_road") }}'

  - name: proximity.dist_pin_to_university
    description: '{{ doc("table_dist_pin_to_university") }}'

  - name: proximity.dist_pin_to_vacant_land
    description: '{{ doc("table_dist_pin_to_vacant_land") }}'

  - name: proximity.dist_pin_to_water
    description: '{{ doc("table_dist_pin_to_water") }}'

  - name: proximity.vw_pin10_proximity
    description: '{{ doc("view_vw_pin10_proximity") }}'
    columns: &vw_proximity_columns
      - name: airport_dnl_total
        description: '{{ doc("column_airport_dnl_total") }}'
      - name: avg_school_rating_in_half_mile
        description: '{{ doc("column_avg_school_rating_in_half_mile") }}'
      - name: lake_michigan_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: lake_michigan_dist_ft
        description: '{{ doc("column_lake_michigan_dist_ft") }}'
      - name: nearest_bike_trail_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_bike_trail_dist_ft
        description: '{{ doc("column_nearest_bike_trail_dist_ft") }}'
      - name: nearest_bike_trail_id
        description: '{{ doc("column_nearest_bike_trail_id") }}'
      - name: nearest_bike_trail_name
        description: '{{ doc("column_nearest_bike_trail_name") }}'
      - name: nearest_cemetery_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_cemetery_dist_ft
        description: '{{ doc("column_nearest_cemetery_dist_ft") }}'
      - name: nearest_cemetery_gnis_code
        description: '{{ doc("column_nearest_cemetery_gnis_code") }}'
      - name: nearest_cemetery_name
        description: '{{ doc("column_nearest_cemetery_name") }}'
      - name: nearest_cta_route_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_cta_route_dist_ft
        description: '{{ doc("column_nearest_cta_route_dist_ft") }}'
      - name: nearest_cta_route_id
        description: '{{ doc("column_nearest_cta_route_id") }}'
      - name: nearest_cta_route_name
        description: '{{ doc("column_nearest_cta_route_name") }}'
      - name: nearest_cta_stop_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_cta_stop_dist_ft
        description: '{{ doc("column_nearest_cta_stop_dist_ft") }}'
      - name: nearest_cta_stop_id
        description: '{{ doc("column_nearest_cta_stop_id") }}'
      - name: nearest_cta_stop_name
        description: '{{ doc("column_nearest_cta_stop_name") }}'
      - name: nearest_golf_course_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_golf_course_dist_ft
        description: '{{ doc("column_nearest_golf_course_dist_ft") }}'
      - name: nearest_golf_course_id
        description: '{{ doc("column_nearest_golf_course_id") }}'
      - name: nearest_grocery_store_dist_ft
        description: '{{ doc("column_nearest_grocery_store_dist_ft") }}'
      - name: nearest_grocery_store_name
        description: '{{ doc("column_nearest_grocery_store_name") }}'
      - name: nearest_grocery_store_name
        description: '{{ doc("column_nearest_grocery_store_name") }}'
      - name: nearest_hospital_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_hospital_dist_ft
        description: '{{ doc("column_nearest_hospital_dist_ft") }}'
      - name: nearest_hospital_gnis_code
        description: '{{ doc("column_nearest_hospital_gnis_code") }}'
      - name: nearest_hospital_name
        description: '{{ doc("column_nearest_hospital_name") }}'
      - name: nearest_major_road_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_major_road_dist_ft
        description: '{{ doc("column_nearest_major_road_dist_ft") }}'
      - name: nearest_major_road_name
        description: '{{ doc("column_nearest_major_road_name") }}'
      - name: nearest_major_road_osm_id
        description: '{{ doc("column_nearest_major_road_osm_id") }}'
      - name: nearest_metra_route_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_metra_route_dist_ft
        description: '{{ doc("column_nearest_metra_route_dist_ft") }}'
      - name: nearest_metra_route_id
        description: '{{ doc("column_nearest_metra_route_id") }}'
      - name: nearest_metra_route_name
        description: '{{ doc("column_nearest_metra_route_name") }}'
      - name: nearest_metra_stop_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_metra_stop_dist_ft
        description: '{{ doc("column_nearest_metra_stop_dist_ft") }}'
      - name: nearest_metra_stop_id
        description: '{{ doc("column_nearest_metra_stop_id") }}'
      - name: nearest_metra_stop_name
        description: '{{ doc("column_nearest_metra_stop_name") }}'
      - name: nearest_neighbor_1_dist_ft
        description: '{{ doc("column_nearest_neighbor_dist_ft") }}'
      - name: nearest_neighbor_1_pin10
        description: '{{ doc("column_nearest_neighbor_pin10") }}'
      - name: nearest_neighbor_2_dist_ft
        description: '{{ doc("column_nearest_neighbor_dist_ft") }}'
      - name: nearest_neighbor_2_pin10
        description: '{{ doc("column_nearest_neighbor_pin10") }}'
      - name: nearest_neighbor_3_dist_ft
        description: '{{ doc("column_nearest_neighbor_dist_ft") }}'
      - name: nearest_neighbor_3_pin10
        description: '{{ doc("column_nearest_neighbor_pin10") }}'
      - name: nearest_new_construction_char_yrblt
        description: '{{ doc("column_nearest_new_construction_char_yrblt") }}'
      - name: nearest_new_construction_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_new_construction_dist_ft
        description: '{{ doc("column_nearest_new_construction_dist_ft") }}'
      - name: nearest_new_construction_pin10
        description: '{{ doc("column_nearest_new_construction_pin10") }}'
      - name: nearest_park_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_park_dist_ft
        description: '{{ doc("column_nearest_park_dist_ft") }}'
      - name: nearest_park_name
        description: '{{ doc("column_nearest_park_name") }}'
      - name: nearest_park_osm_id
        description: '{{ doc("column_nearest_park_osm_id") }}'
      - name: nearest_railroad_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_railroad_dist_ft
        description: '{{ doc("column_nearest_railroad_dist_ft") }}'
      - name: nearest_railroad_id
        description: '{{ doc("column_nearest_railroad_id") }}'
      - name: nearest_railroad_name
        description: '{{ doc("column_nearest_railroad_name") }}'
      - name: nearest_secondary_road_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_secondary_road_dist_ft
        description: '{{ doc("column_nearest_secondary_road_dist_ft") }}'
      - name: nearest_secondary_road_name
        description: '{{ doc("column_nearest_secondary_road_name") }}'
      - name: nearest_secondary_road_osm_id
        description: '{{ doc("column_nearest_secondary_road_osm_id") }}'
      - name: nearest_stadium_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_stadium_dist_ft
        description: '{{ doc("column_nearest_stadium_dist_ft") }}'
      - name: nearest_stadium_name
        description: '{{ doc("column_nearest_stadium_name") }}'
      - name: nearest_university_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_university_dist_ft
        description: '{{ doc("column_nearest_university_dist_ft") }}'
      - name: nearest_university_gnis_code
        description: '{{ doc("column_nearest_university_gnis_code") }}'
      - name: nearest_university_name
        description: '{{ doc("column_nearest_university_name") }}'
      - name: nearest_vacant_land_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_vacant_land_dist_ft
        description: '{{ doc("column_nearest_vacant_land_dist_ft") }}'
      - name: nearest_vacant_land_pin10
        description: '{{ doc("column_nearest_vacant_land_pin10") }}'
      - name: nearest_water_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: nearest_water_dist_ft
        description: '{{ doc("column_nearest_water_dist_ft") }}'
      - name: nearest_water_id
        description: '{{ doc("column_nearest_water_id") }}'
      - name: nearest_water_name
        description: '{{ doc("column_nearest_water_name") }}'
      - name: num_bus_stop_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: num_bus_stop_in_half_mile
        description: '{{ doc("column_num_bus_stop_in_half_mile") }}'
      - name: num_foreclosure_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: num_foreclosure_in_half_mile_past_5_years
        description: '{{ doc("column_num_foreclosure_in_half_mile_past_5_years") }}'
      - name: num_foreclosure_per_1000_pin_past_5_years
        description: '{{ doc("column_num_foreclosure_per_1000_pin_past_5_years") }}'
      - name: num_pin_in_half_mile
        description: '{{ doc("column_num_pin_in_half_mile") }}'
      - name: num_school_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: num_school_in_half_mile
        description: '{{ doc("column_num_school_in_half_mile") }}'
      - name: num_school_rating_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: num_school_with_rating_in_half_mile
        description: '{{ doc("column_num_school_with_rating_in_half_mile") }}'
      - name: pin10
        description: '{{ doc("shared_column_pin10") }}'
      - name: year
        description: '{{ doc("shared_column_year") }}'

  - name: proximity.vw_pin10_proximity_fill
    description: '{{ doc("view_vw_pin10_proximity_fill") }}'
    columns: *vw_proximity_columns

exposures:
  - name: parcel_proximity
    label: Parcel Proximity
    type: dashboard
    url: https://datacatalog.cookcountyil.gov/Property-Taxation/Assessor-Parcel-Proximity/ydue-e5u3
    depends_on:
      - ref('proximity.vw_pin10_proximity')
    owner:
      name: Data Department
    meta:
      test_row_count: true
      asset_id: ydue-e5u3
      primary_key:
        - pin10
        - year
    description: |
      Cook County 10-digit parcels with attached distances to various spatial features.

      Notes: Refreshed monthly, data is updated yearly as spatial files are made available.

      Use cases: Can be used to isolate parcels by distance to specific spatial features.
