version: 2


models:
  - name: default.vw_pin_history
    description: '{{ doc("vw_pin_history") }}'
    tests:
      # Unique by 14-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin_history_unique_by_14_digit_pin_and_year
          combination_of_columns:
            - pin
            - year
  - name: default.vw_pin_value
    description: '{{ doc("vw_pin_value") }}'
    tests:
      # Unique by 14-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin_value_unique_by_14_digit_pin_and_year
          combination_of_columns:
            - pin
            - year
      # TODO: Values match what's in whatever iasworld view feeds our website
  - name: default.vw_pin_appeal
    description: '{{ doc("vw_pin_appeal") }}'
    tests:
      # `change` should be an enum
      - expression_is_true:
          name: vw_pin_appeal_no_unexpected_change_values
          expression: change is null or change in ('change', 'no change')
          select_columns:
            - pin
            - year
            - case_no
            - change
          config:
            error_if: ">43"
      # If there is a `change`, the values should reflect this
      - expression_is_true:
          name: vw_pin_appeal_change_matches_appeal_outcome
          expression: >-
            (change = 'no change' AND
              (mailed_bldg, mailed_land, mailed_tot)
              =
              (certified_bldg, certified_land, certified_tot)
            )
            OR
            (change = 'change' AND
              (mailed_bldg, mailed_land, mailed_tot)
              !=
              (certified_bldg, certified_land, certified_tot)
            )
            OR
            (change is null)
          select_columns:
            - pin
            - year
            - case_no
            - mailed_bldg
            - certified_bldg
            - mailed_land
            - certified_land
            - mailed_tot
            - certified_tot
          config:
            error_if: ">266758"
  - name: default.vw_card_res_char
    description: '{{ doc("vw_card_res_char") }}'
    tests:
      # Unique by card and year
      - dbt_utils.unique_combination_of_columns:
          name: vw_card_res_char_unique_by_pin_card_and_year
          combination_of_columns:
            - pin
            - year
            - card
      # TODO: Characteristics columns should adhere to pre-determined criteria
  - name: default.vw_pin_address
    description: '{{ doc("vw_pin_address") }}'
    tests:
      # Unique by 14-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin_address_unique_by_14_digit_pin_and_year
          combination_of_columns:
            - pin
            - year
      # No superfluous whitespace
      - no_extra_whitespace:
          name: vw_pin_address_no_extra_whitespace
          column_names:
            - prop_address_full
            - prop_address_city_name
            - prop_address_state
            - prop_address_zipcode_1
            - prop_address_zipcode_2
            - mail_address_full
            - mail_address_city_name
            - mail_address_state
            - mail_address_zipcode_1
            - mail_address_zipcode_2
          config:
            error_if: ">880615"
      # TODO: Mailing address changes after validated sale(?)
      # TODO: Site addresses are all in Cook County
  - name: default.vw_pin_condo_char
    description: '{{ doc("vw_pin_condo_char") }}'
    tests:
      # Unique by 14-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin_condo_char_unique_by_14_digit_pin_and_year
          combination_of_columns:
            - pin
            - year
          config:
            error_if: ">70297"
      # TODO: Non-liveable unit heuristics
      # TODO: Row count matches PARDAT for condo classes
      # TODO: Non-unit and unit parcel count add up to total parcels per
      # 10-digit PIN
      # TODO: Sum of proration rate never exceeds 1 per 10-digit PIN
      # TODO: Characteristics columns should adhere to pre-determined criteria
  - name: default.vw_pin_land
    description: '{{ doc("vw_pin_land") }}'
  - name: default.vw_pin_sale
    description: '{{ doc("vw_pin_sale") }}'
    columns:
      - name: doc_no
        tests:
          - unique:
              config:
                error_if: ">1711769"
    tests:
      # No sales for same price/pin within 12 months
      - unique_combination_of_columns:
          name: vw_pin_sale_unique_price_pin_and_year
          combination_of_columns:
            - pin
            - year
            - sale_price
      # Number of sales for a given time period isn't suspicious
      - unique_combination_of_columns:
          name: vw_pin_sale_reasonable_number_of_sales_per_year
          combination_of_columns:
            - pin
            - year
          allowed_duplicates: 2
          config:
            error_if: ">3192"
      # TODO: Sale is validated (after sales validation has been added to
      # iasworld)
      # TODO: Validation is catching obvious outliers
      # TODO: Joins with other tables produce consistent number of rows
  - name: default.vw_pin_universe
    description: '{{ doc("vw_pin_universe") }}'
    tests:
      # Unique by 14-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin_universe_unique_by_14_digit_pin_and_year
          combination_of_columns:
            - pin
            - year
      # Number of towns is consistent over time
      - count_is_consistent:
          name: vw_pin_universe_township_code_count_is_consistent_by_year
          group_column: year
          count_column: township_code
      # Number of classes is consistent over time
      - count_is_consistent:
          name: vw_pin_universe_class_count_is_consistent_by_year
          group_column: year
          count_column: class
          config:
            error_if: ">24"
      # TODO: Data completeness correlates with availability of spatial data
      # by year
  - name: default.vw_pin_exempt
