replace(replace(`tax_municipality_num`, '[', ''), ']', '')
replace(replace(`tax_municipality_name`, '[', ''), ']', '')
replace(replace(`tax_school_elementary_district_num`, '[', ''), ']', '')
replace(replace(`tax_school_elementary_district_name`, '[', ''), ']', '')
replace(replace(`tax_school_secondary_district_num`, '[', ''), ']', '')
replace(replace(`tax_school_secondary_district_name`, '[', ''), ']', '')
replace(replace(`tax_school_unified_district_num`, '[', ''), ']', '')
replace(replace(`tax_school_unified_district_name`, '[', ''), ']', '')
replace(replace(`tax_community_college_district`, '[', ''), ']', '')
replace(replace(`tax_community_college_district_name`, '[', ''), ']', '')
replace(replace(`tax_fire_protection_district_num`, '[', ''), ']', '')
replace(replace(`tax_fire_protection_district_name`, '[', ''), ']', '')
replace(replace(`tax_library_district_num`, '[', ''), ']', '')
replace(replace(`tax_library_district_name`, '[', ''), ']', '')
replace(replace(`tax_park_district_num`, '[', ''), ']', '')
replace(replace(`tax_park_district_name`, '[', ''), ']', '')
replace(replace(`tax_sanitation_district_num`, '[', ''), ']', '')
replace(replace(`tax_sanitation_district_name`, '[', ''), ']', '')
replace(replace(`tax_special_service_area_num`, '[', ''), ']', '')
replace(replace(`tax_special_service_area_name`, '[', ''), ']', '')
replace(replace(`tax_tif_district_num`, '[', ''), ']', '')
replace(replace(`tax_tif_district_name`, '[', ''), ']', '')
left_pad(`pin`, 14, '0')
left_pad(`pin10`, 10, '0')

