---
File_Locations:
  LANDING_BUCKET : "ccao-landing-us-east-1"
  LANDING_FOLDER : "iasworld/data"
  STAGE_BUCKET : "ccao-staging-us-east-1"
  STAGE_RAW_FOLDER : "target"
  STAGE_ARCHIVE_FOLDER : "archives"
  STAGE_AUDIT_LOG_FOLDER : "audit-logs"
Fact_Tables:
  ADDN: JUR, PARID, CARD,TAXYR, LLINE
  APRVAL: JUR,PARID,TAXYR
  ASMT_HIST: JUR, PARID,TAXYR
  COMDAT: JUR, PARID, TAXYR, CARD
  CVLEG: JUR, PARID,TAXYR, CONVEYNO
  CVOWN: JUR,TAXYR, CONVEYNO
  CVTRAN: JUR,TAXYR,CONVEYNO
  DWELDAT: JUR,PARID, CARD,TAXYR, SEQ
  EXDET: JUR, PARID,TAXYR,LINENO
  HTPAR: JUR,PARID,TAXYR,HEARTYP,SUBKEY
  LAND: JUR,PARID,LLINE,TAXYR
  LEGDAT: JUR, PARID,TAXYR
  OWNDAT: JUR, PARID, TAXYR, OWNSEQ
  SALES: JUR, PARID, SALEKEY
Dimension_Tables:
  AASYSJUR: JUR
  ADDRINDX: JUR, PARID, TAXYR, TABSEQ
  CNAME: JUR, OWNNUM
  COMNT: JUR, PARID, CODE, COMNTNO
  EXADMN: JUR, PARID, TAXYR
  EXCODE: JUR, EXCODE, TAXYR, SEQ
  HTAGNT: JUR, AGENT
  LPMOD: LCODE
  LPNBHD: JUR, NBHD
  RCOBY: VER, CODE
  SPLCOM: JUR, OLDID, NEWID, TAXYR, SPLITNO, SEQ
  VALCLASS: JUR, TAXYR, ROLLTYPE, VALCLASS