---
File_Locations:
  LANDING_BUCKET : "ccao-landing-us-east-1"
  LANDING_FOLDER : "iasworld/data"
  STAGE_BUCKET : "ccao-staging-us-east-1"
  STAGE_RAW_FOLDER : "iasworld/target"
  STAGE_ARCHIVE_FOLDER : "iasworld/archives"
  STAGE_AUDIT_LOG_FOLDER : "iasworld/audit-logs"
Fact_Tables:
  ADDN: JUR, PARID, CARD, TAXYR, LLINE
  APRVAL: JUR, PARID, TAXYR
  ASMT_ALL: JUR, PARID, TAXYR
  ASMT_HIST: JUR, PARID, TAXYR
  COMDAT: JUR, PARID, TAXYR, CARD
  CVLEG: JUR, PARID,TAXYR, CONVEYNO
  CVOWN: JUR, TAXYR, CONVEYNO
  CVTRAN: JUR, TAXYR,CONVEYNO
  DWELDAT: JUR, PARID, CARD, TAXYR, SEQ
  EXDET: JUR, PARID, TAXYR, LINENO
  HTPAR: JUR, PARID, TAXYR, HEARTYP, SUBKEY
  LAND: JUR, PARID, LLINE, TAXYR
  LEGDAT: JUR, PARID, TAXYR
  OBY: JUR, PARID, CARD, TAXYR, LLINE
  OWNDAT: JUR, PARID, TAXYR, OWNSEQ
  PARDAT: JUR, PARID,TAXYR
  SALES: JUR, PARID, SALEKEY
Dimension_Tables:
  AASYSJUR: JUR
  ADDRINDX: JUR, PARID, TAXYR, TABSEQ
  CNAME: JUR, OWNNUM
  #COMFEAT: JUR, PARID, TAXYR, CARD, LLINE
  #COMINTEXT: JUR, PARID, TAXYR, CARD, LLINE
  COMNT: JUR, PARID, CODE, COMNTNO
  #COMNT3: JUR, PARID, TAXYR, COMNTNO
  EXADMN: JUR, PARID, TAXYR
  EXCODE: JUR, EXCODE, TAXYR, SEQ
  #DEDIT:
  HTAGNT: JUR, AGENT
  #HTDATES: JUR, PARID,TAXYR, HEARTYP, SUBKEY, SCHDTE
  LPMOD: LCODE
  LPNBHD: JUR, NBHD
  RCOBY: VER, CODE
  SPLCOM: JUR, OLDID, NEWID, TAXYR, SPLITNO, SEQ
  VALCLASS: JUR, TAXYR, ROLLTYPE, VALCLASS
