models:
  - name: location.access
  - name: location.census
  - name: location.census_acs5
  - name: location.chicago
  - name: location.crosswalk_year_fill
  - name: location.economy
  - name: location.environment
  - name: location.other
  - name: location.political
  - name: location.school
  - name: location.tax
  - name: location.vw_pin10_location
    description: '{{ doc("vw_pin10_location") }}'
    tests:
      # Unique by 10-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin10_location_unique_by_10_digit_pin_and_year
          combination_of_columns:
            - pin10
            - year
      # GeoIDs are the correct length
      - column_length:
          name: vw_pin10_location_seven_digit_geoids_are_the_correct_length
          length: 7
          columns:
            - census_place_geoid
            - census_puma_geoid
            - census_school_district_elementary_geoid
            - census_school_district_secondary_geoid
            - census_acs5_place_geoid
            - census_acs5_puma_geoid
            - census_acs5_school_district_elementary_geoid
            - census_acs5_school_district_secondary_geoid
          additional_select_columns:
            - pin10
            - year
      # TODO: Columns specific to certain locations only have values for that
      # location
  - name: location.vw_pin10_location_fill
    description: '{{ doc("vw_pin10_location_fill") }}'
