models:
  - name: location.access
    description: '{{ doc("table_access") }}'

  - name: location.census
    description: '{{ doc("table_census") }}'

  - name: location.census_acs5
    description: '{{ doc("table_census_acs5") }}'

  - name: location.chicago
    description: '{{ doc("table_chicago") }}'

  - name: location.crosswalk_year_fill
    description: '{{ doc("table_crosswalk_year_fill") }}'

  - name: location.economy
    description: '{{ doc("table_economy") }}'

  - name: location.environment
    description: '{{ doc("table_environment") }}'

  - name: location.other
    description: '{{ doc("table_other") }}'

  - name: location.political
    description: '{{ doc("table_political") }}'

  - name: location.school
    description: '{{ doc("table_school") }}'

  - name: location.tax
    description: '{{ doc("table_tax") }}'

  - name: location.vw_pin10_location
    description: '{{ doc("view_vw_pin10_location") }}'
    columns: &vw_location_columns
      - name: access_cmap_walk_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: access_cmap_walk_id
        description: '{{ doc("column_access_cmap_walk_id") }}'
      - name: access_cmap_walk_nta_score
        description: '{{ doc("column_access_cmap_walk_nta_score") }}'
      - name: access_cmap_walk_total_score
        description: '{{ doc("column_access_cmap_walk_total_score") }}'
      - name: census_acs5_congressional_district_geoid
        description: '{{ doc("column_census_congressional_district_geoid") }}'
      - name: census_acs5_county_subdivision_geoid
        description: '{{ doc("column_census_county_subdivision_geoid") }}'
      - name: census_acs5_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: census_acs5_place_geoid
        description: '{{ doc("column_census_place_geoid") }}'
      - name: census_acs5_puma_geoid
        description: '{{ doc("column_census_puma_geoid") }}'
      - name: census_acs5_school_district_elementary_geoid
        description: '{{ doc("column_census_school_district_elementary_geoid") }}'
      - name: census_acs5_school_district_secondary_geoid
        description: '{{ doc("column_census_school_district_secondary_geoid") }}'
      - name: census_acs5_school_district_unified_geoid
        description: '{{ doc("column_census_school_district_unified_geoid") }}'
      - name: census_acs5_state_representative_geoid
        description: '{{ doc("column_census_state_representative_geoid") }}'
      - name: census_acs5_state_senate_geoid
        description: '{{ doc("column_census_state_senate_geoid") }}'
      - name: census_acs5_tract_geoid
        description: '{{ doc("column_census_tract_geoid") }}'
      - name: census_block_geoid
        description: '{{ doc("column_census_block_geoid") }}'
      - name: census_block_group_geoid
        description: '{{ doc("column_census_block_group_geoid") }}'
      - name: census_congressional_district_geoid
        description: '{{ doc("column_census_congressional_district_geoid") }}'
      - name: census_county_subdivision_geoid
        description: '{{ doc("column_census_county_subdivision_geoid") }}'
      - name: census_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: census_place_geoid
        description: '{{ doc("column_census_place_geoid") }}'
      - name: census_puma_geoid
        description: '{{ doc("column_census_puma_geoid") }}'
      - name: census_school_district_elementary_geoid
        description: '{{ doc("column_census_school_district_elementary_geoid") }}'
      - name: census_school_district_secondary_geoid
        description: '{{ doc("column_census_school_district_secondary_geoid") }}'
      - name: census_school_district_unified_geoid
        description: '{{ doc("column_census_school_district_unified_geoid") }}'
      - name: census_state_representative_geoid
        description: '{{ doc("column_census_state_representative_geoid") }}'
      - name: census_state_senate_geoid
        description: '{{ doc("column_census_state_senate_geoid") }}'
      - name: census_tract_geoid
        description: '{{ doc("column_census_tract_geoid") }}'
      - name: census_zcta_geoid
        description: '{{ doc("column_census_zcta_geoid") }}'
      - name: chicago_community_area_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: chicago_community_area_name
        description: '{{ doc("column_chicago_community_area_name") }}'
      - name: chicago_community_area_num
        description: '{{ doc("column_chicago_community_area_num") }}'
      - name: chicago_industrial_corridor_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: chicago_industrial_corridor_name
        description: '{{ doc("column_chicago_industrial_corridor_name") }}'
      - name: chicago_industrial_corridor_num
        description: '{{ doc("column_chicago_industrial_corridor_num") }}'
      - name: chicago_police_district_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: chicago_police_district_num
        description: '{{ doc("column_chicago_police_district_num") }}'
      - name: cook_board_of_review_district_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: cook_board_of_review_district_num
        description: '{{ doc("column_cook_board_of_review_district_num") }}'
      - name: cook_commissioner_district_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: cook_commissioner_district_num
        description: '{{ doc("column_cook_commissioner_district_num") }}'
      - name: cook_judicial_district_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: cook_judicial_district_num
        description: '{{ doc("column_cook_judicial_district_num") }}'
      - name: econ_coordinated_care_area_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: econ_coordinated_care_area_num
        description: '{{ doc("column_econ_coordinated_care_area_num") }}'
      - name: econ_enterprise_zone_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: econ_enterprise_zone_num
        description: '{{ doc("column_econ_enterprise_zone_num") }}'
      - name: econ_industrial_growth_zone_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: econ_industrial_growth_zone_num
        description: '{{ doc("column_econ_industrial_growth_zone_num") }}'
      - name: econ_qualified_opportunity_zone_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: econ_qualified_opportunity_zone_num
        description: '{{ doc("column_econ_qualified_opportunity_zone_num") }}'
      - name: env_airport_noise_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: env_airport_noise_dnl
        description: '{{ doc("column_env_airport_noise_dnl") }}'
      - name: env_flood_fema_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: env_flood_fema_sfha
        description: '{{ doc("column_env_flood_fema_sfha") }}'
      - name: env_flood_fs_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: env_flood_fs_factor
        description: '{{ doc("column_env_flood_fs_factor") }}'
      - name: env_flood_fs_risk_direction
        description: '{{ doc("column_env_flood_fs_risk_direction") }}'
      - name: env_ohare_noise_contour_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: env_ohare_noise_contour_half_mile_buffer_bool
        description: '{{ doc("column_env_ohare_noise_contour_half_mile_buffer_bool") }}'
      - name: env_ohare_noise_contour_no_buffer_bool
        description: '{{ doc("column_env_ohare_noise_contour_no_buffer_bool") }}'
      - name: misc_subdivision_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: misc_subdivision_id
        description: '{{ doc("column_misc_subdivision_id") }}'
      - name: pin10
        description: '{{ doc("shared_column_pin10") }}'
      - name: school_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: school_elementary_district_geoid
        description: '{{ doc("column_school_elementary_district_geoid") }}'
      - name: school_elementary_district_name
        description: '{{ doc("column_school_elementary_district_name") }}'
      - name: school_school_year
        description: '{{ doc("column_school_year") }}'
      - name: school_secondary_district_geoid
        description: '{{ doc("column_school_secondary_district_geoid") }}'
      - name: school_secondary_district_name
        description: '{{ doc("column_school_secondary_district_name") }}'
      - name: school_unified_district_geoid
        description: '{{ doc("column_school_unified_district_geoid") }}'
      - name: school_unified_district_name
        description: '{{ doc("column_school_unified_district_name") }}'
      - name: tax_community_college_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_community_college_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: tax_fire_protection_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_fire_protection_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_library_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_library_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_municipality_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_municipality_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_park_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_park_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_sanitation_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_sanitation_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_school_elementary_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_school_elementary_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_school_secondary_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_school_secondary_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_school_unified_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_school_unified_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_special_service_area_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_special_service_area_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: tax_tif_district_name
        description: '{{ doc("column_tax_district_name") }}'
      - name: tax_tif_district_num
        description: '{{ doc("column_tax_district_num") }}'
      - name: ward_chicago_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: ward_evanston_data_year
        description: '{{ doc("shared_column_data_year") }}'
      - name: ward_name
        description: '{{ doc("column_ward_name") }}'
      - name: ward_num
        description: '{{ doc("column_ward_num") }}'
      - name: year
        description: '{{ doc("shared_column_year") }}'

    tests:
      # Unique by 10-digit PIN and year
      - unique_combination_of_columns:
          name: vw_pin10_location_unique_by_10_digit_pin_and_year
          combination_of_columns:
            - pin10
            - year
      # GeoIDs are the correct length
      - column_length:
          name: vw_pin10_location_seven_digit_geoids_are_the_correct_length
          length: 7
          columns:
            - census_place_geoid
            - census_puma_geoid
            - census_school_district_elementary_geoid
            - census_school_district_secondary_geoid
            - census_acs5_place_geoid
            - census_acs5_puma_geoid
            - census_acs5_school_district_elementary_geoid
            - census_acs5_school_district_secondary_geoid
          additional_select_columns:
            - pin10
            - year
      # TODO: Columns specific to certain locations only have values for that
      # location

  - name: location.vw_pin10_location_fill
    description: '{{ doc("view_vw_pin10_location_fill") }}'
    columns: *vw_location_columns
