version: 2


sources:
  - name: reporting
    tables:
      - name: ratio_stats
      - name: res_report_summary

models:
  - name: reporting.vw_assessment_roll
    tests:
      - unique_combination_of_columns: 
          name: vw_assessment_roll_unique_by_year_stage_township_name_class
          combination_of_columns:
            - year
            - stage
            - township_name
            - class
  - name: reporting.vw_most_recent_boundary
    tests:
      - unique_combination_of_columns:
          name: vw_most_recent_boundary_unique_by_pin10_municipality_name
          combination_of_columns:
            - pin10
            - municipality_name
  - name: reporting.vw_pin_most_recent_sale
  - name: reporting.vw_ratio_stats
    tests:
      - unique_combination_of_columns:
          name: vw_ratio_stats_unique_by_pin_year_assessment_stage_sale_price
          combination_of_columns:
            - pin
            - year
            - assessment_stage
            - sale_price
  - name: reporting.vw_res_report_summary
    tests:
      - unique_combination_of_columns:
          name: vw_res_report_summary_unique_by_geography_id_property_group_assessment_stage_year
          combination_of_columns:
            - geography_id
            - property_group
            - assessment_stage
            - year
  - name: reporting.vw_top_5
  - name: reporting.vw_town_sale_history
    tests:
      - unique_combination_of_columns:
          name: vw_town_sale_history_unique_by_geography_id_property_group_sale_year
          combination_of_columns:
            - geography_id
            - property_group
            - sale_year

