version: 2


models:
  - name: reporting.ratio_stats
  - name: reporting.res_report_summary
  - name: reporting.vw_assessment_roll
  - name: reporting.vw_pin_most_recent_sale
  - name: reporting.vw_ratio_stats
  - name: reporting.vw_res_report_summary
  - name: reporting.vw_top_5
  - name: reporting.vw_town_sale_history
