/* This query aggregates assessed values and exemptions for each tax code in the county. Used in conjunction with data on TIF
increments and jurisdiction crosswalks to tax codes, this query allows the calculation of tax bases for every
jurisdiction in the County at each of the three main stages in the assessment cycle */

SELECT * INTO DTBL_TAX_BASE_BY_TAXCODE FROM (

SELECT 
/* Contextual Fields */
X.TAX_YEAR AS [Year], [Equalization Factor], X.TAX_CODE AS [Tax Code], X.TOWNSHIP AS [Township], X.MAJOR_CLASS AS [Major Class], PIN_COUNT AS [Total PINs]
/* Aggregate Values */
, X.TOTAL_ASSMAILED_AV AS [Total Assessor Mailed AV]
, X.TOTAL_ASSCERT_AV AS [Total Assessor Certified AV]
, X.TOTAL_BORCERT_AV AS [Total Board Certified AV]
, TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX_ASSMAILED AS [Total Clerk Exemptions at Assr. Mailing]
, TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX_ASSCERT AS [Total Clerk Exemptions at Assr. Certified]
, TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX_BOR AS [Total Clerk Exemptions at BOR Certified]
, CASE WHEN TOTAL_CLERK_EXEMPTIONS IS NULL AND TOTAL_ASSR_EXEMPTIONS IS NULL AND DIS_VET_80_EX_ASSMAILED IS NULL THEN 0
		WHEN TOTAL_CLERK_EXEMPTIONS IS NULL AND TOTAL_ASSR_EXEMPTIONS IS NOT NULL AND DIS_VET_80_EX_ASSMAILED IS NULL THEN TOTAL_ASSR_EXEMPTIONS + 0
		WHEN TOTAL_CLERK_EXEMPTIONS IS NOT NULL AND  DIS_VET_80_EX_ASSMAILED IS NULL THEN TOTAL_CLERK_EXEMPTIONS + 0 
		WHEN TOTAL_CLERK_EXEMPTIONS IS NOT NULL AND  DIS_VET_80_EX_ASSMAILED IS NOT NULL THEN TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX_ASSMAILED 
		ELSE 'Error'
		END AS [Total Exemptions at Assr. Mailing]
, CASE WHEN TOTAL_CLERK_EXEMPTIONS IS NULL AND TOTAL_ASSR_EXEMPTIONS IS NULL AND DIS_VET_80_EX_ASSMAILED IS NULL THEN 0
		WHEN TOTAL_CLERK_EXEMPTIONS IS NULL AND TOTAL_ASSR_EXEMPTIONS IS NOT NULL AND DIS_VET_80_EX_ASSMAILED IS NULL THEN TOTAL_ASSR_EXEMPTIONS + 0
		WHEN TOTAL_CLERK_EXEMPTIONS IS NOT NULL AND  DIS_VET_80_EX_ASSMAILED IS NULL THEN TOTAL_CLERK_EXEMPTIONS + 0 
		WHEN TOTAL_CLERK_EXEMPTIONS IS NOT NULL AND  DIS_VET_80_EX_ASSMAILED IS NOT NULL THEN TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX_ASSCERT 
		ELSE 'Error'
		END AS [Total Exemptions at Assr. Certified]
, CASE WHEN TOTAL_CLERK_EXEMPTIONS IS NULL AND TOTAL_ASSR_EXEMPTIONS IS NULL AND DIS_VET_80_EX_ASSMAILED IS NULL THEN 0
		WHEN TOTAL_CLERK_EXEMPTIONS IS NULL AND TOTAL_ASSR_EXEMPTIONS IS NOT NULL AND DIS_VET_80_EX_ASSMAILED IS NULL THEN TOTAL_ASSR_EXEMPTIONS + 0
		WHEN TOTAL_CLERK_EXEMPTIONS IS NOT NULL AND  DIS_VET_80_EX_ASSMAILED IS NULL THEN TOTAL_CLERK_EXEMPTIONS + 0 
		WHEN TOTAL_CLERK_EXEMPTIONS IS NOT NULL AND  DIS_VET_80_EX_ASSMAILED IS NOT NULL THEN TOTAL_CLERK_EXEMPTIONS + DIS_VET_80_EX_BOR 
		ELSE 'Error'
		END AS [Total Exemptions at BOR Certified]
 FROM (  
	  SELECT
	  H.TAX_YEAR, FACTOR as [Equalization Factor]
	  , CL_TXCD AS TAX_CODE
	  , H.HD_TOWN AS TOWNSHIP 
	  , LEFT(H.HD_CLASS, 1) AS MAJOR_CLASS
	  /* PART 1: Total EAV, excluding disabled vets with >70% disability,
		aggregated from the Board of Review Head file */
	  , SUM(H.HD_ASS_LND+H.HD_ASS_BLD) AS TOTAL_BORCERT_AV
	  , SUM(T.HD_ASS_LND+T.HD_ASS_BLD) AS TOTAL_ASSMAILED_AV
	  , SUM(TB.HD_ASS_LND+TB.HD_ASS_BLD) AS TOTAL_ASSCERT_AV
	  , COUNT(H.PIN) AS PIN_COUNT
	  /* PART 2. Total Exempt EAV, excluding disabled vets with >70% disability
			, aggregated from the Clerk's exemtpion data. */
	  , SUM(CLRK.CL_DIS_IND+CLRK.CL_DIS_VET+CL_FREEZE_EXE_AMT+CL_HOMOWN_EXE_AMT+
	 CL_HOMSTD_EXE_AMT+CL_RET_VET+CL_DIS_VET_GE75K+
	 CL_DIS_VET_LT75K+CL_EXOWNEXVAL) AS TOTAL_CLERK_EXEMPTIONS
	 , SUM(E.HO + E.HS + E.SF + E.DISABLED + E.DVET_GE75 + E.DVET_LT75 + E.VETERAN +E.RETURN_VET) AS TOTAL_ASSR_EXEMPTIONS
	  FROM AS_HEADBR AS H   
	  LEFT JOIN EXEMPTIONS AS E
		ON E.PIN=H.PIN AND E.TAX_YEAR=H.TAX_YEAR
	  LEFT JOIN FTBL_EQUALIZATION_FACTOR AS F
		ON H.TAX_YEAR=F.TAX_YEAR
	  LEFT JOIN	CLERKVALUES AS CLRK   
		ON CLRK.CL_PIN=H.PIN AND CLRK.TAX_YEAR=H.TAX_YEAR
	  LEFT JOIN AS_HEADT AS T
	    ON T.PIN=H.PIN AND T.TAX_YEAR=H.TAX_YEAR
	  LEFT JOIN AS_HEADTB AS TB
		ON TB.PIN=H.PIN AND TB.TAX_YEAR=H.TAX_YEAR
	  WHERE (1=1) 
	  AND H.HD_ASS_LND+H.HD_ASS_BLD>=150
	  GROUP BY H.TAX_YEAR,FACTOR,CL_TXCD, H.HD_TOWN, LEFT(H.HD_CLASS, 1)
	 ) AS X
	LEFT JOIN
	( /* PART 3. Total EAV for disabled veterans >70% are actually exemptions, up to 250,000.
		 Though these are EAVs, they are actually subtracted from the base as exemptions. */
	SELECT TAX_YEAR, TOWNSHIP, MAJOR_CLASS, TAX_CODE
	, SUM(DIS_VET_80_EX_BORCERT) AS DIS_VET_80_EX_BOR
	, SUM(DIS_VET_80_EX_ASSMAILED) AS DIS_VET_80_EX_ASSMAILED
	, SUM(DIS_VET_80_EX_ASSCERT) AS DIS_VET_80_EX_ASSCERT
	FROM 
	( SELECT H.TAX_YEAR
	  , CLRK.CL_TXCD AS TAX_CODE
	  , H.HD_TOWN AS TOWNSHIP 
	  , LEFT(H.HD_CLASS, 1) AS MAJOR_CLASS
	  /* Take EAV for these PINs up to 250k as an exemption, deducted from the base */
	  , CASE WHEN H.HD_ASS_LND+H.HD_ASS_BLD <250000 THEN H.HD_ASS_LND+H.HD_ASS_BLD ELSE 250000 END AS DIS_VET_80_EX_BORCERT
	  , CASE WHEN T.HD_ASS_LND+T.HD_ASS_BLD <250000 THEN H.HD_ASS_LND+H.HD_ASS_BLD ELSE 250000 END AS DIS_VET_80_EX_ASSMAILED
	  , CASE WHEN TB.HD_ASS_LND+TB.HD_ASS_BLD <250000 THEN H.HD_ASS_LND+H.HD_ASS_BLD ELSE 250000 END AS DIS_VET_80_EX_ASSCERT
	FROM AS_HEADBR AS H
	LEFT JOIN CLERKVALUES AS CLRK
		ON CLRK.PIN=H.PIN AND CLRK.TAX_YEAR=H.TAX_YEAR
    LEFT JOIN AS_HEADT AS T
	    ON T.PIN=H.PIN AND T.TAX_YEAR=H.TAX_YEAR
	LEFT JOIN AS_HEADTB AS TB
		ON TB.PIN=H.PIN AND TB.TAX_YEAR=H.TAX_YEAR
		WHERE (1=1)
		AND H.HD_ASS_LND+H.HD_ASS_BLD>=150 
		AND CL_DIS_IND=8 
		 ) AS XXX
		 GROUP BY TAX_YEAR,TAX_CODE,TOWNSHIP, MAJOR_CLASS
		 ) AS XX
	ON X.TAX_YEAR=XX.TAX_YEAR 
	AND X.TAX_CODE=XX.TAX_CODE
	AND X.TOWNSHIP=XX.TOWNSHIP
	AND X.MAJOR_CLASS=XX.MAJOR_CLASS

	) DTBL_TAX_BASE_BY_TAXCODE