ALTER VIEW VW_CLEAN_IDORSALES AS

SELECT DISTINCT

B.PIN, CONVERT(DATE, B.RECORDED_DATE) as sale_date, CAST(B.SALE_PRICE AS INT) as sale_price, B.DOC_NO, B.DEED_TYPE, YEAR(B.RECORDED_DATE) AS TAX_YEAR

FROM IDORSALES AS B

/* Arbitrarily select a deed */
INNER JOIN
	(SELECT DISTINCT A.PIN, A.RECORDED_DATE, A.SALE_PRICE, MAX(A.DOC_NO) AS DOC_NO FROM IDORSALES AS A
	/* Largest sale price by PIN and date */
	INNER JOIN
		(SELECT X.PIN, X.RECORDED_DATE, MAX(X.SALE_PRICE) AS SALE_PRICE FROM IDORSALES AS X
		GROUP BY X.PIN, X.RECORDED_DATE) AS SSS
		ON A.PIN = SSS.PIN AND A.RECORDED_DATE = SSS.RECORDED_DATE AND A.SALE_PRICE = SSS.SALE_PRICE
		GROUP BY A.PIN, A.RECORDED_DATE, A.SALE_PRICE) AS WW
	ON WW.PIN = B.PIN AND WW.RECORDED_DATE = B.RECORDED_DATE AND WW.DOC_NO = B.DOC_NO

/* Some sales show up more than once with dates transcribed incorrectly as Jan rather than Oct, Nov, or Dec */
INNER JOIN
	(SELECT DOC_NO, MAX(RECORDED_DATE) AS CORRECT_DATE FROM IDORSALES
	GROUP BY DOC_NO) PROBLEM_DATES
ON B.DOC_NO = PROBLEM_DATES.DOC_NO AND B.RECORDED_DATE = PROBLEM_DATES.CORRECT_DATE

WHERE B.DEED_TYPE NOT IN ('Q', 'E', 'B')
	AND MULT_IND = ''
	AND YEAR(B.RECORDED_DATE) >= 1997
	AND (B.DEED_TYPE != '' OR YEAR(B.RECORDED_DATE) <= 2000)