ALTER VIEW VW_RES_UNIVERSE AS

SELECT

/* Fields from AS_HEADT */
H.PIN as PIN, DETAIL.DT_CLASS as CLASS, H.TAX_YEAR, HD_NBHD AS NBHD, HD_HD_SF AS HD_SF, LEFT(HD_TOWN, 2) as TOWN_CODE
, (HD_PRI_LND)*10 as PRI_EST_LAND, (HD_PRI_BLD)*10 as PRI_EST_BLDG
/* Recoded fields */
, 1 as cons
, CASE WHEN MULTI_IND IS NULL THEN 0
		ELSE MULTI_IND END AS MULTI_IND
/* Assign properties to modeling groups */
, CASE WHEN DETAIL.DT_CLASS IN (200, 201, 241) OR (DETAIL.DT_CLASS = 299 AND (DT_CDU != 'GR' OR DT_CDU IS NULL) AND ((HD_PRI_BLD + HD_PRI_LND) > 100 OR (HD_PRI_BLD + HD_PRI_LND) IS NULL)) THEN 'NCHARS'
	WHEN DETAIL.DT_CLASS IN (202, 203, 204, 205, 206, 207, 208, 209, 210, 234, 278, 295) THEN 'SF'
	WHEN DETAIL.DT_CLASS IN (211, 212) THEN 'MF'
	WHEN DETAIL.DT_CLASS = 299 AND (DT_CDU = 'GR' OR (HD_PRI_BLD + HD_PRI_LND) <= 100) THEN 'FIXED'
	ELSE NULL END AS modeling_group
/* Factor variable for NCHARS modeling group */
, CASE WHEN DT_CLASS IN (200,201,241) THEN 200
	WHEN DT_CLASS IN (299) THEN 299
	ELSE NULL END AS CONDO_CLASS_FACTOR
/* Factor variable for mf modeling group */
, CASE WHEN DT_CLASS IN (211, 212) THEN DT_CLASS
	ELSE NULL
	END AS MULTI_FAMILY_IND
/* Count number of condo units in a building */
, n_units
/* Fields from DETAIL */
, KEY_PIN, DT_CDU AS CDU, total_units
/* Where we have missing percentage of ownership, we divide values equally */
, CASE WHEN DT_PER_ASS = 0 THEN 1/n_units
	WHEN DT_PER_ASS IS NULL THEN 1/n_units
	ELSE DT_PER_ASS END AS PER_ASS
/* strata */
, condo_strata_10, condo_strata_100
/* Fields from CCAOSFCHARS */
, APTS, EXT_WALL, ROOF_CNST, ROOMS, BEDS, BSMT, BSMT_FIN, HEAT, OHEAT, AIR, FRPL, ATTIC_TYPE, FBATH, HBATH, TP_PLAN, TP_DSGN, CNST_QLTY, SITE
, GAR1_SIZE, GAR1_CNST, GAR1_ATT, GAR1_AREA, GAR2_SIZE, GAR2_CNST, GAR2_ATT, GAR2_AREA, OT_IMPR, BLDG_SF, REPAIR_CND, MULTI_CODE, VOLUME, NCU
, CASE WHEN TYPE_RESD = 0 THEN NULL
	ELSE TYPE_RESD END AS TYPE_RESD /* NULL recorded as 0 in AS400 */
, CASE WHEN ATTIC_FNSH = 0 THEN NULL
	ELSE ATTIC_FNSH END AS ATTIC_FNSH /* NULL recorded as 0 in AS400 */
, CASE WHEN RENOVATION = 0 THEN NULL
	ELSE RENOVATION END AS RENOVATION /* NULL recorded as 0 in AS400 */
, CASE WHEN PORCH = 0 THEN NULL
	ELSE PORCH END AS PORCH /* NULL recorded as 0 in AS400 */
/* Account for missing characteristics for NCHARS group */
, CASE WHEN DT_CLASS = 299 AND NCHARS_AGE IS NOT NULL THEN NCHARS_AGE
	WHEN AGE IS NULL THEN 10
	ELSE AGE END AS AGE
, CASE WHEN [USE] IS NULL THEN 1
	ELSE [USE] END AS [USE]
/* Calculated field from CCAOSFCHARS where MULTI_IND == 1 */
, total_bldg_sf
/* Fields from TAXBILLAMOUNTS */
, HD_TOWN AS TAX_CD, TB_TAX_RATE AS TAX_RATE, TB_AMT_TAX_PAID AS AMT_TAX_PAID

/* The AS_HEADT file defines the universe of PINs that could have a sale associated with them */
FROM AS_HEADT AS H

/* Total count of 299s in a building */
LEFT JOIN
	(SELECT DISTINCT COUNT(PIN) AS n_units, LEFT(PIN, 10) as PIN10, TAX_YEAR FROM AS_HEADT
	WHERE HD_CLASS = 299
	GROUP BY LEFT(PIN, 10), TAX_YEAR) AS N299
	ON N299.PIN10 = SUBSTRING(H.PIN, 1, 10) AND H.TAX_YEAR = N299.TAX_YEAR
/* Total count of units in a building, including non-residential classes */
LEFT JOIN
	(SELECT COUNT(LEFT(PIN, 10)) AS total_units, LEFT(PIN, 10) AS BUILDING_PIN, TAX_YEAR FROM AS_DETAILT
	WHERE DT_MLT_CD = 1 AND RIGHT(DT_CLASS, 2) NOT IN ('00', '01', '41', '88')
	GROUP BY LEFT(PIN, 10), TAX_YEAR) AS BUILDING_UNITS
	ON LEFT(H.PIN, 10) = BUILDING_PIN AND BUILDING_UNITS.TAX_YEAR = H.TAX_YEAR
/* Percentage of ownership for condos and proration for non-condo buildings on multiple PINs and characteristics for SF & MF */
LEFT JOIN
	(SELECT DISTINCT APTS, EXT_WALL, ROOF_CNST, ROOMS, BEDS, BSMT, BSMT_FIN, HEAT, OHEAT, AIR, FRPL, ATTIC_TYPE, FBATH, HBATH, TP_PLAN, TP_DSGN, CNST_QLTY, SITE,
	GAR1_SIZE, GAR1_CNST, GAR1_ATT, GAR1_AREA, GAR2_SIZE, GAR2_CNST, GAR2_ATT, GAR2_AREA, OT_IMPR, BLDG_SF, REPAIR_CND, MULTI_CODE, VOLUME, NCU,
	TYPE_RESD, ATTIC_FNSH, RENOVATION, PORCH, MULTI_IND, AGE, [USE],
	DT_PIN AS PIN, T.TAX_YEAR, DT_AGE AS NCHARS_AGE, DT_CLASS, DT_CDU, DT_PER_ASS, CASE WHEN DT_KEY_PIN != 0 THEN RIGHT('0' + CAST(DT_KEY_PIN AS VARCHAR), 14) ELSE NULL END AS KEY_PIN
	FROM AS_DETAILT AS T
	LEFT JOIN
	CCAOSFCHARS AS C
	ON T.PIN = C.PIN AND T.TAX_YEAR = C.TAX_YEAR AND T.DT_MLT_CD = C.MULTI_CODE
	WHERE RIGHT(DT_CLASS, 2) NOT IN ('00', '01', '41', '88')) AS DETAIL
	ON H.PIN = DETAIL.PIN AND DETAIL.TAX_YEAR = H.TAX_YEAR
/* Allows us to prorate sale prices based on building size for multi properties */
LEFT JOIN
	(SELECT CASE WHEN SUM(BLDG_SF) = 0 THEN LAG(SUM(BLDG_SF)) OVER (ORDER BY PIN, TAX_YEAR) ELSE SUM(BLDG_SF) END as total_bldg_sf, PIN, TAX_YEAR FROM CCAOSFCHARS
	WHERE MULTI_IND = 1
	GROUP BY PIN, TAX_YEAR) AS PRO
	ON PRO.PIN = H.PIN AND PRO.TAX_YEAR = H.TAX_YEAR
/* Allows us to model condos within strata */
LEFT JOIN
	DTBL_CONDOSTRATA STRATA
	ON LEFT(H.PIN, 10) = STRATA.PIN10 AND H.TAX_YEAR = STRATA.ASSESSMENT_YEAR
/* Add effective tax rates and tax codes */
LEFT JOIN
	TAXBILLAMOUNTS AS TBA
	ON TBA.PIN = H.PIN AND TBA.TAX_YEAR + 1 = H.TAX_YEAR
/*Excludes properties with a pending inspection */
LEFT OUTER JOIN
	(SELECT PIN, TAX_YEAR FROM PERMITTRACKING WHERE COMP_RECV = 0) AS I
	ON I.PIN = H.PIN AND I.TAX_YEAR = H.TAX_YEAR

/* Limit sample to residential parcels */
WHERE DT_CLASS IN (211, 212, 200, 201, 241, 299, 202, 203, 204, 205, 206, 207, 208, 209, 210, 234, 278, 295)