ALTER VIEW VW_RES_UNIVERSE AS

SELECT
	/* Fields from AS_HEADT */
	HEADT.PIN as PIN,
	HEADT.TAX_YEAR,
	DT_CLASS as CLASS,
	LEFT(HD_TOWN, 2) as TOWN_CODE,
	HD_NBHD AS NBHD,
	HD_HD_SF AS HD_SF,
	(HD_PRI_LND) * 10 as PRI_EST_LAND,
	(HD_PRI_BLD) * 10 as PRI_EST_BLDG,

	/* Assign properties to modeling groups*/
	CASE WHEN DETAILT.DT_CLASS IN (200, 201, 241) OR (DETAILT.DT_CLASS IN (299, 399) AND (DT_CDU != 'GR' OR DT_CDU IS NULL) AND (HD_PRI_BLD + HD_PRI_LND) NOT BETWEEN 1 AND 3000) THEN 'NCHARS'
		 WHEN DETAILT.DT_CLASS IN (202, 203, 204, 205, 206, 207, 208, 209, 210, 234, 278, 295) THEN 'SF'
		 WHEN DETAILT.DT_CLASS IN (211, 212) THEN 'MF'
		 WHEN DETAILT.DT_CLASS IN (299, 399) AND (DT_CDU = 'GR' OR (HD_PRI_BLD + HD_PRI_LND) BETWEEN 1 AND 3000) THEN 'FIXED'
		 ELSE NULL 
		 END AS MODELING_GROUP,

	/* Fields from AS_DETAILT */
	/* The PER_ASS field is equal to 0 when the proration rate is 100%, and is > 0 all other times */
	DT_AGE AS AGE,
	DT_MLT_CD,
	CASE WHEN DT_PER_ASS = 0 THEN 1
	     ELSE DT_PER_ASS
		 END AS DT_PER_ASS,
	CASE WHEN DT_CDU = '' THEN NULL
	     ELSE DT_CDU
		 END AS CDU,
	CASE WHEN DT_KEY_PIN != 0 THEN RIGHT('0' + CAST(DT_KEY_PIN AS VARCHAR), 14)
		 ELSE NULL 
		 END AS DT_KEY_PIN,

	/* Constructed condominium strata */
	condo_strata_10 AS CONDO_STRATA_10,
	condo_strata_100 AS CONDO_STRATA_100,

	/* Fields from CCAOSFCHARS */
	APTS, EXT_WALL, ROOF_CNST, ROOMS, BEDS, BSMT, BSMT_FIN, HEAT, OHEAT,
	AIR, FRPL, ATTIC_TYPE, FBATH, HBATH, TP_PLAN, TP_DSGN, CNST_QLTY, [SITE],
	GAR1_SIZE, GAR1_CNST, GAR1_ATT, GAR1_AREA, GAR2_SIZE, GAR2_CNST, GAR2_ATT,
	GAR2_AREA, OT_IMPR, BLDG_SF, REPAIR_CND, MULTI_CODE, VOLUME, NCU, [USE],

	/* Fix fields from CCAOSFCHARS for which NULL is recorded as 0 in AS400 */
	CASE WHEN TYPE_RESD = 0 THEN NULL
		 ELSE TYPE_RESD 
		 END AS TYPE_RESD,
	CASE WHEN ATTIC_FNSH = 0 THEN NULL
		 ELSE ATTIC_FNSH 
		 END AS ATTIC_FNSH,
	CASE WHEN RENOVATION = 0 THEN NULL
		 ELSE RENOVATION 
		 END AS RENOVATION,
	CASE WHEN PORCH = 0 THEN NULL
		 ELSE PORCH
		 END AS PORCH,
	CASE WHEN MULTI_IND IS NULL THEN 0
		 ELSE MULTI_IND 
		 END AS MULTI_IND,

	/* Fields from TAXBILLAMOUNTS */
	HD_TOWN AS TAX_CD,
	TB_TAX_RATE AS TAX_RATE,
	TB_AMT_TAX_PAID AS TAX_AMT_PAID

/* The AS_HEADT file defines the universe of PINs that could have a sale associated with them. 
This includes properties without characteristics data such as 211, 212, and 299s */
FROM AS_HEADT AS HEADT

/* Get the proper characteristics data from each year for each class by merging AS_DETAILT and CCAOSFCHARS */
LEFT JOIN (
	SELECT
		T.PIN,
		T.TAX_YEAR,
		DT_CLASS,
		DT_MLT_CD,
		DT_PER_ASS,
		DT_CDU,
		DT_AGE,
		DT_KEY_PIN,
		APTS, EXT_WALL, ROOF_CNST, ROOMS, BEDS, BSMT, BSMT_FIN, HEAT, OHEAT, AIR, FRPL, ATTIC_TYPE, FBATH, HBATH,
		TP_PLAN, TP_DSGN, CNST_QLTY, [SITE], GAR1_SIZE, GAR1_CNST, GAR1_ATT, GAR1_AREA, GAR2_SIZE, GAR2_CNST, GAR2_ATT,
		GAR2_AREA, OT_IMPR, BLDG_SF, REPAIR_CND, MULTI_CODE, VOLUME, NCU, TYPE_RESD, ATTIC_FNSH, RENOVATION, PORCH,
		MULTI_IND, AGE, [USE]
	FROM AS_DETAILT T
	LEFT JOIN CCAOSFCHARS CH 
		ON T.PIN = CH.PIN 
		AND T.TAX_YEAR = CH.TAX_YEAR 
		AND T.DT_MLT_CD = CH.MULTI_CODE
	WHERE RIGHT(DT_CLASS, 2) NOT IN ('00', '01', '41', '88')
) AS DETAILT
ON HEADT.PIN = DETAILT.PIN 
AND HEADT.TAX_YEAR = DETAILT.TAX_YEAR

/* Allows us to model condos within strata */
LEFT JOIN DTBL_CONDOSTRATA AS STRATA
ON LEFT(HEADT.PIN, 10) = STRATA.PIN10 
AND HEADT.TAX_YEAR = STRATA.ASSESSMENT_YEAR

/* Add effective tax rates and tax codes. Max is used here to remove the
very occasional duplicated PIN and TAX_YEAR unique combo*/
LEFT JOIN (
	SELECT 
		PIN,
		TAX_YEAR, 
		MAX(TB_AMT_TAX_PAID) AS TB_AMT_TAX_PAID, 
		MAX(TB_TAX_RATE) AS TB_TAX_RATE
	FROM TAXBILLAMOUNTS
	GROUP BY PIN, TAX_YEAR
) AS TBA
ON TBA.PIN = HEADT.PIN 
AND TBA.TAX_YEAR + 1 = HEADT.TAX_YEAR

/* Excludes properties with a pending inspection */
LEFT JOIN (
	SELECT 
		PIN, 
		TAX_YEAR
	FROM PERMITTRACKING
	WHERE COMP_RECV = 0
) AS PERMITS
ON PERMITS.PIN = HEADT.PIN AND PERMITS.TAX_YEAR = HEADT.TAX_YEAR
WHERE PERMITS.PIN IS NULL

/* Limit sample to residential parcels */
AND DT_CLASS IN (
	200, 201, 202, 203, 204, 205, 206, 207, 208,
	209, 210, 211, 212, 234, 241, 278, 295, 299, 399
)