SELECT EM_NAME as [Employee], X.Month, X.[Desk Reviews], X.PINs FROM (

	SELECT [Employee ID], RIGHT(A.MONTH,2) AS Month, [Desk Reviews], PINs
	, [Desk Reviews]/PINs as [Percent of PINs]
	FROM (
		SELECT COUNT(DISTINCT LEFT(D65_PIN, 10)) AS [Desk Reviews]
		, D65_EMPID as [Employee ID]
		, LEFT(D65_DATECHG, 4) AS MONTH
		FROM [65D] WHERE TAX_YEAR=2020 AND D65_EMPID!=0
		GROUP BY D65_EMPID, LEFT(D65_DATECHG, 4)
	) AS A
	INNER JOIN  
	(
		SELECT COUNT(DISTINCT LEFT(D65_PIN, 10)) AS [PINs]
		, LEFT(D65_DATECHG, 4) AS MONTH
		FROM [65D] AS D WHERE TAX_YEAR=2020 AND D65_EMPID!=0
		GROUP BY LEFT(D65_DATECHG, 4)
	) AS B
	ON A.MONTH=B.MONTH
) AS X
INNER JOIN (SELECT DISTINCT EM_ID,EM_NAME FROM AS400_DKEMPL) AS DK
ON DK.EM_ID=X.[Employee ID] 

ORDER BY [Employee ID], MONTH