/* This view produces JSON data for TruRoll */

ALTER VIEW VW_TRUEROLL_2 AS

SELECT PIN, [KEY PIN]
, CONCAT(IND1, ', ', IND2, ', ', IND3, ', ', IND4, ', ', IND5, ', ', IND6, ', ', IND7, ', ', IND8, ', ', IND9, ', ', IND10) AS exemption_years
FROM(
SELECT T.PIN
, CASE WHEN E1.PIN IS NULL THEN CONCAT('[', Year(GetDate())-1, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-1, ':TRUE]') END AS IND1
, CASE WHEN E2.PIN IS NULL THEN CONCAT('[', Year(GetDate())-2, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-2, ':TRUE]') END AS IND2
, CASE WHEN E3.PIN IS NULL THEN CONCAT('[', Year(GetDate())-3, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-3, ':TRUE]') END AS IND3
, CASE WHEN E4.PIN IS NULL THEN CONCAT('[', Year(GetDate())-4, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-4, ':TRUE]') END AS IND4
, CASE WHEN E5.PIN IS NULL THEN CONCAT('[', Year(GetDate())-5, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-5, ':TRUE]') END AS IND5
, CASE WHEN E6.PIN IS NULL THEN CONCAT('[', Year(GetDate())-6, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-6, ':TRUE]') END AS IND6
, CASE WHEN E7.PIN IS NULL THEN CONCAT('[', Year(GetDate())-7, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-7, ':TRUE]') END AS IND7
, CASE WHEN E8.PIN IS NULL THEN CONCAT('[', Year(GetDate())-8, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-8, ':TRUE]') END AS IND8
, CASE WHEN E9.PIN IS NULL THEN CONCAT('[', Year(GetDate())-9, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-9, ':TRUE]') END AS IND9
, CASE WHEN E10.PIN IS NULL THEN CONCAT('[', Year(GetDate())-10, ':FALSE]') ELSE CONCAT('[', Year(GetDate())-10, ':TRUE]') END AS IND10
FROM 
(SELECT DISTINCT TAX_YEAR, PIN 
FROM AS_HEADT 
WHERE HD_CLASS IN (202, 203, 204, 205, 206, 207, 208, 209, 210, 234, 278, 295, 299, 211, 212)
AND TAX_YEAR>=Year(GetDate())-10) AS T 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-1) AS E1 ON T.PIN=E1.PIN 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-2) AS E2 ON T.PIN=E2.PIN 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-3) AS E3 ON T.PIN=E3.PIN 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-4) AS E4 ON T.PIN=E4.PIN 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-5) AS E5 ON T.PIN=E5.PIN 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-6) AS E6 ON T.PIN=E6.PIN 
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-7) AS E7 ON T.PIN=E7.PIN
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-8) AS E8 ON T.PIN=E8.PIN
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-9) AS E9 ON T.PIN=E9.PIN
LEFT JOIN (SELECT PIN FROM EXEMPTIONS WHERE TAX_YEAR=Year(GetDate())-10) AS E10 ON T.PIN=E10.PIN
INNER JOIN
		(SELECT PIN, CASE WHEN DT_KEY_PIN=0 THEN NULL ELSE DT_KEY_PIN END AS [KEY PIN] , TAX_YEAR
			FROM AS_DETAILT 
			WHERE LEFT(DT_CLASS,1)=2 AND DT_CLASS NOT IN (200, 288) AND TAX_YEAR=2018 AND DT_MLT_CD=1
			) AS KEYPINS
ON T.PIN=KEYPINS.PIN AND T.TAX_YEAR=KEYPINS.TAX_YEAR
) AS X 
FOR JSON PATH, ROOT('exemption_years')