---
title: "Test"
author: "Damon"
date: "2024-04-30"
output: html_document
---
```{r}
library(noctua)
library(dplyr)
```


```{r}
con <- dbConnect(noctua::athena())

query <- "SELECT tot30, parid, taxyr FROM iasworld.asmt_all WHERE taxyr = '2023'"

result <- dbGetQuery(con, query)

result <- result %>%
  arrange(-tot30)

result1a <- result %>%
  filter(tot30 > 0)

result1b <- result %>%
  filter(tot30 == 0)

query <- "SELECT * FROM iasworld.addn WHERE taxyr = '2023'"

result2 <-  dbGetQuery(con, query)

result3 <- left_join(result1a, result2, by = "parid")

result3b <- left_join(result1b, result2, by = "parid")

result4 <- result3 %>%
  select(parid, tot30, first, second, third, value)
```
```{r}
query <- "SELECT parid, card, mgfa, sfla, flr1area, adjarea FROM iasworld.dweldat WHERE taxyr = '2023'"

dweldat_2023 <- dbGetQuery(con, query)

query <- "SELECT parid, card, mgfa, sfla, flr1area, adjarea FROM iasworld.dweldat WHERE taxyr = '2018'"

dweldat_2018 <- dbGetQuery(con, query)

dweldat <- inner_join(dweldat_2023, dweldat_2018, by = "parid", "card")
```

```{r}
test <- left_join(result1a, dweldat, by = "parid")
testb <- left_join(result1b, dweldat, by = "parid")

```

