version: 2

models:
  - name: vw_pin_history_test
    description: '{{ doc("vw_pin_history_test") }}'
    tests:
      # Unique by 14-digit PIN and year
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - pin
            - year
  - name: vw_pin_value_test
    description: '{{ doc("vw_pin_value_test") }}'
    tests:
      # Unique by 14-digit PIN and year
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - pin
            - year
      # Missing test here: "values match what's in whatever iasworld view
      # feeds our website
  - name: vw_pin_appeal_test
    description: '{{ doc("vw_pin_appeal_test") }}'
    tests:
      - dbt_utils.unique_combination_of_columns:
          name: unique_by_14_digit_pin_and_year
          combination_of_columns:
            - pin
            - year
      - dbt_utils.unique_combination_of_columns:
          name: unique_by_case_number_and_year
          combination_of_columns:
            - year
            - case_no
      - dbt_utils.expression_is_true:
          name: no_unexpected_change_values
          expression: change is null or change in ('change', 'no change')
      - dbt_utils.expression_is_true:
          name: change_matches_appeal_outcome
          expression: >-
            (change = 'no change' AND
              (mailed_bldg, mailed_land, mailed_tot)
              =
              (certified_bldg, certified_land, certified_tot)
            )
            OR
            (change = 'change' AND
              (mailed_bldg, mailed_land, mailed_tot)
              !=
              (certified_bldg, certified_land, certified_tot)
            )
            OR
            (change is null)
  # TODO: Tests for these models
  - name: vw_card_res_char_test
    description: '{{ doc("vw_card_res_char_test") }}'
  - name: vw_pin_address_test
    description: '{{ doc("vw_pin_address_test") }}'
  - name: vw_pin_condo_char_test
    description: '{{ doc("vw_pin_condo_char_test") }}'
  - name: vw_pin_sale_test
    description: '{{ doc("vw_pin_sale_test") }}'
  - name: vw_pin_universe_test
    description: '{{ doc("vw_pin_universe_test") }}'

