seeds:
  - name: model.final_model_raw
    description: '{{ doc("seed_final_model_raw") }}'
    tags:
      - load_manual
    data_tests:
      - accepted_values:
          name: model_final_model_triad_name_accepted_values
          column_name: triad_name
          values:
            - City
            - North
            - South
          meta:
            description: Accepted values for triad name
      - unique_combination_of_columns:
          name: model_final_model_unique_by_run_id
          combination_of_columns:
            - run_id
          meta:
            description: Final model is unique by run_id
      - unique_combination_of_columns:
          name: model_final_model_unique_by_year_type_is_final
          combination_of_columns:
            - is_final
            - type
            - year
          meta:
            description: Final model is unique by year, type and is_final
    config:
      column_types:
        year: string
