seeds:
  - name: ccao.adjective
    description: '{{ doc("seed_adjective") }}'

  - name: ccao.aprval_reascd
    description: '{{ doc("seed_aprval_reascd") }}'
    config:
      column_types:
        reascd: string
        description: string

  - name: ccao.cdu
    description: '{{ doc("seed_cdu") }}'
    config:
      column_types:
        cdu_code: string
        cdu_description: string

  - name: ccao.class_dict
    description: '{{ doc("seed_class_dict") }}'
    config:
      column_types:
        min_age: double
        max_age: double
        min_size: double
        max_size: double

    columns:
      - name: class_code
        description: Full, 3-digit class code of the property sub-class
      - name: class_desc
        description: Human-readable description of the property sub-class
      - name: major_class_code
        description: First digit of class code, major class
      - name: major_class_type
        description: Human-readable description of the major class
      - name: max_age
        description: Double of maximum age for 200-class property codes
      - name: max_size
        description: Double of maximum size for 200-class property codes
      - name: min_age
        description: Double of minimum age for 200-class property codes
      - name: min_size
        description: Double of minimum size for 200-class property codes
      - name: modeling_group
        description: Modeling group used for internal CCAO data selection
      - name: regression_class
        description: Boolean indicating whether or not this class isincluded in CAMA regressions
      - name: reporting_group
        description: Reporting group name used for internal CCAO reports and aggregate statistics

  - name: ccao.commercial_model_group
    description: '{{ doc("seed_commercial_model_group") }}'
    config:
      column_types:
        code: string
        description: string
    data_tests:
      - unique_combination_of_columns:
          name: ccao_commercial_model_group_unique_by_code
          combination_of_columns:
            - code

  - name: ccao.commercial_major_subclass
    description: '{{ doc("seed_commercial_major_subclass") }}'
    config:
      column_types:
        code: string
        description: string

  - name: ccao.commercial_minor_subclass
    description: '{{ doc("seed_commercial_minor_subclass") }}'
    config:
      column_types:
        code: string
        description: string

  - name: ccao.infl_reascd
    description: '{{ doc("seed_infl_reascd") }}'
    config:
      column_types:
        reascd: string
        description: string

  - name: ccao.loa
    description: '{{ doc("seed_loa") }}'
    config:
      column_types:
        year: string
        class_code: string

    columns:
      - name: class_code
        description: '{{ doc("shared_column_class") }}'
      - name: loa
        description: |
          Level of Assessment (LoA) for each year and property class. This
          number is effectively the percentage of market/fair cash value on
          which properties are assessed
        data_tests:
          - accepted_range:
              name: loa_less_than_38
              max_value: .38
              meta:
                description: loa should be less than .38
      - name: year
        description: '{{ doc("shared_column_year") }}'

  - name: ccao.person
    description: '{{ doc("seed_person") }}'

    columns:
      - name: person
        description: Name of a former CCAO intern, fellow, or employee
      - name: type
        description: |
          Type, one of: fte, intern, fellow

  - name: ccao.pin_test
    description: '{{ doc("seed_pin_test") }}'
    config:
      column_types:
        class: string
        pin: string
        township_code: string
        triad_code: string
        year: string

    columns:
      - name: class
        description: '{{ doc("shared_column_class") }}'
      - name: description
        description: |
          Short description of the issue, use, or situation with this PIN
      - name: is_test
        description: |
          Boolean for whether or not the PIN is useful for integration testing
      - name: pin
        description: '{{ doc("shared_column_pin") }}'
      - name: test_type
        description: Type of integration test this PIN is useful for
      - name: township_code
        description: '{{ doc("shared_column_township_code") }}'
      - name: triad_code
        description: '{{ doc("shared_column_triad_code") }}'
      - name: year
        description: '{{ doc("shared_column_year") }}'

  - name: ccao.htpar_reascd
    description: '{{ doc("seed_htpar_reascd") }}'
    config:
      column_types:
        description: string
        outcome: string
        reascd: string
