seeds:
  - name: ccao.class_dict
    description: '{{ doc("seed_class_dict") }}'
    config:
      column_types:
        min_age: double
        max_age: double
        min_size: double
        max_size: double
