seeds:
  - name: ccao.adjective
    description: '{{ doc("seed_adjective") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_adjective_unique_by_adjective
        combination_of_columns:
          - adjective
        meta:
          description: adjective is unique by adjective

  - name: ccao.aprval_reascd
    description: '{{ doc("seed_aprval_reascd") }}'
    config:
      column_types:
        reascd: string
        description: string

  - name: ccao.cdu
    description: '{{ doc("seed_cdu") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_cdu_unique_by_cdu_code
        combination_of_columns:
          - cdu_code
        meta:
          description: cdu is unique by cdu_code
    config:
      column_types:
        cdu_code: string
        cdu_description: string

  - name: ccao.class_dict
    description: '{{ doc("seed_class_dict") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_class_dict_unique_by_class_code
        combination_of_columns:
          - class_code
        meta:
          description: class_dict is unique by class_code
    config:
      column_types:
        min_age: double
        max_age: double
        min_size: double
        max_size: double

    columns:
      - name: class_code
        description: Full, 3-digit class code of the property sub-class
      - name: class_desc
        description: Human-readable description of the property sub-class
      - name: major_class_code
        description: First digit of class code, major class
      - name: major_class_type
        description: Human-readable description of the major class
      - name: max_age
        description: Double of maximum age for 200-class property codes
      - name: max_size
        description: Double of maximum size for 200-class property codes
      - name: min_age
        description: Double of minimum age for 200-class property codes
      - name: min_size
        description: Double of minimum size for 200-class property codes
      - name: modeling_group
        description: Modeling group used for internal CCAO data selection
      - name: regression_class
        description: Boolean indicating whether or not this class isincluded in CAMA regressions
      - name: reporting_group
        description: Reporting group name used for internal CCAO reports and aggregate statistics

  - name: ccao.commercial_major_subclass
    description: '{{ doc("seed_commercial_major_subclass") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_commercial_major_subclass_unique_by_code
        combination_of_columns:
          - code
        meta:
          description: commercial_major_subclass is unique by code
    config:
      column_types:
        code: string
        description: string

  - name: ccao.commercial_minor_subclass
    description: '{{ doc("seed_commercial_minor_subclass") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_commercial_minor_subclass_unique_by_code
        combination_of_columns:
          - code
        meta:
          description: commercial_minor_subclass is unique by code
    config:
      column_types:
        code: string
        description: string

  - name: ccao.infl_reascd
    description: '{{ doc("seed_infl_reascd") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_infl_reascd_unique_by_reascd
        combination_of_columns:
          - reascd
        meta:
          description: infl_reascd is unique by reascd
    config:
      column_types:
        reascd: string
        description: string

  - name: ccao.loa
    description: '{{ doc("seed_loa") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_loa_unique_by_year_class_code
        combination_of_columns:
          - year
          - class_code
        meta:
          description: loa is unique by year and class_code
    config:
      column_types:
        year: string
        class_code: string

    columns:
      - name: class_code
        description: '{{ doc("shared_column_class") }}'
      - name: loa
        description: |
          Level of Assessment (LoA) for each year and property class. This
          number is effectively the percentage of market/fair cash value on
          which properties are assessed
        data_tests:
          - accepted_range:
              name: loa_less_than_38
              max_value: .38
              meta:
                description: loa should be less than .38
      - name: year
        description: '{{ doc("shared_column_year") }}'

  - name: ccao.person
    description: '{{ doc("seed_person") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_person_unique_by_person
        combination_of_columns:
          - person
          - type
        meta:
          description: person is unique by person and type

    columns:
      - name: person
        description: Name of a former CCAO intern, fellow, or employee
      - name: type
        description: |
          Type, one of: fte, intern, fellow

  - name: ccao.pin_test
    description: '{{ doc("seed_pin_test") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_pin_test_unique_by_year_pin
        combination_of_columns:
          - year
          - pin
        meta:
          description: pin_test is unique by year and pin
    config:
      column_types:
        class: string
        pin: string
        township_code: string
        triad_code: string
        year: string

    columns:
      - name: class
        description: '{{ doc("shared_column_class") }}'
      - name: description
        description: |
          Short description of the issue, use, or situation with this PIN
      - name: is_test
        description: |
          Boolean for whether or not the PIN is useful for integration testing
      - name: pin
        description: '{{ doc("shared_column_pin") }}'
      - name: test_type
        description: Type of integration test this PIN is useful for
        data_tests:
          - accepted_values:
              name: ccao_pin_test_test_type_accepted_values
              values:
                - class_change
                - incorrect_char
                - just_weird
                - multi_card
                - multi_card_prorated
                - omitted_assessment
                - prorated
                - split_class
      - name: township_code
        description: '{{ doc("shared_column_township_code") }}'
      - name: triad_code
        description: '{{ doc("shared_column_triad_code") }}'
      - name: year
        description: '{{ doc("shared_column_year") }}'

  - name: ccao.htpar_reascd
    description: '{{ doc("seed_htpar_reascd") }}'
    data_tests:
    - unique_combination_of_columns:
        name: ccao_htpar_reascd_unique_by_reascd
        combination_of_columns:
          - reascd
        meta:
          description: htpar_reascd is unique by reascd
    config:
      column_types:
        description: string
        outcome: string
        reascd: string
