flowchart LR
    A[(MyDec)] -->|Via DS + SP| B[AS/400 + Mainframe]
    A --> |Sales after Feb. 2021<br>via DS + MV| C[(iasworld.sales)]
    B --> |Sales before<br>Feb. 2021| C
    A --> |Via Data. Dept.<br> direct import| D[(sale.mydec)]
    D --> |Used to fill<br>missing data| E[default.vw_pin_sale]
    C --> |Default source| E
