sources:
  - name: spatial
    tags:
      - load_manual
    tables:
      - name: bike_trail
        description: '{{ doc("table_bike_trail") }}'

      - name: board_of_review_district
        description: '{{ doc("table_board_of_review_district") }}'

      - name: building_footprint
        description: '{{ doc("table_building_footprint") }}'

      - name: cemetery
        description: '{{ doc("table_cemetery") }}'

      - name: census
        description: '{{ doc("table_spatial_census") }}'

      - name: central_business_district
        description: '{{ doc("table_spatial_central_business_district") }}'

      - name: coastline
        description: '{{ doc("table_coastline") }}'

      - name: commissioner_district
        description: '{{ doc("table_commissioner_district") }}'

      - name: community_area
        description: '{{ doc("table_community_area") }}'

      - name: community_college_district
        description: '{{ doc("table_community_college_district") }}'

      - name: congressional_district
        description: '{{ doc("table_congressional_district") }}'

      - name: coordinated_care
        description: '{{ doc("table_coordinated_care") }}'

      - name: corner
        description: '{{ doc("table_corner") }}'
        data_tests:
        - unique_combination_of_columns:
            name: spatial_corner_unique_by_pin10_year
            combination_of_columns:
              - pin10
              - year
            meta:
              description: corner unique by pin10 and year
        columns:
          - name: geometry
            description: |
              Well-Known Binary (WKB) geometry (EPSG 4326) representation of
              the remaining arms of the cross used in the corner detection
              algorithm
          - name: geometry_3435
            description: |
              Well-Known Binary (WKB) geometry (EPSG 3435) representation of
              the remaining arms of the cross used in the corner detection
              algorithm
          - name: is_corner_lot
            description: '{{ doc("shared_column_is_corner_lot") }}'
          - name: num_cross_branch
            description: |
              The number of remaining branches of the cross used to detect
              whether the corner is a parcel. See table description for
              details
          - name: pin10
            description: '{{ doc("shared_column_pin10") }}'
          - name: township_code
            description: '{{ doc("shared_column_township_code") }}'
          - name: year
            description: '{{ doc("shared_column_year") }}'

      - name: county
        description: '{{ doc("table_county") }}'

      - name: enterprise_zone
        description: '{{ doc("table_enterprise_zone") }}'

      - name: fire_protection_district
        description: '{{ doc("table_fire_protection_district") }}'

      - name: flood_fema
        description: '{{ doc("table_flood_fema") }}'

      - name: geojson
        description: '{{ doc("table_geojson") }}'

      - name: golf_course
        description: '{{ doc("table_golf_course") }}'

      - name: grocery_store
        description: '{{ doc("table_grocery_store") }}'

      - name: hospital
        description: '{{ doc("table_hospital") }}'

      - name: hydrology
        description: '{{ doc("table_hydrology") }}'

      - name: industrial_corridor
        description: '{{ doc("table_industrial_corridor") }}'

      - name: industrial_growth_zone
        description: '{{ doc("table_industrial_growth_zone") }}'

      - name: judicial_district
        description: '{{ doc("table_judicial_district") }}'

      - name: library_district
        description: '{{ doc("table_library_district") }}'

      - name: major_road
        description: '{{ doc("table_major_road") }}'

      - name: midway_noise_monitor
        description: '{{ doc("table_midway_noise_monitor") }}'

      - name: municipality
        description: '{{ doc("table_municipality") }}'

      - name: neighborhood
        description: '{{ doc("table_neighborhood") }}'

      - name: ohare_noise_contour
        description: '{{ doc("table_ohare_noise_contour") }}'

      - name: ohare_noise_monitor
        description: '{{ doc("table_ohare_noise_monitor") }}'

      - name: parcel
        description: '{{ doc("table_parcel") }}'
        columns:
          - name: source
            description: |
              Column denoting if the parcel's geography was derived from Cook County GIS `raw`,
              `imputed` (using a previous or future year of the same parcel), or
              `geocoded` with tidygeocoder.
      - name: park
        description: '{{ doc("table_park") }}'

      - name: park_district
        description: '{{ doc("table_park_district") }}'

      - name: police_district
        description: '{{ doc("table_police_district") }}'

      - name: qualified_opportunity_zone
        description: '{{ doc("table_qualified_opportunity_zone") }}'

      - name: railroad
        description: '{{ doc("table_railroad") }}'

      - name: road
        description: '{{ doc("table_road") }}'

      - name: sanitation_district
        description: '{{ doc("table_sanitation_district") }}'

      - name: school_district
        description: '{{ doc("table_school_district") }}'

      - name: school_location
        description: '{{ doc("table_school_location") }}'

      - name: secondary_road
        description: '{{ doc("table_secondary_road") }}'

      - name: sidwell_grid
        description: '{{ doc("table_sidwell_grid") }}'

      - name: special_service_area
        description: '{{ doc("table_special_service_area") }}'

      - name: stadium
        description: '{{ doc("table_stadium") }}'

      - name: state_representative_district
        description: '{{ doc("table_state_representative_district") }}'

      - name: state_senate_district
        description: '{{ doc("table_state_senate_district") }}'

      - name: subdivision
        description: '{{ doc("table_subdivision") }}'

      - name: tif_district
        description: '{{ doc("table_tif_district") }}'

      - name: township
        description: '{{ doc("table_township") }}'

      - name: transit_dict
        description: '{{ doc("table_transit_dict") }}'

      - name: transit_route
        description: '{{ doc("table_transit_route") }}'

      - name: transit_stop
        description: '{{ doc("table_transit_stop") }}'

      - name: walkability
        description: '{{ doc("table_walkability") }}'

      - name: ward
        description: '{{ doc("table_ward") }}'

      - name: ward_chicago
        description: '{{ doc("table_ward_chicago") }}'

      - name: ward_evanston
        description: '{{ doc("table_ward_evanston") }}'
