version: 2


models:
  - name: spatial.bike_trail
  - name: spatial.board_of_review_district
  - name: spatial.building_footprint
  - name: spatial.cemetery
  - name: spatial.census
  - name: spatial.coastline
  - name: spatial.commissioner_district
  - name: spatial.community_area
  - name: spatial.community_college_district
  - name: spatial.congressional_district
  - name: spatial.coordinated_care
  - name: spatial.county
  - name: spatial.enterprize_zone
  - name: spatial.fire_protection_district
  - name: spatial.flood_fema
  - name: spatial.geojson
  - name: spatial.golf_course
  - name: spatial.hospital
  - name: spatial.hydrology
  - name: spatial.industrial_corridor
  - name: spatial.industrial_growth_zone
  - name: spatial.judicial_district
  - name: spatial.library_district
  - name: spatial.major_road
  - name: spatial.midway_noise_monitor
  - name: spatial.municipality
  - name: spatial.neighborhood
  - name: spatial.ohare_noise_contour
  - name: spatial.ohare_noise_monitor
  - name: spatial.parcel
  - name: spatial.park
  - name: spatial.park_district
  - name: spatial.police_district
  - name: spatial.qualified_opportunity_zone
  - name: spatial.railroad
  - name: spatial.sanitation_district
  - name: spatial.school_district
  - name: spatial.school_location
  - name: spatial.special_service_area
  - name: spatial.state_representative_district
  - name: spatial.state_senate_district
  - name: spatial.subdivision
  - name: spatial.tif_district
  - name: spatial.township
  - name: spatial.transit_dict
  - name: spatial.transit_route
  - name: spatial.transit_stop
  - name: spatial.walkability
  - name: spatial.ward
  - name: spatial.ward_chicago
  - name: spatial.ward_evanston
