library(stringr)
library(tidycensus)
library(dplyr)
library(purrr)
library(openxlsx)
library(arrow)
library(here)
library(sf)
library(here)
library(rvest)
library(janitor)
library(odbc)
library(DBI)

# retrieve raw census data
source(here("scripts/stable-census-acs.R"))
source(here("scripts/stable-census-decennial.R"))
source(here("scripts/stable-housing-ihs.R"))
source(here("scripts/rpie-tables.R"))
