sources:
  - name: rpie
    tags:
      - load_manual
    tables:
      - name: pin_codes
      - name: pin_codes_dummy

models:
  - name: rpie.vw_code_retrieval
  - name: rpie.vw_pin_flatfile
  - name: rpie.vw_pin_mailers
