version: 2


models:
  - name: tax.agency
  - name: tax.agency_fund
  - name: tax.agency_fund_info
  - name: tax.agency_info
  - name: tax.cpi
  - name: tax.eq_factor
  - name: tax.pin
  - name: tax.pin_geometry_raw
  - name: tax.tax_code
  - name: tax.tif
  - name: tax.tif_crosswalk
  - name: tax.tif_distribution
