sources:
  - name: tax
    tags:
      - load_manual
    tables:
      - name: agency
        description: '{{ doc("table_agency") }}'

      - name: agency_fund
        description: '{{ doc("table_agency_fund") }}'

      - name: agency_fund_info
        description: '{{ doc("table_agency_fund_info") }}'

      - name: agency_info
        description: '{{ doc("table_agency_info") }}'

      - name: cpi
        description: '{{ doc("table_cpi") }}'

      - name: eq_factor
        description: '{{ doc("table_eq_factor") }}'

      - name: pin
        description: '{{ doc("table_pin") }}'
        columns:
          - name: class
            description: '{{ doc("shared_column_char_class")}}'
            data_tests:
              - relationships:
                  name: tax_pin_all_class_in_ccao_class_dict
                  to: ref('ccao.class_dict')
                  field: class_code
                  additional_select_columns: &select-columns
                    - year
                  config:
                    where:
                      CAST(year AS int) BETWEEN {{ var('data_test_iasworld_year_start') }} AND {{ var('data_test_iasworld_year_end') }}
                  meta:
                    category: class_mismatch_or_issue
                    description: class code must be valid
              - res_class_matches_pardat:
                  name: tax_pin_class_equals_iasworld_pardat
                  parid_column_name: pin
                  taxyr_column_name: year
                  additional_select_columns:
                    - agg_func: max
                      column: year
                  config:
                    where:
                      CAST(year AS int) BETWEEN {{ var('data_test_iasworld_year_start') }} AND {{ var('data_test_iasworld_year_end') }}
                  meta:
                    description: at least one class should match pardat class

          - name: tax_code_num
            description: '{{ doc("shared_column_tax_code")}}'
            data_tests:
              - row_values_match_after_join:
                  name: pin_tax_dist_matches_iasworld_legdat
                  external_model: source('iasworld', 'legdat')
                  external_column_name: taxdist
                  column_alias: tax_code_num
                  external_column_alias: taxdist
                  group_by:
                    - year
                    - pin
                  join_condition:
                    ON  model.pin = external_model.parid
                    AND model.year = external_model.taxyr
                    AND external_model.cur = 'Y'
                    AND external_model.deactivat IS NULL
                  config:
                    where:
                      CAST(year AS int) BETWEEN {{ var('data_test_iasworld_year_start') }} AND {{ var('data_test_iasworld_year_end') }}
                    severity: warn
                  meta:
                    description: tax_code_num should match legdat.taxdist

      - name: pin_geometry_raw
        description: '{{ doc("table_pin_geometry_raw") }}'

      - name: tax_code
        description: '{{ doc("table_tax_code") }}'

      - name: tif
        description: '{{ doc("table_tif") }}'

      - name: tif_crosswalk
        description: '{{ doc("table_tif_crosswalk") }}'

      - name: tif_distribution
        description: '{{ doc("table_tif_distribution") }}'
