CREATE OR REPLACE VIEW model.vw_card_shap_long AS
WITH features AS (
    SELECT
        a1.meta_year,
        a1.meta_pin,
        a1.meta_card_num,
        a1.meta_class,
        a1.year,
        a1.run_id,
        a1.township_code,
        a2.feature_name,
        a2.feature_value
    FROM
        model.assessment_card a1
    CROSS JOIN
    unnest(
    array[
        'meta_township_code',
        'meta_nbhd_code',
        'meta_tieback_proration_rate',
        'ind_pin_is_multicard',
        'char_yrblt',
        'char_bldg_sf',
        'char_land_sf',
        'char_beds',
        'char_rooms',
        'char_fbath',
        'char_hbath',
        'char_frpl',
        'char_type_resd',
        'char_apts',
        'char_tp_dsgn',
        'char_attic_fnsh',
        'char_gar1_att',
        'char_gar1_area',
        'char_gar1_size',
        'char_gar1_cnst',
        'char_attic_type',
        'char_bsmt',
        'char_ext_wall',
        'char_heat',
        'char_bsmt_fin',
        'char_roof_cnst',
        'char_use',
        'char_porch',
        'char_air',
        'char_ncu',
        'char_tp_plan',
        'ind_land_gte_95_percentile',
        'ind_bldg_gte_95_percentile',
        'ind_land_bldg_ratio_gte_10',
        'loc_cook_municipality_name',
        'loc_school_elementary_district_geoid',
        'loc_school_secondary_district_geoid',
        'loc_school_unified_district_geoid',
        'loc_tax_special_service_area_num',
        'loc_misc_subdivision_id',
        'loc_misc_unincorporated_area_bool',
        'loc_env_flood_fema_sfha',
        'loc_env_flood_fs_factor',
        'loc_env_flood_fs_risk_direction',
        'loc_env_ohare_noise_contour_no_buffer_bool',
        'loc_access_cmap_walk_nta_score',
        'loc_access_cmap_walk_total_score',
        'prox_num_pin_in_half_mile',
        'prox_num_bus_stop_in_half_mile',
        'prox_num_foreclosure_per_1000_pin_past_5_years',
        'prox_num_school_in_half_mile',
        'prox_num_school_with_rating_in_half_mile',
        'prox_avg_school_rating_in_half_mile',
        'prox_nearest_bike_trail_dist_ft',
        'prox_nearest_cemetery_dist_ft',
        'prox_nearest_cta_route_dist_ft',
        'prox_nearest_cta_stop_dist_ft',
        'prox_nearest_hospital_dist_ft',
        'prox_lake_michigan_dist_ft',
        'prox_nearest_major_road_dist_ft',
        'prox_nearest_metra_route_dist_ft',
        'prox_nearest_metra_stop_dist_ft',
        'prox_nearest_park_dist_ft',
        'prox_nearest_railroad_dist_ft',
        'prox_nearest_water_dist_ft',
        'acs5_percent_age_children',
        'acs5_percent_age_senior',
        'acs5_median_age_total',
        'acs5_percent_mobility_no_move',
        'acs5_percent_mobility_moved_in_county',
        'acs5_percent_mobility_moved_from_other_state',
        'acs5_percent_household_family_married',
        'acs5_percent_household_nonfamily_alone',
        'acs5_percent_education_high_school',
        'acs5_percent_education_bachelor',
        'acs5_percent_education_graduate',
        'acs5_percent_income_below_poverty_level',
        'acs5_median_income_household_past_year',
        'acs5_median_income_per_capita_past_year',
        'acs5_percent_income_household_received_snap_past_year',
        'acs5_percent_employment_unemployed',
        'acs5_median_household_total_occupied_year_built',
        'acs5_median_household_renter_occupied_gross_rent',
        'acs5_median_household_owner_occupied_value',
        'acs5_percent_household_owner_occupied',
        'acs5_percent_household_total_occupied_w_sel_cond',
        'other_ihs_avg_year_index',
        'other_tax_bill_amount_total',
        'other_tax_bill_rate',
        'other_school_district_elementary_avg_rating',
        'other_school_district_secondary_avg_rating',
        'time_sale_year',
        'time_sale_week',
        'time_sale_quarter_of_year',
        'time_sale_week_of_year',
        'time_sale_during_school_year',
        'time_sale_during_holidays'
    ],
    array[
        CAST(meta_township_code AS varchar),
        CAST(meta_nbhd_code AS varchar),
        CAST(meta_tieback_proration_rate AS varchar),
        CAST(ind_pin_is_multicard AS varchar),
        CAST(char_yrblt AS varchar),
        CAST(char_bldg_sf AS varchar),
        CAST(char_land_sf AS varchar),
        CAST(char_beds AS varchar),
        CAST(char_rooms AS varchar),
        CAST(char_fbath AS varchar),
        CAST(char_hbath AS varchar),
        CAST(char_frpl AS varchar),
        CAST(char_type_resd AS varchar),
        CAST(char_apts AS varchar),
        CAST(char_tp_dsgn AS varchar),
        CAST(char_attic_fnsh AS varchar),
        CAST(char_gar1_att AS varchar),
        CAST(char_gar1_area AS varchar),
        CAST(char_gar1_size AS varchar),
        CAST(char_gar1_cnst AS varchar),
        CAST(char_attic_type AS varchar),
        CAST(char_bsmt AS varchar),
        CAST(char_ext_wall AS varchar),
        CAST(char_heat AS varchar),
        CAST(char_bsmt_fin AS varchar),
        CAST(char_roof_cnst AS varchar),
        CAST(char_use AS varchar),
        CAST(char_porch AS varchar),
        CAST(char_air AS varchar),
        CAST(char_ncu AS varchar),
        CAST(char_tp_plan AS varchar),
        CAST(ind_land_gte_95_percentile AS varchar),
        CAST(ind_bldg_gte_95_percentile AS varchar),
        CAST(ind_land_bldg_ratio_gte_10 AS varchar),
        CAST(loc_cook_municipality_name AS varchar),
        CAST(loc_school_elementary_district_geoid AS varchar),
        CAST(loc_school_secondary_district_geoid AS varchar),
        CAST(loc_school_unified_district_geoid AS varchar),
        CAST(loc_tax_special_service_area_num AS varchar),
        CAST(loc_misc_subdivision_id AS varchar),
        CAST(loc_misc_unincorporated_area_bool AS varchar),
        CAST(loc_env_flood_fema_sfha AS varchar),
        CAST(loc_env_flood_fs_factor AS varchar),
        CAST(loc_env_flood_fs_risk_direction AS varchar),
        CAST(loc_env_ohare_noise_contour_no_buffer_bool AS varchar),
        CAST(loc_access_cmap_walk_nta_score AS varchar),
        CAST(loc_access_cmap_walk_total_score AS varchar),
        CAST(prox_num_pin_in_half_mile AS varchar),
        CAST(prox_num_bus_stop_in_half_mile AS varchar),
        CAST(prox_num_foreclosure_per_1000_pin_past_5_years AS varchar),
        CAST(prox_num_school_in_half_mile AS varchar),
        CAST(prox_num_school_with_rating_in_half_mile AS varchar),
        CAST(prox_avg_school_rating_in_half_mile AS varchar),
        CAST(prox_nearest_bike_trail_dist_ft AS varchar),
        CAST(prox_nearest_cemetery_dist_ft AS varchar),
        CAST(prox_nearest_cta_route_dist_ft AS varchar),
        CAST(prox_nearest_cta_stop_dist_ft AS varchar),
        CAST(prox_nearest_hospital_dist_ft AS varchar),
        CAST(prox_lake_michigan_dist_ft AS varchar),
        CAST(prox_nearest_major_road_dist_ft AS varchar),
        CAST(prox_nearest_metra_route_dist_ft AS varchar),
        CAST(prox_nearest_metra_stop_dist_ft AS varchar),
        CAST(prox_nearest_park_dist_ft AS varchar),
        CAST(prox_nearest_railroad_dist_ft AS varchar),
        CAST(prox_nearest_water_dist_ft AS varchar),
        CAST(acs5_percent_age_children AS varchar),
        CAST(acs5_percent_age_senior AS varchar),
        CAST(acs5_median_age_total AS varchar),
        CAST(acs5_percent_mobility_no_move AS varchar),
        CAST(acs5_percent_mobility_moved_in_county AS varchar),
        CAST(acs5_percent_mobility_moved_from_other_state AS varchar),
        CAST(acs5_percent_household_family_married AS varchar),
        CAST(acs5_percent_household_nonfamily_alone AS varchar),
        CAST(acs5_percent_education_high_school AS varchar),
        CAST(acs5_percent_education_bachelor AS varchar),
        CAST(acs5_percent_education_graduate AS varchar),
        CAST(acs5_percent_income_below_poverty_level AS varchar),
        CAST(acs5_median_income_household_past_year AS varchar),
        CAST(acs5_median_income_per_capita_past_year AS varchar),
        CAST(acs5_percent_income_household_received_snap_past_year AS varchar),
        CAST(acs5_percent_employment_unemployed AS varchar),
        CAST(acs5_median_household_total_occupied_year_built AS varchar),
        CAST(acs5_median_household_renter_occupied_gross_rent AS varchar),
        CAST(acs5_median_household_owner_occupied_value AS varchar),
        CAST(acs5_percent_household_owner_occupied AS varchar),
        CAST(acs5_percent_household_total_occupied_w_sel_cond AS varchar),
        CAST(other_ihs_avg_year_index AS varchar),
        CAST(other_tax_bill_amount_total AS varchar),
        CAST(other_tax_bill_rate AS varchar),
        CAST(other_school_district_elementary_avg_rating AS varchar),
        CAST(other_school_district_secondary_avg_rating AS varchar),
        CAST(time_sale_year AS varchar),
        CAST(time_sale_week AS varchar),
        CAST(time_sale_quarter_of_year AS varchar),
        CAST(time_sale_week_of_year AS varchar),
        CAST(time_sale_during_school_year AS varchar),
        CAST(time_sale_during_holidays AS varchar)
    ]) a2 (feature_name, feature_value)
),
shaps AS (
    SELECT
        a1.meta_year,
        a1.meta_pin,
        a1.meta_card_num,
        a1.year,
        a1.run_id,
        a1.township_code,
        a2.feature_name,
        a2.feature_shap
    FROM
        model.shap a1
    CROSS JOIN
    unnest(
    array[
        'meta_township_code',
        'meta_nbhd_code',
        'meta_tieback_proration_rate',
        'ind_pin_is_multicard',
        'char_yrblt',
        'char_bldg_sf',
        'char_land_sf',
        'char_beds',
        'char_rooms',
        'char_fbath',
        'char_hbath',
        'char_frpl',
        'char_type_resd',
        'char_apts',
        'char_tp_dsgn',
        'char_attic_fnsh',
        'char_gar1_att',
        'char_gar1_area',
        'char_gar1_size',
        'char_gar1_cnst',
        'char_attic_type',
        'char_bsmt',
        'char_ext_wall',
        'char_heat',
        'char_bsmt_fin',
        'char_roof_cnst',
        'char_use',
        'char_porch',
        'char_air',
        'char_ncu',
        'char_tp_plan',
        'ind_land_gte_95_percentile',
        'ind_bldg_gte_95_percentile',
        'ind_land_bldg_ratio_gte_10',
        'loc_cook_municipality_name',
        'loc_school_elementary_district_geoid',
        'loc_school_secondary_district_geoid',
        'loc_school_unified_district_geoid',
        'loc_tax_special_service_area_num',
        'loc_misc_subdivision_id',
        'loc_misc_unincorporated_area_bool',
        'loc_env_flood_fema_sfha',
        'loc_env_flood_fs_factor',
        'loc_env_flood_fs_risk_direction',
        'loc_env_ohare_noise_contour_no_buffer_bool',
        'loc_access_cmap_walk_nta_score',
        'loc_access_cmap_walk_total_score',
        'prox_num_pin_in_half_mile',
        'prox_num_bus_stop_in_half_mile',
        'prox_num_foreclosure_per_1000_pin_past_5_years',
        'prox_num_school_in_half_mile',
        'prox_num_school_with_rating_in_half_mile',
        'prox_avg_school_rating_in_half_mile',
        'prox_nearest_bike_trail_dist_ft',
        'prox_nearest_cemetery_dist_ft',
        'prox_nearest_cta_route_dist_ft',
        'prox_nearest_cta_stop_dist_ft',
        'prox_nearest_hospital_dist_ft',
        'prox_lake_michigan_dist_ft',
        'prox_nearest_major_road_dist_ft',
        'prox_nearest_metra_route_dist_ft',
        'prox_nearest_metra_stop_dist_ft',
        'prox_nearest_park_dist_ft',
        'prox_nearest_railroad_dist_ft',
        'prox_nearest_water_dist_ft',
        'acs5_percent_age_children',
        'acs5_percent_age_senior',
        'acs5_median_age_total',
        'acs5_percent_mobility_no_move',
        'acs5_percent_mobility_moved_in_county',
        'acs5_percent_mobility_moved_from_other_state',
        'acs5_percent_household_family_married',
        'acs5_percent_household_nonfamily_alone',
        'acs5_percent_education_high_school',
        'acs5_percent_education_bachelor',
        'acs5_percent_education_graduate',
        'acs5_percent_income_below_poverty_level',
        'acs5_median_income_household_past_year',
        'acs5_median_income_per_capita_past_year',
        'acs5_percent_income_household_received_snap_past_year',
        'acs5_percent_employment_unemployed',
        'acs5_median_household_total_occupied_year_built',
        'acs5_median_household_renter_occupied_gross_rent',
        'acs5_median_household_owner_occupied_value',
        'acs5_percent_household_owner_occupied',
        'acs5_percent_household_total_occupied_w_sel_cond',
        'other_ihs_avg_year_index',
        'other_tax_bill_amount_total',
        'other_tax_bill_rate',
        'other_school_district_elementary_avg_rating',
        'other_school_district_secondary_avg_rating',
        'time_sale_year',
        'time_sale_week',
        'time_sale_quarter_of_year',
        'time_sale_week_of_year',
        'time_sale_during_school_year',
        'time_sale_during_holidays'
    ],
    array[
        meta_township_code,
        meta_nbhd_code,
        meta_tieback_proration_rate,
        ind_pin_is_multicard,
        char_yrblt,
        char_bldg_sf,
        char_land_sf,
        char_beds,
        char_rooms,
        char_fbath,
        char_hbath,
        char_frpl,
        char_type_resd,
        char_apts,
        char_tp_dsgn,
        char_attic_fnsh,
        char_gar1_att,
        char_gar1_area,
        char_gar1_size,
        char_gar1_cnst,
        char_attic_type,
        char_bsmt,
        char_ext_wall,
        char_heat,
        char_bsmt_fin,
        char_roof_cnst,
        char_use,
        char_porch,
        char_air,
        char_ncu,
        char_tp_plan,
        ind_land_gte_95_percentile,
        ind_bldg_gte_95_percentile,
        ind_land_bldg_ratio_gte_10,
        loc_cook_municipality_name,
        loc_school_elementary_district_geoid,
        loc_school_secondary_district_geoid,
        loc_school_unified_district_geoid,
        loc_tax_special_service_area_num,
        loc_misc_subdivision_id,
        loc_misc_unincorporated_area_bool,
        loc_env_flood_fema_sfha,
        loc_env_flood_fs_factor,
        loc_env_flood_fs_risk_direction,
        loc_env_ohare_noise_contour_no_buffer_bool,
        loc_access_cmap_walk_nta_score,
        loc_access_cmap_walk_total_score,
        prox_num_pin_in_half_mile,
        prox_num_bus_stop_in_half_mile,
        prox_num_foreclosure_per_1000_pin_past_5_years,
        prox_num_school_in_half_mile,
        prox_num_school_with_rating_in_half_mile,
        prox_avg_school_rating_in_half_mile,
        prox_nearest_bike_trail_dist_ft,
        prox_nearest_cemetery_dist_ft,
        prox_nearest_cta_route_dist_ft,
        prox_nearest_cta_stop_dist_ft,
        prox_nearest_hospital_dist_ft,
        prox_lake_michigan_dist_ft,
        prox_nearest_major_road_dist_ft,
        prox_nearest_metra_route_dist_ft,
        prox_nearest_metra_stop_dist_ft,
        prox_nearest_park_dist_ft,
        prox_nearest_railroad_dist_ft,
        prox_nearest_water_dist_ft,
        acs5_percent_age_children,
        acs5_percent_age_senior,
        acs5_median_age_total,
        acs5_percent_mobility_no_move,
        acs5_percent_mobility_moved_in_county,
        acs5_percent_mobility_moved_from_other_state,
        acs5_percent_household_family_married,
        acs5_percent_household_nonfamily_alone,
        acs5_percent_education_high_school,
        acs5_percent_education_bachelor,
        acs5_percent_education_graduate,
        acs5_percent_income_below_poverty_level,
        acs5_median_income_household_past_year,
        acs5_median_income_per_capita_past_year,
        acs5_percent_income_household_received_snap_past_year,
        acs5_percent_employment_unemployed,
        acs5_median_household_total_occupied_year_built,
        acs5_median_household_renter_occupied_gross_rent,
        acs5_median_household_owner_occupied_value,
        acs5_percent_household_owner_occupied,
        acs5_percent_household_total_occupied_w_sel_cond,
        other_ihs_avg_year_index,
        other_tax_bill_amount_total,
        other_tax_bill_rate,
        other_school_district_elementary_avg_rating,
        other_school_district_secondary_avg_rating,
        time_sale_year,
        time_sale_week,
        time_sale_quarter_of_year,
        time_sale_week_of_year,
        time_sale_during_school_year,
        time_sale_during_holidays
    ]) a2 (feature_name, feature_shap)
)
SELECT 
    f.run_id,
    f.meta_year,
    f.meta_pin,
    f.meta_card_num,
    f.feature_name,
    f.feature_value,
    s.feature_shap,
    f.year,
    f.township_code
FROM features f
LEFT JOIN shaps s
    ON f.meta_year = s.meta_year
    AND f.meta_pin = s.meta_pin
    AND f.meta_card_num = s.meta_card_num
    AND f.feature_name = s.feature_name
    AND f.year = s.year
    AND f.run_id = s.run_id
    AND f.township_code = s.township_code
