sources:
  - name: sale
    tables:
      - name: flag
        description: '{{ doc("flag") }}'
        tags:
          - load_auto

        columns:
          - name: group
            description: '{{ doc("column_group_id") }}'
          - name: meta_sale_document_number
            description: '{{ doc("shared_column_document_number") }}'
          - name: ptax_flag_original
            description: |
              Whether or not this sale was flagged on certain Q10 
              line items of the PTAX-203 form.
          - name: rolling_window
            description: '{{ doc("column_rolling_window") }}'
          - name: run_id
            description: '{{ doc("shared_column_sv_run_id") }}'
          - name: sv_is_heuristic_outlier
            description: '{{ doc("shared_column_sv_is_heuristic_outlier") }}'
          - name: sv_is_outlier
            description: '{{ doc("shared_column_sv_is_outlier") }}'
          - name: sv_is_ptax_outlier
            description: '{{ doc("shared_column_sv_is_ptax_outlier") }}'
          - name: sv_outlier_reason1
            description: '{{ doc("shared_column_sv_outlier_reason") }}'
            data_tests:
              - not_null:
                  name: sale_flag_sv_outlier_reason1_not_null_when_sv_is_outlier
                  config:
                    where: sv_is_outlier
                  meta:
                    description: sv_outlier_reason1 is not null when sv_is_outlier
          - name: sv_outlier_reason2
            description: '{{ doc("shared_column_sv_outlier_reason") }}'
          - name: sv_outlier_reason3
            description: '{{ doc("shared_column_sv_outlier_reason") }}'
          - name: version
            description: '{{ doc("shared_column_sv_version") }}'

        data_tests:
          - unique_combination_of_columns:
              name: sale_flag_unique_by_doc_num_version
              combination_of_columns:
                - meta_sale_document_num
                - version
              meta:
                description: flag is unique by meta_sale_document_num and version

      - name: flag_override
        description: '{{ doc("flag_override") }}'
        columns:
          - name: doc_no
            description: '{{ doc("shared_column_document_number") }}'
          - name: is_valid_for_modeling
            description: Whether or not to exclude the sale from the model training data b
                         based on analyst decision between arms length and characteristic classification
        data_tests:
          - unique_combination_of_columns:
              name: sale_flag_override_unique_by_doc_no
              combination_of_columns:
                - doc_no

      - name: foreclosure
        description: '{{ doc("foreclosure") }}'
        tags:
          - load_manual
        data_tests:
          - unique_combination_of_columns:
              name: sale_foreclosure_unique
              combination_of_columns:
                - case_number
                - pin
                - sale_results
                - date_of_sale
              meta:
                description: foreclosure is unique by case_number, pin, sale_results and date_of_sale
              config:
                error_if: ">1"

      - name: group_mean
        description: '{{ doc("group_mean") }}'
        tags:
          - load_auto
        data_tests:
          - unique_combination_of_columns:
              name: sale_group_mean_unique_by_group_run_id
              combination_of_columns:
                - '"group"'
                - run_id
              meta:
                description: group_mean is unique by group and run_id

        columns:
          - name: group
            description: '{{ doc("column_group_id") }}'
          - name: group_size
            description: '{{ doc("column_group_size") }}'
          - name: mean_price
            description: Mean price of the group, in FMV
          - name: mean_price_per_sqft
            description: Mean price per sqft (of building) of the group, in FMV
          - name: run_id
            description: '{{ doc("shared_column_sv_run_id") }}'

      - name: parameter
        description: '{{ doc("parameter") }}'
        tags:
          - load_auto
        data_tests:
          - unique_combination_of_columns:
              name: sale_parameter_unique_by_run_id
              combination_of_columns:
                - run_id
              meta:
                description: parameter is unique by run_id

        columns:
          - name: condo_stat_groups
            description: |
              Groups used to calculate flagging statistics (std. dev.)
              for condominium (class 299, 399) properties
          - name: dev_bounds
            description: |
              Boundaries for standard deviation flagging.

              Sales with prices beyond these boundaries are flagged.
          - name: earliest_data_ingest
            description: |
              Date of earliest sale used in validation.

              This inclusive of the rolling window period used for
              calculating statistical groups. In other words, if the earliest
              sale to-be-flagged is 2013-12-01 and the rolling window period
              is 9 months, then the earliest sale *used* would be 2013-03-01
          - name: iso_forest_cols
            description: Columns used as features in the isolation forest model
          - name: latest_data_ingest
            description: Date of latest sale used in validation
          - name: min_group_thresh
            description: '{{ doc("column_min_group_thresh") }}'
          - name: ptax_sd
            description: |
              Boundaries for standard deviation flagging in combination
              with a PTAX-203 flag
          - name: res_stat_groups
            description: |
              Groups used to calculate flagging statistics (std. dev.)
              for residential (class 2) properties
          - name: rolling_window
            description: '{{ doc("column_rolling_window") }}'
          - name: run_id
            description: '{{ doc("shared_column_sv_run_id") }}'
          - name: sales_flagged
            description: |
              Total number of sales flagged.

              Inclusive of both sales flagged as outliers *and* sales
              flagged as non-outliers
          - name: short_term_owner_threshold
            description: |
              Properties with a significant price change and multiple
              sales within this time duration (in days) are flagged


      - name: metadata
        description: '{{ doc("metadata") }}'
        tags:
          - load_auto
        data_tests:
          - unique_combination_of_columns:
              name: sale_metadata_unique_by_run_id
              combination_of_columns:
                - run_id
              meta:
                description: metadata is unique by run_id

        columns:
          - name: long_commit_sha
            description: Full commit SHA of the code used for the model run
          - name: run_id
            description: '{{ doc("shared_column_sv_run_id") }}'
          - name: run_timestamp
            description: Start timestamp of the model run
          - name: run_type
            description: |
              Type of model run.

              Variable can be one of `initial_flagging`, `recurring`,
              or `manual_update`
          - name: short_commit_sha
            description: Short commit SHA of the code used for the model run

        data_tests:
          - unique:
              name: sale_metadata_singular_initial_run
              column_name: run_id
              config:
                where: run_id = 'initial_flagging'

      - name: mydec
        description: '{{ doc("mydec") }}'
        tags:
          - load_manual
        data_tests:
          - unique_combination_of_columns:
              name: sale_mydec_unique_by_document_number
              combination_of_columns:
                - document_number
              config:
                where: not is_multisale
              meta:
                description: mydec is unique by document_number

models:
  - name: sale.vw_ias_salesval_upload
    description: '{{ doc("vw_ias_salesval_upload") }}'
    data_tests:
      - unique_combination_of_columns:
          name: sale_vw_ias_salesval_upload_unique_by_salekey_run_id
          combination_of_columns:
            - salekey
            - run_id
          meta:
            description: vw_ias_salesval_upload is unique by salekey and run_id

    columns:
      - name: run_id
        description: '{{ doc("shared_column_sv_run_id") }}'
      - name: salekey
        description: '{{ doc("shared_column_sale_key") }}'
      - name: sv_is_outlier
        description: '{{ doc("shared_column_sv_is_outlier") }}'
      - name: sv_outlier_reason1
        description: '{{ doc("shared_column_sv_outlier_reason") }}'
      - name: sv_outlier_reason2
        description: '{{ doc("shared_column_sv_outlier_reason") }}'
      - name: sv_outlier_reason3
        description: '{{ doc("shared_column_sv_outlier_reason") }}'
  - name: sale.vw_flag_group
    description: '{{ doc("vw_flag_group") }}'

    columns:
      - name: doc_no
        description: '{{ doc("shared_column_document_number") }}'
      - name: group_id
        description: '{{ doc("column_group_id") }}'
      - name: group_size
        description: '{{ doc("column_group_size") }}'
      - name: meets_group_threshold
        description: |
          If a group's `group_size` is under a certain threshold, we decide to
          automatically set the `sv_is_outlier` status to `False`. This is a binary
          column that tells us if that threshold is met or not.
          
          A caveat is that even if the threshold is not met, sales with certain
          line items marked on the ptax-203 form can still be classified as an
          outlier.
      - name: min_group_thresh
        description: '{{ doc("column_min_group_thresh") }}'
      - name: pin
        description: '{{ doc("shared_column_pin") }}'
      - name: ptax_flag
        description: |
          Whether or not this sale was flagged on certain Q10 
          line items of the PTAX-203 form.
      - name: run_id
        description: '{{ doc("shared_column_sv_run_id") }}'
      - name: sale_date
        description: '{{ doc("shared_column_sale_date") }}'
      - name: sale_price
        description: '{{ doc("shared_column_sale_price") }}'
      - name: sv_is_outlier
        description: '{{ doc("shared_column_sv_is_outlier") }}'
      - name: sv_is_ptax_outlier
        description: '{{ doc("shared_column_sv_is_ptax_outlier") }}'
      - name: sv_outlier_reason1
        description: '{{ doc("shared_column_sv_outlier_reason") }}'
      - name: sv_outlier_reason2
        description: '{{ doc("shared_column_sv_outlier_reason") }}'
      - name: sv_outlier_reason3
        description: '{{ doc("shared_column_sv_outlier_reason") }}'

    data_tests:
      - unique_combination_of_columns:
          name: sale_vw_flag_group_unique_by_run_id_and_doc_no
          combination_of_columns:
            - run_id
            - doc_no
          config:
            # This threshold is based on an existing data problem in which there are
            # 4 violations of this assumption
            # more details: https://github.com/ccao-data/data-architecture/pull/913#discussion_r2475427865
            # If there are any more duplicates, we will be pushed over 4 and this test will flag it
            error_if: ">4"
