name: build-and-test-dbt-daily-assets

on:
  schedule:
    # Run daily at 7am
    - cron: '0 7 * * *'

jobs:
  build-and-test-dbt-daily-assets:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    # so that we can authenticate with AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dbt
        uses: ./.github/actions/setup_dbt
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          role-duration-seconds: 900

      - name: Restore dbt state cache
        id: cache
        uses: ./.github/actions/restore_dbt_cache
        with:
          path: ${{ env.PROJECT_DIR }}/${{ env.STATE_DIR }}
          key: ${{ env.CACHE_KEY }}

      - name: Set command args for building/testing resources
        run: |
          if [[ $CACHE_HIT == 'true' ]]; then
            echo "MODIFIED_RESOURCES_ONLY=true" >> "$GITHUB_ENV"
          fi
          if [[ $EVENT_NAME == 'workflow_dispatch' ]]; then
              echo "MANUALLY_DISPATCHED=true" >> "$GITHUB_ENV"
          fi
        shell: bash
        env:
          CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}
          EVENT_NAME: ${{ github.event_name }}

      - name: Build daily assets
        run: dbt run --full-refresh -t "$TARGET" --select tag:daily --defer --state "$STATE_DIR"
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash

      - name: Test daily assets
        run: |
          dbt test -t "$TARGET" --select tag:daily --defer --state "$STATE_DIR"
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash

      - if: github.ref == 'refs/heads/master' && success()
        name: Update dbt state cache
        uses: ./.github/actions/save_dbt_cache
        with:
          path: ${{ env.PROJECT_DIR }}/${{ env.TARGET_DIR }}
          key: ${{ env.CACHE_KEY }}

      - name: Send failure notification
        if: failure()
        uses: ./.github/actions/publish_sns_topic
        with:
          sns_topic_arn: ${{ secrets.AWS_SNS_NOTIFICATION_TOPIC_ARN }}
          subject: "Daily dbt asset creation failed in workflow run: ${{ github.run_id }}"
          body: |
            Daily dbt asset creation failed for workflow ${{ github.run_id }}, run on ${{ env.TIMESTAMP }} UTC

            Link to failing workflow:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
