name: check-sort-dbt-yaml-files

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check-sort-dbt-yaml-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: Run dbt yaml sort checks
      #run: pwd
      run: python check_sort_dbt_yaml_files.py
      working_directory: dbt/scripts/
      #run: python dbt/scripts/check_sort_dbt_yaml_files.py
      #working_directory: dbt
