name: check-sort-dbt-yaml-files

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  check-sort-dbt-yaml-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: |
          dbt/pyproject.toml
          dbt/uv.lock

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: dbt/.python-version

    - name: Install Python dependencies
      working-directory: dbt
      shell: bash
      run: uv pip install ".[ci_checks]"

    - name: Run dbt yaml sort checks
      working-directory: dbt
      run: python scripts/check_sort_dbt_yaml_files.py
