on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

name: super-linter

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      # Superlinter will load renv if .Rprofile is present - it will then fail
      # because the renv environment doesn't have lintr. Removing the .Rprofile
      # file loads the default superlinter R environment.
      - name: Disable renv
        shell: bash
        run: rm etl/.Rprofile

      - name: Lint
        uses: super-linter/super-linter@9e863354e3ff62e0727d37183162c4a88873df41 # v8.6.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: false
          VALIDATE_MARKDOWN_PRETTIER: false
          # These tools are either handled by pre-commit, or we don't use them,
          # so we exclude them from superlinter
          VALIDATE_CHECKOV: false
          VALIDATE_SPELL_CODESPELL: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_RUFF: false
          VALIDATE_R: false
          VALIDATE_TRIVY: false
          VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
          VALIDATE_BIOME_FORMAT: false
          VALIDATE_BIOME_LINT: false
          # The natural language check slows down our velocity and is rarely
          # helpful
          VALIDATE_NATURAL_LANGUAGE: false
          # We use yamllint for YAML linting so we don't need prettier
          VALIDATE_YAML_PRETTIER: false
          # We have a separate workflow for pre-commit
          VALIDATE_PRE_COMMIT: false
          LINTER_RULES_PATH: /
          YAML_CONFIG_FILE: .yamllint.yml
