name: Check Sorting

on: [push, pull_request]

jobs:
  check-sorting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    - name: List files in dbt/scripts
      run: ls dbt/scripts
    - name: Run YAML column sorting check
      run: python dbt/scripts/check_sort.py .
