name: test-dbt-models

on: workflow_dispatch

jobs:
  test-dbt-models:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    # so that we can authenticate with AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dbt
        uses: ./.github/actions/setup_dbt
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}

      - name: Test models
        run: dbt test --target "$TARGET"
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash

      - name: Send failure notification
        # if: failure()
        uses: ./.github/actions/send_notification
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          sns-topic-arn: ${{ secrets.AWS_SNS_NOTIFICATION_TOPIC_ARN }}
