name: Test dbt models

on:
  pull_request:
    branches: [master, data-catalog]
  workflow_dispatch:
    inputs:
      use_build_cache:
        description: >-
          Use the master branch build cache to avoid rebuilding models.
        type: boolean
        required: false
        default: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    # so that we can authenticate with AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dbt requirements
        uses: ./.github/actions/install_dbt_requirements

      - name: Load environment variables
        uses: ./.github/actions/load_environment_variables

      - if: ${{ inputs.use_build_cache }}
        name: Cache dbt manifest
        uses: actions/cache@v3
        with:
          path: ${{ env.MANIFEST_DIR }}
          key: ${{ env.CACHE_NAME }}-master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}
          aws-region: us-east-1

      - name: Test models
        run: dbt test --target prod
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash
