name: test-dbt-source-freshness

on:
  schedule:
    # Every day at 8am (2pm UTC-5)
    - cron: '0 13 * * *'

jobs:
  test-dbt-source-freshness:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint
    # so that we can authenticate with AWS
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dbt
        uses: ./.github/actions/setup_dbt
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME_ARN }}

      - name: Test source freshness
        run: dbt source freshness --target "$TARGET"
        working-directory: ${{ env.PROJECT_DIR }}
        shell: bash
