name: Test dbt models

on:
  workflow_dispatch:
    inputs:
      use_build_cache:
        description: >-
          Use the master branch build cache to avoid rebuilding models.
        type: boolean
        required: true
        default: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dbt requirements
        uses: ./.github/actions/install_dbt_requirements.yaml

      - if: ${{ inputs.use_build_cache }}
        name: Cache dbt manifest
        uses: actions/cache@v3
        with:
          path: ./dbt/target
          key: cache-dbt-run-master

      # TODO: AWS configuration?

      - name: Test models
        run: dbt test --target prod
        working-directory: ./dbt
        shell: bash
