models:
  - name: qc.vw_asmt_value
    description: '{{ doc("view_vw_asmt_value") }}'
    config:
      tags:
        - test_qc_val_first_pass
    columns:
      - name: val01
        tests:
          - dbt_utils.accepted_range: &test-non-negative
              name: qc_vw_asmt_value_val01_gte_0
              min_value: 0
              config:
                where: taxyr >= '2023'
      - name: val02
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val02_gte_0
              <<: *test-non-negative
      - name: val03
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val03_gte_0
              <<: *test-non-negative
      - name: val04
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val04_gte_0
              <<: *test-non-negative
      - name: val05
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val05_gte_0
              <<: *test-non-negative
      - name: val06
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val06_gte_0
              <<: *test-non-negative
      - name: val07
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val07_gte_0
              <<: *test-non-negative
      - name: val08
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val08_gte_0
              <<: *test-non-negative
      - name: val09
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val09_gte_0
              <<: *test-non-negative
      - name: val10
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val10_gte_0
              <<: *test-non-negative
      - name: val11
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val11_gte_0
              <<: *test-non-negative
      - name: val12
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val12_gte_0
              <<: *test-non-negative
      - name: val13
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val13_gte_0
              <<: *test-non-negative
      - name: val14
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val14_gte_0
              <<: *test-non-negative
      - name: val15
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val15_gte_0
              <<: *test-non-negative
      - name: val16
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val16_gte_0
              <<: *test-non-negative
      - name: val17
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val17_gte_0
              <<: *test-non-negative
      - name: val18
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val18_gte_0
              <<: *test-non-negative
      - name: val19
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val19_gte_0
              <<: *test-non-negative
      - name: val20
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val20_gte_0
              <<: *test-non-negative
      - name: val21
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val21_gte_0
              <<: *test-non-negative
      - name: val22
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val22_gte_0
              <<: *test-non-negative
      - name: val23
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val23_gte_0
              <<: *test-non-negative
      - name: val24
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val24_gte_0
              <<: *test-non-negative
      - name: val25
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val25_gte_0
              <<: *test-non-negative
      - name: val26
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val26_gte_0
              <<: *test-non-negative
      - name: val27
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val27_gte_0
              <<: *test-non-negative
      - name: val28
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val28_gte_0
              <<: *test-non-negative
      - name: val29
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val29_gte_0
              <<: *test-non-negative
      - name: val30
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val30_gte_0
              <<: *test-non-negative
      - name: val31
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val31_gte_0
              <<: *test-non-negative
      - name: val32
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val32_gte_0
              <<: *test-non-negative
      - name: val33
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val33_gte_0
              <<: *test-non-negative
      - name: val34
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val34_gte_0
              <<: *test-non-negative
      - name: val35
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val35_gte_0
              <<: *test-non-negative
      - name: val36
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val36_gte_0
              <<: *test-non-negative
      - name: val37
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val37_gte_0
              <<: *test-non-negative
      - name: val38
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val38_gte_0
              <<: *test-non-negative
      - name: val39
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val39_gte_0
              <<: *test-non-negative
      - name: val40
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val40_gte_0
              <<: *test-non-negative
      - name: val41
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val41_gte_0
              <<: *test-non-negative
      - name: val42
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val42_gte_0
              <<: *test-non-negative
      - name: val43
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val43_gte_0
              <<: *test-non-negative
      - name: val44
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val44_gte_0
              <<: *test-non-negative
      - name: val45
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val45_gte_0
              <<: *test-non-negative
      - name: val46
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val46_gte_0
              <<: *test-non-negative
      - name: val47
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val47_gte_0
              <<: *test-non-negative
      - name: val48
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val48_gte_0
              <<: *test-non-negative
      - name: val49
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val49_gte_0
              <<: *test-non-negative
      - name: val50
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val50_gte_0
              <<: *test-non-negative
      - name: val51
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val51_gte_0
              <<: *test-non-negative
      - name: val52
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val52_gte_0
              <<: *test-non-negative
      - name: val53
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val53_gte_0
              <<: *test-non-negative
      - name: val54
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val54_gte_0
              <<: *test-non-negative
      - name: val55
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val55_gte_0
              <<: *test-non-negative
      - name: val56
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val56_gte_0
              <<: *test-non-negative
      - name: val57
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val57_gte_0
              <<: *test-non-negative
      - name: val58
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val58_gte_0
              <<: *test-non-negative
      - name: val59
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val59_gte_0
              <<: *test-non-negative
      - name: val60
        tests:
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_val60_gte_0
              <<: *test-non-negative
      - name: valapr1
        tests:
          - not_null: &test-val-non-null
              name: qc_vw_asmt_value_valapr1_not_null
              config:
                where: taxyr >= '2023'
                error_if: ">702"
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valapr1_gte_0
              <<: *test-non-negative
      - name: valapr2
        tests:
          - not_null:
              name: qc_vw_asmt_value_valapr2_not_null
              <<: *test-val-non-null
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valapr2_gte_0
              <<: *test-non-negative
      - name: valapr3
        tests:
          - not_null:
              name: qc_vw_asmt_value_valapr3_not_null
              <<: *test-val-non-null
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valapr3_gte_0
              <<: *test-non-negative
      - name: valasm1
        tests:
          - not_null:
              name: qc_vw_asmt_value_valasm1_not_null
              <<: *test-val-non-null
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valasm1_gte_0
              <<: *test-non-negative
          # Equivalent to 0 Land Value test from FP Checklist
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valasm1_non_ex_rr_gt_0
              min_value: 0
              inclusive: false
              config:
                where: |
                  taxyr >= '2023'
                  AND class NOT IN ('EX', 'RR')
      - name: valasm2
        tests:
          - not_null:
              name: qc_vw_asmt_value_valasm2_not_null
              <<: *test-val-non-null
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valasm2_gte_0
              <<: *test-non-negative
      - name: valasm3
        tests:
          - not_null:
              name: qc_vw_asmt_value_valasm3_not_null
              <<: *test-val-non-null
          - dbt_utils.accepted_range:
              name: qc_vw_asmt_value_valasm3_gte_0
              <<: *test-non-negative
