models:
  - name: qc.vw_neg_asmt_value
    description: '{{ doc("view_vw_neg_asmt_value") }}'
    columns:
      - name: val01
        tests: &test-non-negative
          - dbt_utils.accepted_range:
              min_value: 0
              config:
                where: taxyr >= '2023'
      - name: val02
        tests: *test-non-negative
      - name: val03
        tests: *test-non-negative
      - name: val04
        tests: *test-non-negative
      - name: val05
        tests: *test-non-negative
      - name: val06
        tests: *test-non-negative
      - name: val07
        tests: *test-non-negative
      - name: val08
        tests: *test-non-negative
      - name: val09
        tests: *test-non-negative
      - name: val10
        tests: *test-non-negative
      - name: val11
        tests: *test-non-negative
      - name: val12
        tests: *test-non-negative
      - name: val13
        tests: *test-non-negative
      - name: val14
        tests: *test-non-negative
      - name: val15
        tests: *test-non-negative
      - name: val16
        tests: *test-non-negative
      - name: val17
        tests: *test-non-negative
      - name: val18
        tests: *test-non-negative
      - name: val19
        tests: *test-non-negative
      - name: val20
        tests: *test-non-negative
      - name: val21
        tests: *test-non-negative
      - name: val22
        tests: *test-non-negative
      - name: val23
        tests: *test-non-negative
      - name: val24
        tests: *test-non-negative
      - name: val25
        tests: *test-non-negative
      - name: val26
        tests: *test-non-negative
      - name: val27
        tests: *test-non-negative
      - name: val28
        tests: *test-non-negative
      - name: val29
        tests: *test-non-negative
      - name: val30
        tests: *test-non-negative
      - name: val31
        tests: *test-non-negative
      - name: val32
        tests: *test-non-negative
      - name: val33
        tests: *test-non-negative
      - name: val34
        tests: *test-non-negative
      - name: val35
        tests: *test-non-negative
      - name: val36
        tests: *test-non-negative
      - name: val37
        tests: *test-non-negative
      - name: val38
        tests: *test-non-negative
      - name: val39
        tests: *test-non-negative
      - name: val40
        tests: *test-non-negative
      - name: val41
        tests: *test-non-negative
      - name: val42
        tests: *test-non-negative
      - name: val43
        tests: *test-non-negative
      - name: val44
        tests: *test-non-negative
      - name: val45
        tests: *test-non-negative
      - name: val46
        tests: *test-non-negative
      - name: val47
        tests: *test-non-negative
      - name: val48
        tests: *test-non-negative
      - name: val49
        tests: *test-non-negative
      - name: val50
        tests: *test-non-negative
      - name: val51
        tests: *test-non-negative
      - name: val52
        tests: *test-non-negative
      - name: val53
        tests: *test-non-negative
      - name: val54
        tests: *test-non-negative
      - name: val55
        tests: *test-non-negative
      - name: val56
        tests: *test-non-negative
      - name: val57
        tests: *test-non-negative
      - name: val58
        tests: *test-non-negative
      - name: val59
        tests: *test-non-negative
      - name: val60
        tests: *test-non-negative
      - name: valapr1
        tests: &test-non-null-and-non-negative
          - not_null:
              config:
                where: taxyr >= '2023'
                error_if: ">702"
          - dbt_utils.accepted_range:
              min_value: 0
              config:
                where: taxyr >= '2023'
      - name: valapr2
        tests: *test-non-null-and-non-negative
      - name: valapr3
        tests: *test-non-null-and-non-negative
      - name: valasm1
        tests: *test-non-null-and-non-negative
      - name: valasm2
        tests: *test-non-null-and-non-negative
      - name: valasm3
        tests: *test-non-null-and-non-negative
